
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<div class="info">VENEZUELA</div>

<p></p>

<p></p>

<p></p>

<p></p>
<a href="http://www.fiesta-casino.net" target="_new">www.fiesta-casino.net</a><br>
<div class="info">Casino y diversión. Juegos de mesas, maquinitas y agradable atención</div>

<p></p>
<a href="http://www.goldfingersvenezuela.com" target="_new">www.goldfingersvenezuela.com</a><br>
<div class="info">Discoteca, en la Isla de Margarita, Venezuela</div>

<p></p>
<a href="http://www.lagartosdisc.com" target="_new">www.lagartosdisc.com</a><br>
<div class="info">Local nocturno ubicado en Los Ruices.</div>

<p></p>
<a href="http://www.zonavip.net" target="_new">www.zonavip.net</a><br>
<div class="info">Portal donde encontrarás información sobre eventos y más.</div>

<p></p>
<a href="http://www.arumbear.com" target="_new">www.arumbear.com</a><br>
<div class="info">Revista rumbera de Venezuela.</div>

<p></p>
<a href="http://www.geocities.com/SouthBeach/Lagoon/1782" target="_new">www.geocities.com/SouthBeach/Lagoon/1782</a><br>
<div class="info">Fiestas de música house y techno, vida nocturna en Mérida.</div>

<p></p>
<a href="http://www.buscarumba.com" target="_new">www.buscarumba.com</a><br>
<div class="info">Su guía on line para la mejor rumba en la Isla de Margarita.</div>

<p></p>
<a href="http://www.Caracas.DNoche.com" target="_new">www.Caracas.DNoche.com</a><br>
<div class="info">Las mejores rumbas de Caracas.</div>

<p></p>
<a href="http://debarranco.com" target="_new">debarranco.com</a><br>
<div class="info">Site donde conseguirás el mejor ambiente de la vida nocturna caraqueña.</div>

<p></p>
<a href="http://www.discobus.com.ve" target="_new">www.discobus.com.ve</a><br>
<div class="info">diversas discotecas de Caracas en autobús</div>

<p></p>
<a href="http://www.geocities.com/djplanet80/miniteka1.html" target="_new">www.geocities.com/djplanet80/miniteka1.html</a><br>
<div class="info">Luces y sonido. Miniteca en San Cristóbal, Edo. Táchira.</div>

<p></p>
<a href="http://www.djpattyjr.550m.com" target="_new">www.djpattyjr.550m.com</a><br>
<div class="info">Dj residente de la miniteca New York, New York.</div>

<p></p>

<p></p>
<a href="http://www.enrumbate.com" target="_new">www.enrumbate.com</a><br>
<div class="info">Site para enrumbarse en Caracas.</div>

<p></p>
<a href="http://www.fondoblanco.com" target="_new">www.fondoblanco.com</a><br>
<div class="info">Lo mejor de las noches caraqueñas, eventos, espectáculos e historias.</div>

<p></p>
<a href="http://caracas.eluniversal.com" target="_new">caracas.eluniversal.com</a><br>
<div class="info">Guía de entretenimiento de Caracas por Internet.</div>

<p></p>
<a href="http://www.megarumba.com" target="_new">www.megarumba.com</a><br>
<div class="info">Eventos y rumbas y la mejor música en formato Mp3.</div>

<p></p>
<a href="http://www.ovnidiscplay.com" target="_new">www.ovnidiscplay.com</a><br>
<div class="info">Portal de entretenimiento.</div>

<p></p>
<a href="http://www.planetaurbe.com" target="_new">www.planetaurbe.com</a><br>
<div class="info">eventos y más de la movida caraqueña</div>

<p></p>
<a href="http://www.rumbaenpuertolacruz.com" target="_new">www.rumbaenpuertolacruz.com</a><br>
<div class="info">Página con toda la diversión de Puerto La Cruz.</div>

<p></p>
<a href="http://www.rumbacaracas.com" target="_new">www.rumbacaracas.com</a><br>
<div class="info">Rumbas en los mejores sitios de Caracas.</div>

<p></p>
<a href="http://www.sinflash.com" target="_new">www.sinflash.com</a><br>
<div class="info">Site de los mejores eventos y todo el esplendor nocturno de caracas.</div>

<p></p>
<a href="http://www.tubarranco.com" target="_new">www.tubarranco.com</a><br>
<div class="info">Directorio del oriente del país de locales de belleza, comida y diversión..</div>

<p></p>
<a href="http://www.laterrazademargarita.com/index2.htm" target="_new">www.laterrazademargarita.com/index2.htm</a><br>
<div class="info">la mejor rumba de margarita con la mejor musica.</div>

<p></p>
<div class="info">hancgarlacastellana@cantv.net<br>La Castellana, Diagonal al Instituto Diseño de Caracas</div>

<p></p>
<a href="http://www.restauranttantra.com" target="_new">www.restauranttantra.com</a><br>
<div class="info">Restaurant Tantra C. C. Plaza Los Naranjos</div>

<p></p>
<a href="http://www.gradassportbar.com" target="_new">www.gradassportbar.com</a><br>
<div class="info">Sport Bar</div>

<p></p>
<a href="http://www.fondoblanco.com" target="_new">www.fondoblanco.com</a><br>
<div class="info">Lo mejor de las noches caraqueñas, eventos, espectáculos e historias.</div>

<p></p>
<a href="http://caracas.eluniversal.com" target="_new">caracas.eluniversal.com</a><br>
<div class="info">Guía de entretenimiento de Caracas por Internet.</div>

<p></p>
<a href="http://www.ovnidiscplay.com" target="_new">www.ovnidiscplay.com</a><br>
<div class="info">Portal de entretenimiento con secciones de interés.</div>

<p></p>
<a href="http://www.supermusica.com.ve" target="_new">www.supermusica.com.ve</a><br>
<div class="info">Portal de noticias, chismes en Venezuela.</div>
