
	
	  <p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<div class="info">BARCELONA</div>

<p></p>

<p></p>
<a href="http://www.albamolas.com" target="_new">www.albamolas.com</a><br>
<div class="info">ALBA MOLAS RIFA<br>CINE Y VIDEO: DISTRIBUCION . CINES .</div>

<p></p>
<a href="http://www.cinesa.es" target="_new">www.cinesa.es</a><br>
<div class="info">COMEDIA CINES .</div>

<p></p>
<a href="http://www.cinesa.es" target="_new">www.cinesa.es</a><br>
<div class="info">MONTIGALA CINES .</div>

<p></p>
<a href="http://www.cinesa.es" target="_new">www.cinesa.es</a><br>
<div class="info">CINESA ESPECTACULOS: LOCALIDADES . CINES .</div>

<p></p>
<a href="http://www.cinesa.es" target="_new">www.cinesa.es</a><br>
<div class="info">CINE ALEXIS CINES .BARCELONA</div>

<p></p>
<a href="http://www.grupbalana.com" target="_new">www.grupbalana.com</a><br>
<div class="info">GRAN SARRIA CINES . TEATROS . BARCELONA</div>

<p></p>
<a href="http://www.servicom.es" target="_new">www.servicom.es</a><br>
<div class="info">CINES PICAROL CINES .BARCELONA</div>

<p></p>
<a href="http://WWW.GRUPBALANA.ES" target="_new">WWW.GRUPBALANA.ES</a><br>
<div class="info">CINE ALCAZAR CINES BARCELONA</div>

<p></p>
<a href="http://www.serviticket.com" target="_new">www.serviticket.com</a><br>
<div class="info">TEATRO BORRAS CINES . TEATROS .BARCELONA</div>

<p></p>
<a href="http://WWW.serviticket.com" target="_new">WWW.serviticket.com</a><br>
<div class="info">CINE REX CINES .BARCELONA</div>

<p></p>
<a href="http://WWW.SERVITICKET.COM" target="_new">WWW.SERVITICKET.COM</a><br>
<div class="info">CINE CLUB DORE CINES .BARCELONA</div>

<p></p>
<a href="http://www.grupbalana.es" target="_new">www.grupbalana.es</a><br>
<div class="info">BOSQUE MIULTICINES CINES .BARCELONA</div>

<p></p>
<a href="http://www.lacaixa.es" target="_new">www.lacaixa.es</a><br>
<div class="info">CINES NAPOLS CINES .BARCELONA</div>

<p></p>
<a href="http://www.servicom.es" target="_new">www.servicom.es</a><br>
<div class="info">CINE RAMBLA CINE: PRODUCTORAS . CINES .BARCELONA</div>

<p></p>
<a href="http://www.laurenfilm.es" target="_new">www.laurenfilm.es</a><br>
<div class="info">MULTICINES LAUREN UNIVERSITAT CINES .BARCELONA</div>

<p></p>
<a href="http://WWW.GRUPBALANA.ES" target="_new">WWW.GRUPBALANA.ES</a><br>
<div class="info">CINE ALCAZAR CINES .BARCELONA</div>

<p></p>
<a href="http://www.serviticket.com" target="_new">www.serviticket.com</a><br>
<div class="info">TEATRO BORRAS CINES . TEATROS .BARCELONA</div>

<p></p>
<a href="http://www.serviticket.com" target="_new">www.serviticket.com</a><br>
<div class="info">CINE REX CINES .BARCELONA</div>

<p></p>
<a href="http://WWW.SERVITICKET.COM" target="_new">WWW.SERVITICKET.COM</a><br>
<div class="info">CINE CLUB DORE CINES .BARCELONA</div>

<p></p>
<a href="http://www.lacaixa.es" target="_new">www.lacaixa.es</a><br>
<div class="info">CINES NAPOLS CINES .BARCELONA</div>

<p></p>
<a href="http://www.servicom.es" target="_new">www.servicom.es</a><br>
<div class="info">CINE RAMBLA CINE: PRODUCTORAS . CINES .BARCELONA</div>

<p></p>
<a href="http://www.laurenfilm.es" target="_new">www.laurenfilm.es</a><br>
<div class="info">MULTICINES LAUREN UNIVERSITAT CINES .BARCELONA</div>

<p></p>
<a href="http://www.serviticket.com" target="_new">www.serviticket.com</a><br>
<div class="info">CINES URGEL CINES BARCELONA</div>

<p></p>
<a href="http://www.multicinesllobregat.com" target="_new">www.multicinesllobregat.com</a><br>
<div class="info">MULTICINEMAS LLOBREGAT S.A. CINES .BARCELONA</div>

<p></p>
<a href="http://www.servicom.es" target="_new">www.servicom.es</a><br>
<div class="info">MULTICINEMAS LLOBREGAT S.A. CINES .BARCELONA</div>

<p></p>
<a href="http://www.filmax.com" target="_new">www.filmax.com</a><br>
<div class="info">MULTICINES FILMAX GRAN VIA CINES .BARCELONA</div>

<p></p>
<a href="http://www.imaxportvell.com" target="_new">www.imaxportvell.com</a><br>
<div class="info">IMAX PORT VELL CINES . CINE: PRODUCTORAS .BARCELONA</div>

<p></p>
<a href="http://www.amccines.com" target="_new">www.amccines.com</a><br>
<div class="info">AMC 24 PARC VALLES CINES .BARCELONA</div>

<p></p>
<a href="http://www.sucrecines.com" target="_new">www.sucrecines.com</a><br>
<div class="info">CINE SUCRE CINES .BARCELONA</div>

<p></p>
<a href="http://www.cinesrenoir.com" target="_new">www.cinesrenoir.com</a><br>
<div class="info">CINE RENOIR - LES CORTS CINES .BARCELONA</div>

<p></p>
<a href="http://www.laurenfilm.es" target="_new">www.laurenfilm.es</a><br>
<div class="info">LAUREN GRACIA CINEMES CINES .BARCELONA</div>

<p></p>
<a href="http://www.cinemacatalanya.com" target="_new">www.cinemacatalanya.com</a><br>
<div class="info">CINE CATALUNYA CINES .BARCELONA</div>

<p></p>
<a href="http://www.laurenfilm.es" target="_new">www.laurenfilm.es</a><br>
<div class="info">LAUREN VILADECANS MULTICINES CINES .BARCELONA</div>

<p></p>
<a href="http://www.laurenfilm.es" target="_new">www.laurenfilm.es</a><br>
<div class="info">LAUREN HORTA MULTICINEMES CINES .BARCELONA</div>

<p></p>
<a href="http://WWW.SERVITICKET.COM" target="_new">WWW.SERVITICKET.COM</a><br>
<div class="info">BOLICHE CINES .BARCELONA</div>

<p></p>
<div class="info">info@f135.com www.f135.com<br>CINE FLORIDA 135 CINES .</div>

<p></p>
<a href="http://www.yelmocineplex.es" target="_new">www.yelmocineplex.es</a><br>
<div class="info">YELMO CINEPLEX</div>

<p></p>
<div class="info">BARCELONA www.barart.net<br>SALAS DE CONCIERTOS . CINES .</div>

<p></p>
<a href="http://www.servicom.es" target="_new">www.servicom.es</a><br>
<div class="info">MULTIPLEX BARNASUD CINES BARCELONA</div>

<p></p>
<a href="http://www.bowlingpedralbes.com" target="_new">www.bowlingpedralbes.com</a><br>
<div class="info">BOWLING PEDRALBES SA</div>

<p></p>
<a href="http://www.newperk.es" target="_new">www.newperk.es</a><br>
<div class="info">NEW PARK BOLERAS</div>

<p></p>
<a href="http://www.sweetrade.com" target="_new">www.sweetrade.com</a><br>
<div class="info">BARCELONA info@sweetrade.com<br>SWEETRADE EUROPE S.L.</div>

<p></p>
<a href="http://www.keisy.es clientes@keisy.es" target="_new">www.keisy.es clientes@keisy.es</a><br>
<div class="info">SUPERMERCATS KEISY" 08013 BARCELONA</div>

<p></p>
<a href="http://www.aventurapark.com/index2.htm" target="_new">www.aventurapark.com/index2.htm</a><br>
<div class="info">AVENTURA PARK</div>

<p></p>
<a href="http://www.dream-slot.com" target="_new">www.dream-slot.com</a><br>
<div class="info">DREAM SLOT</div>

<p></p>
<a href="http://www.laultimafarra.com" target="_new">www.laultimafarra.com</a><br>
<div class="info">LA ULTIMA FARRA.</div>

<p></p>
<a href="http://www.medirflash.com" target="_new">www.medirflash.com</a><br>
<div class="info">MEDIRFLASH medirflash@medirflash.com</div>

<p></p>
<a href="http://www.cap-cua.com/ info@cap-cua.com" target="_new">www.cap-cua.com/ info@cap-cua.com</a><br>
<div class="info">ARISARD</div>

<p></p>
<a href="http://www.sihose.com" target="_new">www.sihose.com</a><br>
<div class="info">SI HO SÉ, EM CASO / SI LO SE, ME CASO</div>

<p></p>
<a href="http://www.standingazafatas.com" target="_new">www.standingazafatas.com</a><br>
<div class="info">STANDING AZAFATAS</div>

<p></p>
<a href="http://www.animatium.com info@animatium.com" target="_new">www.animatium.com info@animatium.com</a><br>
<div class="info">ANIMATIUM</div>

<p></p>
<div class="info">azafatas@royalclass.org<br>CSI ROYAL CLASS</div>

<p></p>
<div class="info">sports@merchanservis.com<br>SPORTSERVICE: 932 237 474/639 771 276.</div>

<p></p>
<div class="info">integral1@merchanservis.com<br>INTEGRALSERVICE: 932 237 474/659 467 762.</div>

<p></p>
<a href="http://www.azafatashosmark.com" target="_new">www.azafatashosmark.com</a><br>
<div class="info">Azafatas para ferias y congresos, convenciones, lanzamientos de productos,</div>

<p></p>
<a href="http://www.bc-carpas.com" target="_new">www.bc-carpas.com</a><br>
<div class="info">ALQUILER DE CARPAS BC - CARPAS</div>

<p></p>
<a href="http://www.confaldas.com" target="_new">www.confaldas.com</a><br>
<div class="info">CON FALDAS Y A LO LOCA</div>

<p></p>
<a href="http://www.barcelonadenoche.info" target="_new">www.barcelonadenoche.info</a><br>
<div class="info">BARCELONA DE NOCHE<br>Destinado exclusivamente para mayores de 18 años.</div>

<p></p>
<a href="http://www.dream-slot.com" target="_new">www.dream-slot.com</a><br>
<div class="info">DREAM SLOT</div>

<p></p>
<a href="http://www.sorpresasorpresa.com" target="_new">www.sorpresasorpresa.com</a><br>
<div class="info">SORPRESA SORPRESA</div>

<p></p>
<a href="http://www.elbarcodespedidas.com" target="_new">www.elbarcodespedidas.com</a><br>
<div class="info">EL BARCO DE LAS DESPEDIDAS S.L.<br>Destinado exclusivamente para mayores de 18 años. BARCELONA</div>

<p></p>
<a href="http://www.tacbcn.com" target="_new">www.tacbcn.com</a><br>
<div class="info">TALLER D´ACTES I CELEBRACIONS<br>Creación y producción de eventos y ceremonias.</div>

<p></p>
<a href="http://www.afrolatina.net" target="_new">www.afrolatina.net</a><br>
<div class="info">Haz bailar a tus invitados!! Salsa, samba, batucada.<br>Animación de fiestas latinas y brasileñas.</div>

<p></p>
<a href="http://www.atrapasomnis.com" target="_new">www.atrapasomnis.com</a><br>
<div class="info">Ofrecemos casas de colonias, salidas de un día, casas de turismo rural,<br>ATRAPASOMNIS</div>

<p></p>
<a href="http://www.brusicatering.com" target="_new">www.brusicatering.com</a><br>
<div class="info">BRUSI CATERING A MIDA Servicio de catering completo.</div>

<p></p>
<a href="http://www.bcnevents.es" target="_new">www.bcnevents.es</a><br>
<div class="info">Productora dedicada al diseño y realización de todo tipo de actos para empresas<br>BCN EVENTS</div>

<p></p>
<a href="http://www.despedidasbarcelona.com" target="_new">www.despedidasbarcelona.com</a><br>
<div class="info">DESPEDIDAS BARCELONA<br>Destinado exclusivamente para mayores de 18 años.</div>

<p></p>
<a href="http://www.elcangur.net" target="_new">www.elcangur.net</a><br>
<div class="info">EL CANGUR<br>Servicio de canguros, clases de repaso y animaciones para cumpleaños.</div>

<p></p>
<a href="http://www.camaraoculta.es" target="_new">www.camaraoculta.es</a><br>
<div class="info">CÁMARA OCULTA</div>

<p></p>
<a href="http://www.cateringsabora.com" target="_new">www.cateringsabora.com</a><br>
<div class="info">CATERING SABORA Su operador de restauración.</div>

<p></p>
<a href="http://www.cenaloca.com" target="_new">www.cenaloca.com</a><br>
<div class="info">CENA LOCA Las mejores fiestas.</div>

<p></p>
<a href="http://www.cateringsabora.com" target="_new">www.cateringsabora.com</a><br>
<div class="info">CATERING SABORA</div>

<p></p>
<a href="http://www.paradoxeclipse.com" target="_new">www.paradoxeclipse.com</a><br>
<div class="info">PARADOX & ECLIPSE Organización de fiestas.</div>

<p></p>
<a href="http://www.elfrutoprohibido.com" target="_new">www.elfrutoprohibido.com</a><br>
<div class="info">EL FRUTO PROHIBIDO Despedidas de soltero/a.</div>

<p></p>
<a href="http://www.mitals.com" target="_new">www.mitals.com</a><br>
<div class="info">MITA'LS S.C.P.<br>Ferias y congresos: organización.</div>

<p></p>
<a href="http://www.grupa18.com" target="_new">www.grupa18.com</a><br>
<div class="info">GUATEQUE</div>

<p></p>
<a href="http://www.elgrupdelalegria.com" target="_new">www.elgrupdelalegria.com</a><br>
<div class="info">EL GRUP DE L'ALEGRIA</div>

<p></p>
<a href="http://www.festamusic.com" target="_new">www.festamusic.com</a><br>
<div class="info">FESTAMUSIC</div>

<p></p>
<a href="http://www.cienciadivertida.com" target="_new">www.cienciadivertida.com</a><br>
<div class="info">Organización de fiesta infantil.</div>

<p></p>
<a href="http://www.servhos.com" target="_new">www.servhos.com</a><br>
<div class="info">Catering.</div>

<p></p>
<a href="http://www.mestumacat. com" target="_new">www.mestumacat. com</a><br>
<div class="info">Organización de fiestas.</div>

<p></p>
<a href="http://www.gaac.info" target="_new">www.gaac.info</a><br>
<div class="info">GESTIÓ I ASSESSERORAMENT D'ACTES CULTURALS S.L.<br>Organización de fiestas y eventos.</div>

<p></p>
<div class="info">cococatering@terra.es<br>Servicio de catering.</div>

<p></p>
<a href="http://www.celebrem-ho.com" target="_new">www.celebrem-ho.com</a><br>
<div class="info">Fiestas y eventos: organización.</div>

<p></p>
<a href="http://www.animacions.es.vg" target="_new">www.animacions.es.vg</a><br>
<div class="info">en menos de 48 horas tendrás tu propia cuenta de correo E-Mail.</div>

<p></p>
<a href="http://www.eldia-d.com" target="_new">www.eldia-d.com</a><br>
<div class="info">FIESTAS</div>

<p></p>
<a href="http://www.giramon.net" target="_new">www.giramon.net</a><br>
<div class="info">FIESTAS</div>

<p></p>
<a href="http://www.tacbcn.com" target="_new">www.tacbcn.com</a><br>
<div class="info">FIESTAS</div>

<p></p>
<a href="http://www.miltonconvencional.com" target="_new">www.miltonconvencional.com</a><br>
<div class="info">MILTON CONVENCION</div>

<p></p>
<a href="http://www.circguiocrac.com" target="_new">www.circguiocrac.com</a><br>
<div class="info">CIRC CRAC</div>

<p></p>
<a href="http://www.hpc.es" target="_new">www.hpc.es</a><br>
<div class="info">HPC IBERICA S.A.</div>

<p></p>
<a href="http://www.canberardo.com" target="_new">www.canberardo.com</a><br>
<div class="info">SALONES DE BODA Y CELEBRACIONES .</div>

<p></p>
<div class="info">mide@mide.es<br>DECORACION Y MONTAJE DE STANDS .</div>

<p></p>
<a href="http://www.alquimiaproduccions.com" target="_new">www.alquimiaproduccions.com</a><br>
<div class="info">ALQUIMIA PRODUCCIONS S.A.</div>

<p></p>
<div class="info">adifolk@retemail.com<br>FIESTAS</div>

<p></p>
<div class="info">autocares@molist.com<br>AUTOCARES: SERVICIOS Y ALQUILER .</div>

<p></p>
<a href="http://www.geronagrup.com" target="_new">www.geronagrup.com</a><br>
<div class="info">GERONA GRUP</div>

<p></p>
<a href="http://www.cruillaespectacles.com" target="_new">www.cruillaespectacles.com</a><br>
<div class="info">CRUILLA D'ESPACTACLES BUSTAMANTE S.CV.</div>

<p></p>
<div class="info">quipeochenta@quipeochenta.com<br>QUIPE OCHENTA S.L.</div>

<p></p>
<a href="http://www.showlince.net" target="_new">www.showlince.net</a><br>
<div class="info">SHOW LINCE PRODUCCIONS S.L.</div>

<p></p>
<a href="http://www.medis.es" target="_new">www.medis.es</a><br>
<div class="info">MEDIS ORGANITZACIO D'ACTES</div>

<p></p>

<p></p>
<a href="http://www.florida-park.com" target="_new">www.florida-park.com</a><br>
<div class="info">SALONES DE BODA Y CELEBRACIONES .</div>

<p></p>
<a href="http://www.happyparc.com" target="_new">www.happyparc.com</a><br>
<div class="info">GUARDERIAS INFANTILES .</div>

<p></p>
<a href="http://www.chiquipark.es" target="_new">www.chiquipark.es</a><br>
<div class="info">JUEGOS INFANTILES: CENTROS .www.chiquipark.es</div>

<p></p>
<a href="http://www.masiasegarrulls.com" target="_new">www.masiasegarrulls.com</a><br>
<div class="info">SALONES DE BODA Y CELEBRACIONES .</div>

<p></p>
<a href="http://www.nightsungroup.com" target="_new">www.nightsungroup.com</a><br>
<div class="info">ESPECTACULOS: AGENCIAS .</div>

<p></p>
<a href="http://www.partyshow.com" target="_new">www.partyshow.com</a><br>
<div class="info">PARTY SHOW</div>

<p></p>
<a href="http://www.usuarios.lycos.es/rialles" target="_new">www.usuarios.lycos.es/rialles</a><br>
<div class="info">PALLASOS GERMANS COLIFLOR</div>

<p></p>
<a href="http://www.masiajulia.com" target="_new">www.masiajulia.com</a><br>
<div class="info">MASIA JULIA</div>

<p></p>
<a href="http://www.lalloca.com" target="_new">www.lalloca.com</a><br>
<div class="info">CA LA MINA</div>

<p></p>
<div class="info">mobilparc@hotmail.com<br>FESTES INFANTILS MOBILPARC S.L</div>

<p></p>
<a href="http://www.afizonia.com" target="_new">www.afizonia.com</a><br>
<div class="info">AFIZONIA</div>

<p></p>
<a href="http://www.carpediem.es" target="_new">www.carpediem.es</a><br>
<div class="info">LA DIMENSIO DESCONEGUDA S.L</div>

<p></p>
<a href="http://www.la-carpa.com" target="_new">www.la-carpa.com</a><br>
<div class="info">LA CARPA</div>

<p></p>
<div class="info">fontpineda@troc.es<br>EL JARDI DE FONTPINEDA</div>

<p></p>
<a href="http://www.sorpresasorpresa.com" target="_new">www.sorpresasorpresa.com</a><br>
<div class="info">LA BOMBONERA ESPECTACLES</div>

<p></p>
<div class="info">elcangur@yahoo.es<br>EL CANGUR S.CV.P.</div>

<p></p>
<a href="http://www.lafontanadeleixample.com" target="_new">www.lafontanadeleixample.com</a><br>
<div class="info">LA FONTANA DE EIXAMPLE</div>

<p></p>
<a href="http://www.vadaventura.com" target="_new">www.vadaventura.com</a><br>
<div class="info">VAD AVENTURA</div>

<p></p>
<div class="info">jungle-parks@jungle-parks.net<br>JUNGLES PARKS S.C.P.</div>

<p></p>
<div class="info">hanabigrup@terra.es<br>EL FRUTO PROHIBIDO</div>

<p></p>
<a href="http://www.lagranmovida.com" target="_new">www.lagranmovida.com</a><br>
<div class="info">LA GRAN MOVIDA</div>

<p></p>
<a href="http://www.festalafesta.com" target="_new">www.festalafesta.com</a><br>
<div class="info">FESTA LA FESTA.COM</div>

<p></p>
<a href="http://www.medirflash.com" target="_new">www.medirflash.com</a><br>
<div class="info">MEDIR MUJAL BOSCH</div>

<p></p>
<a href="http://www.dawakun.com" target="_new">www.dawakun.com</a><br>
<div class="info">DAWAKUN</div>

<p></p>
<a href="http://www.centraldelespectaculo.com" target="_new">www.centraldelespectaculo.com</a><br>
<div class="info">LA CENTRAL DEL ESPECTACULO</div>

<p></p>
<a href="http://www.lozano_ar.hotmail.com" target="_new">www.lozano_ar.hotmail.com</a><br>
<div class="info">XERINOLA S.L</div>

<p></p>
<a href="http://www.desfasate.com" target="_new">www.desfasate.com</a><br>
<div class="info">CULTOUR MUSIC</div>

<p></p>
<a href="http://www.tralia.com/peixosparc" target="_new">www.tralia.com/peixosparc</a><br>
<div class="info">PEIXOS PARC S.L.</div>

<p></p>
<div class="info">festamania@telefonica.net<br>FESTAMANIA 2001 S.L.</div>

<p></p>
<a href="http://www.fiestom.com" target="_new">www.fiestom.com</a><br>
<div class="info">TAM TAM FIESTOM</div>

<p></p>
<a href="http://www.beachsoccer.com" target="_new">www.beachsoccer.com</a><br>
<div class="info">PRO BEACH SOCCER S.L</div>

<p></p>
<div class="info">arubies@infonegocio.com<br>FIESTAS RUBIES</div>

<p></p>
<a href="http://www.moninfant.com" target="_new">www.moninfant.com</a><br>
<div class="info">MONINFANT</div>

<p></p>
<div class="info">infoludoteca@yahoo.es<br>PAM I PIPA S.L.</div>

<p></p>
<a href="http://www.closos.com" target="_new">www.closos.com</a><br>
<div class="info">LUDOTACA ELS CLOSOS</div>

<p></p>
<a href="http://www.masdesanllei.com" target="_new">www.masdesanllei.com</a><br>
<div class="info">MAS DE SANT LLEI</div>

<p></p>
<a href="http://www.stepbcn.com" target="_new">www.stepbcn.com</a><br>
<div class="info">STEP</div>

<p></p>
<a href="http://www.atopetioa.com" target="_new">www.atopetioa.com</a><br>
<div class="info">A TOPE TI@</div>

<p></p>
<a href="http://www.montetelobien.com" target="_new">www.montetelobien.com</a><br>
<div class="info">PROPOS EVENTOS SOCIALES S. L.</div>

<p></p>
<a href="http://www.ectunetes.com" target="_new">www.ectunetes.com</a><br>
<div class="info">PARC INFANTIL DE LA LLUNA</div>

<p></p>
<a href="http://www.granvia2.com" target="_new">www.granvia2.com</a><br>
<div class="info">GRAN VÍA 2</div>

<p></p>
<a href="http://www.mercasa.es" target="_new">www.mercasa.es</a><br>
<div class="info">OLYMPIC MOLL S.A.</div>

<p></p>
<div class="info">fgcomgest@telefonica.net<br>COMERCIALIZACION Y GESTION DE CENTROS COMERCIALES Y OCIO S.L</div>

<p></p>
<a href="http://www.granvia2.com" target="_new">www.granvia2.com</a><br>
<div class="info">ASOCIACION DE COMERCIANTES DEL CENTRO COMERCIAL GRAN VIA 2</div>

<p></p>
<div class="info">mfenech@inmocolonial.com<br>PEDRALBES CENTRE</div>

<p></p>
<a href="http://www.capraboacasa.com" target="_new">www.capraboacasa.com</a><br>
<div class="info">CENTRO COMERCIAL CAPRABO SANT FELIU</div>

<p></p>
<a href="http://www.modashopping.com" target="_new">www.modashopping.com</a><br>
<div class="info">MODA SHOPPING PORT OLIMPIC</div>

<p></p>
<a href="http://www.alcampo.es" target="_new">www.alcampo.es</a><br>
<div class="info">ALCAMPO SANT BOI</div>

<p></p>
<a href="http://www.alcampo.es" target="_new">www.alcampo.es</a><br>
<div class="info">ALCAMPO SANT ADRIA</div>

<p></p>
<a href="http://www.alcampo.es" target="_new">www.alcampo.es</a><br>
<div class="info">ALCAMPO SANT QUIRZE</div>

<p></p>
<a href="http://www.paddockbulevard.com" target="_new">www.paddockbulevard.com</a><br>
<div class="info">PADDOCK - BULEVARD</div>

<p></p>
<a href="http://www.maremagnum.es" target="_new">www.maremagnum.es</a><br>
<div class="info">MAREMAGNUM</div>

<p></p>
<a href="http://www.elcentredelavila.com" target="_new">www.elcentredelavila.com</a><br>
<div class="info">EL CENTRE DE LA VILA</div>

<p></p>
<a href="http://www.bulevardrosa.com" target="_new">www.bulevardrosa.com</a><br>
<div class="info">BULEVARD ROSA</div>

<p></p>
<a href="http://www.baricentro.es" target="_new">www.baricentro.es</a><br>
<div class="info">BARICENTRO</div>

<p></p>
<div class="info">mercatsfamilia@mercatsbcn.com<br>MERCAT SAGRADA FAMILIA</div>

<p></p>
<a href="http://www.laguiademataro.com/mataroparc" target="_new">www.laguiademataro.com/mataroparc</a><br>
<div class="info">MATARO PARC</div>

<p></p>
<a href="http://www.santcugatcentre.com" target="_new">www.santcugatcentre.com</a><br>
<div class="info">CENTRO COMERCIAL SANT CUGAT</div>

<p></p>
<a href="http://www.lesglories.com" target="_new">www.lesglories.com</a><br>
<div class="info">GLORIES</div>

<p></p>
<a href="http://www.larocavillage.com" target="_new">www.larocavillage.com</a><br>
<div class="info">LA ROCA VILLAGE</div>

<p></p>
<a href="http://www.centrolafarga.com" target="_new">www.centrolafarga.com</a><br>
<div class="info">LA FARGA</div>

<p></p>
<div class="info">montserrat_centre@telefonica.net<br>MONTSERRAT CENTRE ABRERA</div>

<p></p>
<a href="http://www.barnasud.com" target="_new">www.barnasud.com</a><br>
<div class="info">CENTRO COMERCIAL BARNASUD</div>

<p></p>
<a href="http://www.lilla.com" target="_new">www.lilla.com</a><br>
<div class="info">L'ILLA DIAGONAL</div>

<p></p>
<div class="info">blau@blaucentre.es<br>BLAU CENTRE DE LA LLAR</div>

<p></p>
<a href="http://www.lamaquinista.com" target="_new">www.lamaquinista.com</a><br>
<div class="info">LA MAQUINISTA</div>

<p></p>
<a href="http://www.heroncitybarcelona.com" target="_new">www.heroncitybarcelona.com</a><br>
<div class="info">HERON CITY BARCELONA</div>

<p></p>
<a href="http://www.parcvalles.com" target="_new">www.parcvalles.com</a><br>
<div class="info">PARC VALLES</div>

<p></p>
<div class="info">info@parcvalles.com<br>PARQUES COMERCIALES .</div>

<p></p>
<a href="http://www.granvia2.com" target="_new">www.granvia2.com</a><br>
<div class="info">GRAN VIA 2</div>

<p></p>
<a href="http://www.matineegroup.com" target="_new">www.matineegroup.com</a><br>
<div class="info">Café Olé</div>

<p></p>
<a href="http://www.cdlcbarcelona.com/v4/index.htm" target="_new">www.cdlcbarcelona.com/v4/index.htm</a><br>
<div class="info">Carpe Diem Lounge Club</div>

<p></p>
<a href="http://www.clubcatwalk.net" target="_new">www.clubcatwalk.net</a><br>
<div class="info">Catwalk</div>

<p></p>
<a href="http://www.grupo-ottozutz.com" target="_new">www.grupo-ottozutz.com</a><br>
<div class="info">City Hall</div>

<p></p>
<a href="http://www.fritz-group.info" target="_new">www.fritz-group.info</a><br>
<div class="info">Club Supreme</div>

<p></p>
<a href="http://www.danzarama.com" target="_new">www.danzarama.com</a><br>
<div class="info">Danzarama</div>

<p></p>
<a href="http://www.group-azo.com" target="_new">www.group-azo.com</a><br>
<div class="info">Danzatoria Tibidabo</div>

<p></p>
<a href="http://www.drugstorebcn.com" target="_new">www.drugstorebcn.com</a><br>
<div class="info">Drugstore Club</div>

<p></p>
<a href="http://www.gaydaybcn.com" target="_new">www.gaydaybcn.com</a><br>
<div class="info">Gay Day</div>

<p></p>
<a href="http://www.masimas.com/INTRO /default.htm" target="_new">www.masimas.com/INTRO /default.htm</a><br>
<div class="info">Jamboree</div>

<p></p>
<a href="http://www.matineegroup.com" target="_new">www.matineegroup.com</a><br>
<div class="info">La Madame</div>

<p></p>
<a href="http://www.maumaunderground.com" target="_new">www.maumaunderground.com</a><br>
<div class="info">MauMau Underground</div>

<p></p>
<a href="http://www.nextownladys.com" target="_new">www.nextownladys.com</a><br>
<div class="info">Nextownladys</div>

<p></p>
<a href="http://www.grupo-ottozutz.com/ottozutz" target="_new">www.grupo-ottozutz.com/ottozutz</a><br>
<div class="info">Otto Zutz</div>

<p></p>
<a href="http://www.clubpachabcn.com" target="_new">www.clubpachabcn.com</a><br>
<div class="info">Pacha</div>

<p></p>
<a href="http://www.gruposalsitas.com" target="_new">www.gruposalsitas.com</a><br>
<div class="info">>Salsitas</div>

<p></p>
<a href="http://www.matineegroup.com" target="_new">www.matineegroup.com</a><br>
<div class="info">Salvation</div>

<p></p>
<a href="http://www.shoko.biz" target="_new">www.shoko.biz</a><br>
<div class="info">SHOKO</div>

<p></p>
<a href="http://www.spacebarcelona.com" target="_new">www.spacebarcelona.com</a><br>
<div class="info">Space Barcelona</div>

<p></p>
<a href="http://www.sugarclub-barcelona.com" target="_new">www.sugarclub-barcelona.com</a><br>
<div class="info">Sugarclub</div>

<p></p>
<a href="http://www.sundownbcn.com" target="_new">www.sundownbcn.com</a><br>
<div class="info">Sundown</div>

<p></p>
<a href="http://www.dosquatredos.com" target="_new">www.dosquatredos.com</a><br>
<div class="info">Zona:</div>

<p></p>
<a href="http://www.arenadisco.com" target="_new">www.arenadisco.com</a><br>
<div class="info">Aire (Sala Diana)</div>

<p></p>
<a href="http://www.arenadisco.com" target="_new">www.arenadisco.com</a><br>
<div class="info">Arena Classic</div>

<p></p>
<a href="http://www.arenadisco.com" target="_new">www.arenadisco.com</a><br>
<div class="info">Arena Madre</div>

<p></p>
<a href="http://www.arenadisco.com" target="_new">www.arenadisco.com</a><br>
<div class="info">Arena Sala Dandy</div>

<p></p>
<a href="http://www.arenadisco.com" target="_new">www.arenadisco.com</a><br>
<div class="info">Arena VIP</div>

<p></p>
<a href="http://www.bearfactorybarcelona.com/indexpost.htm" target="_new">www.bearfactorybarcelona.com/indexpost.htm</a><br>
<div class="info">Bear Factory</div>

<p></p>
<a href="http://www.bel-luna.com" target="_new">www.bel-luna.com</a><br>
<div class="info">Bel Luna</div>

<p></p>
<a href="http://www.bikinibcn.com/index.ysi" target="_new">www.bikinibcn.com/index.ysi</a><br>
<div class="info">Bikini</div>

<p></p>
<a href="http://www.club13bcn.com" target="_new">www.club13bcn.com</a><br>
<div class="info">Club 13</div>

<p></p>
<a href="http://www.clubfellini.com" target="_new">www.clubfellini.com</a><br>
<div class="info">Club Fellini</div>

<p></p>
<a href="http://www.bcn-nightlife.com/es/clubs/www.d-blanco.com" target="_new">www.bcn-nightlife.com/es/clubs/www.d-blanco.com</a><br>
<div class="info">d-blanco</div>

<p></p>
<a href="http://www.grupodejavu.com" target="_new">www.grupodejavu.com</a><br>
<div class="info">Dejavu Club & Spirit & GO!</div>

<p></p>
<a href="http://www.helice.info/discotheque" target="_new">www.helice.info/discotheque</a><br>
<div class="info">Discotheque</div>

<p></p>
<a href="http://www.distritodiagonal.com" target="_new">www.distritodiagonal.com</a><br>
<div class="info">Distrito Diagonal</div>

<p></p>
<a href="http://www.dotlightclub.com" target="_new">www.dotlightclub.com</a><br>
<div class="info">Dot light club</div>

<p></p>
<a href="http://www.gruposalsitas.com" target="_new">www.gruposalsitas.com</a><br>
<div class="info">El Venezia</div>

<p></p>
<a href="http://www.elephantbcn.com" target="_new">www.elephantbcn.com</a><br>
<div class="info">Elephant</div>

<p></p>
<div class="info">bluntinstruments@menta.net<br>Estate</div>

<p></p>
<a href="http://www.fonfone.com" target="_new">www.fonfone.com</a><br>
<div class="info">Fonfone</div>

<p></p>
<div class="info">httpp://www.fuxialounge.com/<br>Fuxia Lounge</div>

<p></p>
<a href="http://www.bovedagroup.com" target="_new">www.bovedagroup.com</a><br>
<div class="info">Japan</div>

<p></p>
<a href="http://www.tallerdemusics.com/web/index.htm" target="_new">www.tallerdemusics.com/web/index.htm</a><br>
<div class="info">Jazz Si Club</div>

<p></p>
<a href="http://www.kche.net" target="_new">www.kche.net</a><br>
<div class="info">Kche</div>

<p></p>
<a href="http://www.masimas.com/INTRO /default.htm" target="_new">www.masimas.com/INTRO /default.htm</a><br>
<div class="info">La Cova del Drac - Jazzroom</div>

<p></p>
<a href="http://www.masimas.com/INTRO/default.htm" target="_new">www.masimas.com/INTRO/default.htm</a><br>
<div class="info">La Boite</div>

<p></p>
<a href="http://www.laterrrazza.com" target="_new">www.laterrrazza.com</a><br>
<div class="info">La Terrrazza</div>

<p></p>
<a href="http://www.grupo-ottozutz.com/lekasbah" target="_new">www.grupo-ottozutz.com/lekasbah</a><br>
<div class="info">Lekasbah</div>

<p></p>
<a href="http://www.elcel.net" target="_new">www.elcel.net</a><br>
<div class="info">Les Carpes del Cel</div>

<p></p>
<a href="http://www.luzdegas.com" target="_new">www.luzdegas.com</a><br>
<div class="info">Luz de Gas</div>

<p></p>
<a href="http://www.luzdegas.com" target="_new">www.luzdegas.com</a><br>
<div class="info">Luz de Gas Port Vell</div>

<p></p>
<a href="http://www.luzdegas.com" target="_new">www.luzdegas.com</a><br>
<div class="info">Luz de Gas Sala B</div>

<p></p>
<a href="http://www.magic-club.net" target="_new">www.magic-club.net</a><br>
<div class="info">Magic Rock Barcelona</div>

<p></p>
<a href="http://www.mephistobcn.com" target="_new">www.mephistobcn.com</a><br>
<div class="info">Mephisto</div>

<p></p>
<a href="http://www.bcn-nightlife.com/es/clubs/www.madness-group.com" target="_new">www.bcn-nightlife.com/es/clubs/www.madness-group.com</a><br>
<div class="info">Merci</div>

<p></p>
<a href="http://www.metrodiscobcn.com/main.php" target="_new">www.metrodiscobcn.com/main.php</a><br>
<div class="info">Metro</div>

<p></p>
<div class="info">betterdaysbcn@yahoo.com<br>New York</div>

<p></p>
<a href="http://www.nitsa.com" target="_new">www.nitsa.com</a><br>
<div class="info">Nitsa Club - Sala Apolo</div>

<p></p>
<a href="http://www.hotelomm.es" target="_new">www.hotelomm.es</a><br>
<div class="info">OmmSesion Club</div>

<p></p>
<div class="info">uzi_essencial@hotmail.com<br>Plataforma</div>

<p></p>
<a href="http://www.salarazzmatazz.com" target="_new">www.salarazzmatazz.com</a><br>
<div class="info">Pop Bar</div>

<p></p>
<a href="http://www.salarazzmatazz.com" target="_new">www.salarazzmatazz.com</a><br>
<div class="info">Razz Club</div>

<p></p>
<a href="http://www.salarazzmatazz.com" target="_new">www.salarazzmatazz.com</a><br>
<div class="info">Razzmatazz (Sala)</div>

<p></p>
<a href="http://www.sala-apolo.com" target="_new">www.sala-apolo.com</a><br>
<div class="info">Sala Apolo</div>

<p></p>
<a href="http://www.saladefiestastango.com" target="_new">www.saladefiestastango.com</a><br>
<div class="info">Sala de fiestas Tango</div>

<p></p>
<a href="http://www.shotwell59.com" target="_new">www.shotwell59.com</a><br>
<div class="info">Shotwell 59</div>

<p></p>
<a href="http://www.sidecarfactoryclub.com" target="_new">www.sidecarfactoryclub.com</a><br>
<div class="info">Sidecar</div>

<p></p>
<a href="http://www.sm55.com" target="_new">www.sm55.com</a><br>
<div class="info">SM 55</div>

<p></p>
<a href="http://www.grupo-sol.net" target="_new">www.grupo-sol.net</a><br>
<div class="info">Sol ClubSol Club</div>

<p></p>
<a href="http://www.matineegroup.com" target="_new">www.matineegroup.com</a><br>
<div class="info">Souvenir</div>

<p></p>
<a href="http://www.suttonmusicclub.com" target="_new">www.suttonmusicclub.com</a><br>
<div class="info">Sutton Music Club (The Club)</div>

<p></p>
<a href="http://www.bitch-club.com" target="_new">www.bitch-club.com</a><br>
<div class="info">The Bitch Club</div>

<p></p>
<a href="http://www.salarazzmatazz.com" target="_new">www.salarazzmatazz.com</a><br>
<div class="info">The Loft</div>

<p></p>
<a href="http://www.grupocostaeste.com" target="_new">www.grupocostaeste.com</a><br>
<div class="info">Universal Lounge Club</div>

<p></p>
<a href="http://www.versusbcn.com" target="_new">www.versusbcn.com</a><br>
<div class="info">Versus</div>

<p></p>
<a href="http://www.villagebarcelona.com" target="_new">www.villagebarcelona.com</a><br>
<div class="info">Village Barcelona</div>

<p></p>
<a href="http://www.zentraus.com/info@zentraus.com" target="_new">www.zentraus.com/info@zentraus.com</a><br>
<div class="info">Zentraus</div>

<p></p>
<a href="http://www.labolsabar.com" target="_new">www.labolsabar.com</a><br>
<div class="info">La Bolsa</div>

<p></p>
<a href="http://www.fritz-group.info" target="_new">www.fritz-group.info</a><br>
<div class="info">Lincoln 19</div>

<p></p>
<a href="http://www.porquesi.com" target="_new">www.porquesi.com</a><br>
<div class="info">Porquesi</div>

<p></p>
<a href="http://www.baramsterdam.com" target="_new">www.baramsterdam.com</a><br>
<div class="info">Bar Amsterdam</div>

<p></p>
<a href="http://www.ritablue.com" target="_new">www.ritablue.com</a><br>
<div class="info">Rita Blue</div>

<p></p>
<a href="http://www.smooth-bcn.com" target="_new">www.smooth-bcn.com</a><br>
<div class="info">Smooth</div>

<p></p>
<a href="http://www.pubyfiesta.com" target="_new">www.pubyfiesta.com</a><br>
<div class="info">Ummagumma</div>

<p></p>
<div class="info">francisco@ebik.com<br>XAPAKO</div>

<p></p>
<div class="info">jamesterry147@yahoo.com<br>London Bar S.L.</div>

<p></p>
<a href="http://www.budarestaurante.com" target="_new">www.budarestaurante.com</a><br>
<div class="info">Budabarcelona</div>

<p></p>
<a href="http://www.masimas.com/INTRO/default.htm" target="_new">www.masimas.com/INTRO/default.htm</a><br>
<div class="info">Mas i Mas</div>

<p></p>
<a href="http://www.overtheclub.com" target="_new">www.overtheclub.com</a><br>
<div class="info">Over the Club</div>

<p></p>
<a href="http://www.plastic-bcn.com" target="_new">www.plastic-bcn.com</a><br>
<div class="info">Plastic Club</div>

<p></p>
<a href="http://www.princesa23.com.es" target="_new">www.princesa23.com.es</a><br>
<div class="info">Princesa 23</div>

<p></p>
<div class="info">jamesterry147@yahoo.com<br>London Bar S.L.</div>

<p></p>
<a href="http://www.elbadlands.com" target="_new">www.elbadlands.com</a><br>
<div class="info">Badlands</div>

<p></p>
<a href="http://www.b4hours.com" target="_new">www.b4hours.com</a><br>
<div class="info">B4hours</div>

<p></p>
<a href="http://www.grupodejavu.com" target="_new">www.grupodejavu.com</a><br>
<div class="info">Be Good</div>

<p></p>
<a href="http://www.overtheclub.com" target="_new">www.overtheclub.com</a><br>
<div class="info">Over the Club</div>

<p></p>
<a href="http://www.newscafe-bcn.com" target="_new">www.newscafe-bcn.com</a><br>
<div class="info">News</div>

<p></p>
<a href="http://www.dostrece.net" target="_new">www.dostrece.net</a><br>
<div class="info">Dostrece</div>

<p></p>
<a href="http://www.bpipaclub.com" target="_new">www.bpipaclub.com</a><br>
<div class="info">Pipa Club Barcelona</div>

<p></p>
<div class="info">templebarbcn@telefonica.net<br>Temple Bar</div>

<p></p>
<a href="http://www.barceferino.net" target="_new">www.barceferino.net</a><br>
<div class="info">Bar Ceferino</div>

<p></p>
<a href="http://www.barceferino.net/coyote" target="_new">www.barceferino.net/coyote</a><br>
<div class="info">El Coyote</div>

<p></p>
<a href="http://www.hardrock.com" target="_new">www.hardrock.com</a><br>
<div class="info">Hardrock Cafe</div>

<p></p>
<a href="http://www.wawanco.net" target="_new">www.wawanco.net</a><br>
<div class="info">Wawanco Rock Club</div>

<p></p>
<a href="http://www.vivaldibar.com" target="_new">www.vivaldibar.com</a><br>
<div class="info">Vivaldi</div>

<p></p>
<a href="http://www.spiritual-cafe.org" target="_new">www.spiritual-cafe.org</a><br>
<div class="info">SPIRITUAL CAFE</div>

<p></p>
<a href="http://www.fantasticoclub.com" target="_new">www.fantasticoclub.com</a><br>
<div class="info">Fantastico</div>

<p></p>
<div class="info">barroc_cafe@telefonica.net<br>Barroc Cafe</div>

<p></p>
<a href="http://www.joliecosmonaute.com/ind_flash.htm" target="_new">www.joliecosmonaute.com/ind_flash.htm</a><br>
<div class="info">Jolie Cosmonaute</div>

<p></p>
<div class="info">luposbar@hotmail.com<br>LUPOS</div>

<p></p>
<a href="http://www.nakupenda.com" target="_new">www.nakupenda.com</a><br>
<div class="info">Nakupenda</div>

<p></p>
<a href="http://www.newscafe-bcn.com" target="_new">www.newscafe-bcn.com</a><br>
<div class="info">News</div>

<p></p>
<a href="http://www.porquesi.com" target="_new">www.porquesi.com</a><br>
<div class="info">Porquesi</div>

<p></p>
<a href="http://www.zeligbarcelona.com" target="_new">www.zeligbarcelona.com</a><br>
<div class="info">Zelig</div>

<p></p>
<a href="http://www.daf-restaurant.net" target="_new">www.daf-restaurant.net</a><br>
<div class="info">DAF LAB</div>

<p></p>
<a href="http://www.diobar.net" target="_new">www.diobar.net</a><br>
<div class="info">Diobar</div>

<p></p>
<a href="http://www.bariposa.com" target="_new">www.bariposa.com</a><br>
<div class="info">Iposa</div>

<p></p>
<div class="info">lafianna@hotmail.com<br>La Fianna</div>

<p></p>
<a href="http://www.puku-cafe.com" target="_new">www.puku-cafe.com</a><br>
<div class="info">Puku Café</div>

<p></p>
<a href="http://www.rubi-bcn.com" target="_new">www.rubi-bcn.com</a><br>
<div class="info">>Rubi</div>

<p></p>
<div class="info">foc@mindesign.nl<br>Tens Foc</div>

<p></p>
<a href="http://www.fantasticoclub.com/sound/Sound.htm" target="_new">www.fantasticoclub.com/sound/Sound.htm</a><br>
<div class="info">The Sound</div>

<p></p>
<a href="http://www.zeltas.net" target="_new">www.zeltas.net</a><br>
<div class="info">Zeltas</div>

<p></p>
<a href="http://www.apartamentoseuropa.com" target="_new">www.apartamentoseuropa.com</a><br>
<div class="info">APARTAMENTOS HOTEL EUROPA</div>

<p></p>
<a href="http://www.hotelgranducat.com" target="_new">www.hotelgranducat.com</a><br>
<div class="info">HOTEL GRAN DUCAT</div>

<p></p>
<a href="http://www.hcchotels.com" target="_new">www.hcchotels.com</a><br>
<div class="info">HOTEL ST. MORITZ</div>

<p></p>
<a href="http://www.apartahotelacces.com" target="_new">www.apartahotelacces.com</a><br>
<div class="info">ACCES</div>

<p></p>
<a href="http://www.guitarthotels.com" target="_new">www.guitarthotels.com</a><br>
<div class="info">GUITART GRAND PASSAGE</div>

<p></p>
<a href="http://www.sansihotels.com" target="_new">www.sansihotels.com</a><br>
<div class="info">SANSI DIPUTACIÓ</div>

<p></p>
<a href="http://www.accorhotels.com" target="_new">www.accorhotels.com</a><br>
<div class="info">IBIS MONTMELÓ GRANOLLERS</div>

<p></p>
<a href="http://www.reginahotel.com" target="_new">www.reginahotel.com</a><br>
<div class="info">HOTEL REGINA</div>

<p></p>
<a href="http://www.hostalpalacios.com" target="_new">www.hostalpalacios.com</a><br>
<a href="http://www.torrevermella.com" target="_new">www.torrevermella.com</a><br>

<p></p>
<a href="http://www.masiacalobac.com" target="_new">www.masiacalobac.com</a><br>
<div class="info">CAL OBAC</div>

<p></p>
<a href="http://www.nh-hotels.com" target="_new">www.nh-hotels.com</a><br>
<div class="info">NH MASTER</div>

<p></p>
<a href="http://www.termesvictoria.com" target="_new">www.termesvictoria.com</a><br>
<div class="info">TERMES VICTORIA</div>

<p></p>
<div class="info">hotelpdg@terra.es<br>HOTEL PASEO DE GRACIA</div>

<p></p>
<a href="http://www.hotelsonix.net" target="_new">www.hotelsonix.net</a><br>
<div class="info">HOTEL ONIX FIRA</div>

<p></p>
<a href="http://www.meridienbarcelona.com" target="_new">www.meridienbarcelona.com</a><br>
<div class="info">LE MERIDIEN BARCELONA</div>

<p></p>
<a href="http://www.hostalcolon.net" target="_new">www.hostalcolon.net</a><br>
<div class="info">HOSTAL COLON</div>

<p></p>
<a href="http://www.hostelcim.cjb.net" target="_new">www.hostelcim.cjb.net</a><br>
<div class="info">CATALAN</div>

<p></p>
<a href="http://www.center-ramblas.com" target="_new">www.center-ramblas.com</a><br>
<div class="info">CARRER</div>

<p></p>
<a href="http://www.hotelsansebastian.com" target="_new">www.hotelsansebastian.com</a><br>
<div class="info">SAN SEBASTIAN PLAYA</div>

<p></p>
<a href="http://www.nh-hotels.com" target="_new">www.nh-hotels.com</a><br>
<div class="info">NH NUMANCIA</div>

<p></p>
<a href="http://www.hotelguillermotell.com" target="_new">www.hotelguillermotell.com</a><br>
<div class="info">HOTEL GUILLERMO TELL</div>

<p></p>
<a href="http://www.bestwestern.es/mediterraneo.html" target="_new">www.bestwestern.es/mediterraneo.html</a><br>
<div class="info">MEDITERRANEO</div>

<p></p>
<a href="http://www.nh-hotels.com" target="_new">www.nh-hotels.com</a><br>
<div class="info">NH EXPRESS LA MAQUINISTA</div>

<p></p>
<a href="http://www.hotelamister.com" target="_new">www.hotelamister.com</a><br>
<div class="info">ÁMISTER HOTEL</div>

<p></p>
<a href="http://www.sitges.dolce.com" target="_new">www.sitges.dolce.com</a><br>
<div class="info">DOLCE SITGES</div>

<p></p>
<a href="http://www.hotelartsbarcelona.com" target="_new">www.hotelartsbarcelona.com</a><br>
<div class="info">HOTEL ARTS BARCELONA</div>

<p></p>
<a href="http://www.hotelargentona.com" target="_new">www.hotelargentona.com</a><br>
<div class="info">HOTEL VILA D'ARGENTONA</div>

<p></p>
<a href="http://www.hotelcelimar.com" target="_new">www.hotelcelimar.com</a><br>
<div class="info">HOTEL CELIMAR</div>

<p></p>
<a href="http://www.nh-hotels.com" target="_new">www.nh-hotels.com</a><br>
<div class="info">NH CALDERON</div>

<p></p>
<a href="http://www.hotelcalasanz.com" target="_new">www.hotelcalasanz.com</a><br>
<div class="info">HOTEL RESTAURANTE CALASANZ</div>

<p></p>
<a href="http://www.nh-hotels.com" target="_new">www.nh-hotels.com</a><br>
<div class="info">NH CORNELLA</div>

<p></p>
<a href="http://www.ibishotel.com" target="_new">www.ibishotel.com</a><br>
<div class="info">HOTEL IBIS BARCELONA MERIDIANA</div>

<p></p>
<a href="http://www.marfina.com" target="_new">www.marfina.com</a><br>
<div class="info">MARFINA</div>

<p></p>
<div class="info">hotelcoronado.bcn@wanadoo.es<br>CORONADO</div>

<p></p>
<a href="http://www.campingplayasol.com" target="_new">www.campingplayasol.com</a><br>
<div class="info">CAMPING PLAYASOL</div>

<p></p>
<a href="http://www.canpamplona.com" target="_new">www.canpamplona.com</a><br>
<div class="info">CAN PAMPLONA</div>

<p></p>
<a href="http://www.nh-hotels.com" target="_new">www.nh-hotels.com</a><br>
<div class="info">NH RALLYE</div>

<p></p>
<a href="http://www.nh-hotels.com" target="_new">www.nh-hotels.com</a><br>
<div class="info">NH CIUTAT DE MATARO</div>

<p></p>
<a href="http://www.goldenhotels.com" target="_new">www.goldenhotels.com</a><br>
<div class="info">HOTEL GOLDEN TAURUS PARK</div>

<p></p>
<a href="http://www.hotelturin.com" target="_new">www.hotelturin.com</a><br>
<div class="info">TURIN</div>

<p></p>
<a href="http://www.hoteliris.com" target="_new">www.hoteliris.com</a><br>
<div class="info">IRIS</div>

<p></p>
<div class="info">hostalmiramar@ya.com<br>HOSTAL MIRAMAR</div>

<p></p>
<a href="http://www.geminisitges.com" target="_new">www.geminisitges.com</a><br>
<div class="info">HOSTAL RESIDENCIA GÉMINI SITGES</div>

<p></p>
<a href="http://www.parksedo.com" target="_new">www.parksedo.com</a><br>
<div class="info">APARTAHOTEL PARK SEDO</div>

<p></p>
<a href="http://www.gataccommodation.com" target="_new">www.gataccommodation.com</a><br>

<p></p>
<a href="http://www.miramarhotel.net" target="_new">www.miramarhotel.net</a><br>
<div class="info">HOTEL MIRAMAR</div>

<p></p>
<a href="http://www.paretselspins.com" target="_new">www.paretselspins.com</a><br>
<div class="info">HOTEL PARETS ELS PINS S.A.</div>

<p></p>
<a href="http://www.hotelatlantis-bcn.com" target="_new">www.hotelatlantis-bcn.com</a><br>
<div class="info">ATLANTIS</div>

<p></p>
<a href="http://www.hotel-lleo.es" target="_new">www.hotel-lleo.es</a><br>
<div class="info">HOTEL LLEO</div>

<p></p>
<a href="http://www.hotelcondestable.com" target="_new">www.hotelcondestable.com</a><br>
<div class="info">HOTEL CONDESTABLE</div>

<p></p>
<a href="http://www.hotelgaudi.es" target="_new">www.hotelgaudi.es</a><br>
<div class="info">HOTEL GAUDI</div>

<p></p>
<div class="info">nhbelagua@nh-hotels.com<br>NH BELAGUA</div>

<p></p>
<a href="http://www.apartamentosmurmar.com" target="_new">www.apartamentosmurmar.com</a><br>
<div class="info">APARTAMENTOS MUR - MAR</div>

<p></p>
<a href="http://www.youthostel.com/castella/index.aspx?idioma=3" target="_new">www.youthostel.com/castella/index.aspx?idioma=3</a><br>
<div class="info">INTEGRAL RENT S.L.</div>

<p></p>
<a href="http://www.foraparc.com" target="_new">www.foraparc.com</a><br>
<div class="info">HOTEL FLORA PARC</div>

<p></p>
<div class="info">nhcorts@nh-hotels.com<br>NH LES CORTS</div>

<p></p>
<a href="http://www.hotelflorparks@ctv.es" target="_new">www.hotelflorparks@ctv.es</a><br>
<div class="info">FLOR PARKS</div>

<p></p>
<div class="info">nhpodium@nh-hotels.com<br>NH PODIUM</div>

<p></p>
<div class="info">nhsantangelo@nh-hotels.com<br>NH SANT ANGELO</div>

<p></p>
<a href="http://www.albergdeberga.com" target="_new">www.albergdeberga.com</a><br>
<div class="info">ALBERG DE BERGA S.L.</div>

<p></p>
<a href="http://www.elcastell.com" target="_new">www.elcastell.com</a><br>
<div class="info">HOTEL EL CASTELL DE SANT BOI</div>

<p></p>
<a href="http://www.hotelalfavalles.com" target="_new">www.hotelalfavalles.com</a><br>
<div class="info">AUGUSTA VALLES</div>

<p></p>
<div class="info">hoteles@bcnclassic.com<br>HOTEL BARCELONA CLASSIC</div>

<p></p>
<div class="info">nhcondor@nh-hotels.com<br>NH CONDOR</div>

<p></p>
<div class="info">exportabarcelona@nh-hotels.com<br>NH EXPRESS PORTA BARCELONA</div>

<p></p>
<a href="http://www.apartamentostavir.com" target="_new">www.apartamentostavir.com</a><br>
<div class="info">APARTAMENTS TAVIR TURISTIC</div>

<p></p>
<div class="info">nhducdelavictoria@nh-hotels.com<br>NH DUC DE LA VICTORIA</div>

<p></p>
<a href="http://www.hduquesadecardona.com" target="_new">www.hduquesadecardona.com</a><br>
<div class="info">DUQUESA DE CARDONA</div>

<p></p>
<a href="http://www.solifemar.com" target="_new">www.solifemar.com</a><br>
<div class="info">APARTAMENTOS SOLIFEMAR</div>

<p></p>
<div class="info">reservas@hotelcristalpalace.com<br>HOTEL CRISTAL PALACE</div>

<p></p>
<a href="http://www.hotelcelimarcentre.com" target="_new">www.hotelcelimarcentre.com</a><br>
<div class="info">HOTEL CELIMAR CENTRE</div>

<p></p>
<a href="http://www.ciutatdesantadria.com" target="_new">www.ciutatdesantadria.com</a><br>
<div class="info">CIUTAT DE SANT ADRIA</div>

<p></p>
<a href="http://www.canmateuet.com" target="_new">www.canmateuet.com</a><br>
<div class="info">ALBERG CAN MATEUET</div>

<p></p>
<a href="http://www.agroturisme.org/pareres.htm" target="_new">www.agroturisme.org/pareres.htm</a><br>
<div class="info">BCM HOUSES</div>

<p></p>
<a href="http://www.bcmhouses.com" target="_new">www.bcmhouses.com</a><br>
<div class="info">PASSATGE</div>

<p></p>
<a href="http://www.citadines.com" target="_new">www.citadines.com</a><br>
<div class="info">CITADINES BARCELONA RAMBLAS</div>

<p></p>
<a href="http://www.htophotels.com" target="_new">www.htophotels.com</a><br>
<div class="info">AMAIKA</div>

<p></p>
<a href="http://www.centrhotel.com" target="_new">www.centrhotel.com</a><br>
<div class="info">CENTROHOTEL</div>

<p></p>
<a href="http://www.abbahotels.com" target="_new">www.abbahotels.com</a><br>
<div class="info">ABBA SANTS</div>

<p></p>
<div class="info">edelwais@telefonica.net<br>EDELWEISS IBERICA</div>

<p></p>
<div class="info">josepsola@jet.es<br>CAMPING MASIA RIERA DE SIRUET</div>

<p></p>
<a href="http://www.domohotel.com" target="_new">www.domohotel.com</a><br>
<div class="info">DOMO</div>

<p></p>
<div class="info">info@hotelespanya-calella.com<br>HOTEL ESPANYA</div>

<p></p>
<a href="http://www.hotelneptuno.com" target="_new">www.hotelneptuno.com</a><br>
<div class="info">APARTHOTEL NEPTUNO</div>

<p></p>
<a href="http://www.hotelneptuno.com" target="_new">www.hotelneptuno.com</a><br>
<div class="info">HOTEL NEPTUNO</div>

<p></p>
<a href="http://www.terra.es/personal4/lespiadimonis" target="_new">www.terra.es/personal4/lespiadimonis</a><br>
<div class="info">L'ESPIADIMONIS</div>

<p></p>
<a href="http://www.terra.es/personal4/lespiadimonis" target="_new">www.terra.es/personal4/lespiadimonis</a><br>
<div class="info">LA CENSADA</div>

<p></p>
<a href="http://www.bcn.es" target="_new">www.bcn.es</a><br>
<div class="info">PORTA MAR</div>

<p></p>
<a href="http://www.minibalneario.com" target="_new">www.minibalneario.com</a><br>
<div class="info">EL MINI BALNEARIO DE CASTELLDEFELS</div>

<p></p>
<a href="http://www.cimhotels.com/robert" target="_new">www.cimhotels.com/robert</a><br>
<div class="info">ROBERT</div>

<p></p>
<a href="http://www.hotelceferino.com" target="_new">www.hotelceferino.com</a><br>
<div class="info">CEFERINO</div>

<p></p>
<div class="info">reservas@hostallevante.com<br>HOSTAL LEVANTE</div>

<p></p>
<a href="http://www.hotelterramar.es" target="_new">www.hotelterramar.es</a><br>
<div class="info">TERRAMAR</div>

<p></p>
<a href="http://www.sapunta.com" target="_new">www.sapunta.com</a><br>
<div class="info">APART HOTEL SAPUNTA DE S' ESTANYOL</div>

<p></p>
<a href="http://www.alimarahotel.com" target="_new">www.alimarahotel.com</a><br>
<div class="info">ALIMARA</div>

<p></p>
<a href="http://www.blauhousing.com" target="_new">www.blauhousing.com</a><br>
<div class="info">BLAU HOUSING</div>

<p></p>
<a href="http://www.hoteles-silken.com" target="_new">www.hoteles-silken.com</a><br>
<div class="info">HOTELES SILKEN S.A.</div>

<p></p>
<a href="http://www.hoteles-silken.com" target="_new">www.hoteles-silken.com</a><br>
<div class="info">HOTELES SILKEN S.A.</div>

<p></p>
<a href="http://www.gargallo-hotels.com" target="_new">www.gargallo-hotels.com</a><br>
<div class="info">GRAN HOTEL BARCINO</div>

<p></p>
<a href="http://www.hostalaustralia.com" target="_new">www.hostalaustralia.com</a><br>
<div class="info">JUAN MANUEL LORENZO RODRIGUEZ</div>

<p></p>
<a href="http://www.turismerural.com" target="_new">www.turismerural.com</a><br>
<div class="info">CAN GUILLA</div>

<p></p>
<div class="info">montemar-hotel@infonegocio.com<br>HOTEL MONTEMAR</div>

<p></p>
<a href="http://www.agroturisme.org/agroturisme/caljeron.htm" target="_new">www.agroturisme.org/agroturisme/caljeron.htm</a><br>
<div class="info">CAL JERONI</div>

<p></p>
<div class="info">p.eco.caldese@diba.es<br>BANYS TERMALS CALDES D'ESTRAC S.L.</div>

<p></p>
<div class="info">aiguadora@cempresarial.com<br>CAMPING IAGUA D'ORA</div>

<p></p>
<a href="http://www.arrahonahotel.com" target="_new">www.arrahonahotel.com</a><br>
<div class="info">ARRAHONA</div>

<p></p>
<a href="http://www.arrahonahotel.com" target="_new">www.arrahonahotel.com</a><br>
<div class="info">APARTAMENTOS ARRAHONA</div>

<p></p>
<a href="http://www.hotelcesar.net" target="_new">www.hotelcesar.net</a><br>
<div class="info">CESAR</div>

<p></p>
<a href="http://www.htophotel.com" target="_new">www.htophotel.com</a><br>
<div class="info">H TOP HOTELS</div>

<p></p>
<a href="http://www.mastrader.com" target="_new">www.mastrader.com</a><br>
<div class="info">LEZACA S.L.</div>

<p></p>
<a href="http://www.solmelia.com" target="_new">www.solmelia.com</a><br>
<div class="info">TRYP APOLO</div>

<p></p>
<div class="info">melia.barcelona@solmelia.com<br>MELIA BARCELONA</div>

<p></p>
<div class="info">tryp.barcelona.aeropuerto@solmelia.com<br>TRYP BARCELONA AEROPUERTO</div>

<p></p>
<a href="http://www.internetcasas.com" target="_new">www.internetcasas.com</a><br>
<div class="info">INTERNET CASAS</div>

<p></p>
<a href="http://www.medplaya.com" target="_new">www.medplaya.com</a><br>
<div class="info">SANTA MONICA</div>

<p></p>
<a href="http://www.barcelona-on-line.com" target="_new">www.barcelona-on-line.com</a><br>
<div class="info">BARCELONA ON LINE</div>

<p></p>
<a href="http://www.turisverd.com" target="_new">www.turisverd.com</a><br>
<div class="info">CAL FERNANDO</div>

<p></p>
<a href="http://www.hostalestrella.com}}" target="_new">www.hostalestrella.com}}</a><br>
<div class="info">HOSTAL ESTRELLA</div>

<p></p>
<div class="info">reservas@hotelbelairbarcelona.com<br>SUNHOTEL BEL-AIR</div>

<p></p>
<div class="info">sants@bchoteles.com<br>BARCELO HOTEL SANTS</div>

<p></p>
<a href="http://www.barcelo.com" target="_new">www.barcelo.com</a><br>
<div class="info">HOTEL BARCELO SANTS</div>

<p></p>
<div class="info">ateneamar@bchoteles.com<br>BARCELO H.ATENEA MAR</div>

<p></p>
<div class="info">maspalou@teleline.es<br>MAS PALOU</div>

<p></p>
<div class="info">info@hotelmadisonbahia.com<br>HOTEL MADISON BAHIA</div>

<p></p>
<div class="info">abalon@mediumhoteles.com<br>ABALON</div>

<p></p>
<div class="info">hotelesgestion@retemail.es<br>G.H. VACACIONES.</div>

<p></p>
<a href="http://www.gargallo-hotels.es" target="_new">www.gargallo-hotels.es</a><br>
<div class="info">HOTEL DEL MAR</div>

<p></p>
<a href="http://www.recpcion@ecohoteles.com" target="_new">www.recpcion@ecohoteles.com</a><br>
<div class="info">K2 HOTELERA S.L.</div>

<p></p>
<div class="info">romantic@arrakis.es<br>JOSEP MANUEL VENDRELL S.L.</div>

<p></p>
<div class="info">romantic@arrakis.es<br>ROMANTIC Y LA RENAIXENÇA</div>

<p></p>
<a href="http://www.barcelona-bookaflat.com" target="_new">www.barcelona-bookaflat.com</a><br>
<div class="info">PONTE SISTO S.L.</div>

<p></p>
<a href="http://www.elgarrafcomercia.com/dayspa" target="_new">www.elgarrafcomercia.com/dayspa</a><br>
<div class="info">DAY SPA M & G</div>

<p></p>
<div class="info">bahia@milisa.com<br>BAHIA</div>

<p></p>
<a href="http://www.hoteljbalmes.com" target="_new">www.hoteljbalmes.com</a><br>
<div class="info">J.BALMES VIC</div>

<p></p>
<a href="http://www.gargallo-hotels.es" target="_new">www.gargallo-hotels.es</a><br>
<div class="info">GARGALLO HOTELS</div>

<p></p>
<a href="http://www.hostalalogar.com" target="_new">www.hostalalogar.com</a><br>
<div class="info">HOSTAL ALOGAR</div>

<p></p>
<a href="http://www.city-hotels.es" target="_new">www.city-hotels.es</a><br>
<div class="info">APARTHOTEL CITY SENATOR</div>

<p></p>
<a href="http://www.habitatgejove.com" target="_new">www.habitatgejove.com</a><br>
<div class="info">HABITATGE JOVE</div>

<p></p>
<a href="http://www.gargallohotels.es" target="_new">www.gargallohotels.es</a><br>
<div class="info">HOTEL SANTA MARTA</div>

<p></p>
<div class="info">reserve@gargallo-hotels.com<br>GOTICO</div>

<p></p>
<div class="info">canbartomeu@hotmail.com<br>CASA BARTOMEU</div>

<p></p>
<a href="http://www.originalhotels.com" target="_new">www.originalhotels.com</a><br>
<div class="info">NERI H&R</div>

<p></p>
<a href="http://www.antemare.com" target="_new">www.antemare.com</a><br>
<div class="info">ANTEMARE NOVA DIMENSIO</div>

<p></p>
<a href="http://www.bcnalberg.com" target="_new">www.bcnalberg.com</a><br>
<div class="info">ALBERGUE JUVENTUD NEW YORK</div>

<p></p>
<a href="http://www.apartamentoseuropa.com" target="_new">www.apartamentoseuropa.com</a><br>
<div class="info">APARTAMENTOS HOTEL EUROPA</div>

<p></p>
<a href="http://www.hotelgranducat.com" target="_new">www.hotelgranducat.com</a><br>
<div class="info">HOTEL GRAN DUCAT</div>

<p></p>
<div class="info">stmoritz@hcchotels.com<br>HOTEL ST. MORITZ</div>

<p></p>
<a href="http://www.apartahotelacces.com" target="_new">www.apartahotelacces.com</a><br>
<div class="info">ACCES</div>

<p></p>
<div class="info">rggp@guitarthotels.com<br>GUITART GRAND PASSAGE</div>

<p></p>
<div class="info">diputacio@sansihotels.com<br>SANSI DIPUTACIÓ</div>

<p></p>
<a href="http://www.accorhotels.com" target="_new">www.accorhotels.com</a><br>
<div class="info">IBIS MONTMELÓ GRANOLLERS</div>

<p></p>
<a href="http://www.reginahotel.com" target="_new">www.reginahotel.com</a><br>
<div class="info">HOTEL REGINA</div>

<p></p>
<a href="http://www.torrevermella.com" target="_new">www.torrevermella.com</a><br>
<div class="info">TORRE VERMELLA</div>

<p></p>
<a href="http://www.hostalpalacios.com" target="_new">www.hostalpalacios.com</a><br>
<div class="info">HOSTAL DE LUXE PALACIOS</div>

<p></p>
<a href="http://www.masiacalobac.com" target="_new">www.masiacalobac.com</a><br>
<div class="info">CAL OBAC</div>

<p></p>
<a href="http://www.nh-hotels.com" target="_new">www.nh-hotels.com</a><br>
<div class="info">NH MASTER</div>

<p></p>
<a href="http://www.termesvictoria.com" target="_new">www.termesvictoria.com</a><br>
<div class="info">TERMES VICTORIA</div>

<p></p>
<div class="info">hotelpdg@terra.es<br>HOTEL PASEO DE GRACIA</div>

<p></p>
<a href="http://www.hotelsonix.net" target="_new">www.hotelsonix.net</a><br>
<div class="info">HOTEL ONIX FIRA</div>

<p></p>
<a href="http://www.meridienbarcelona.com" target="_new">www.meridienbarcelona.com</a><br>
<div class="info">LE MERIDIEN BARCELONA</div>

<p></p>
<a href="http://www.hostalcolon.net" target="_new">www.hostalcolon.net</a><br>
<div class="info">HOSTAL COLON</div>

<p></p>
<div class="info">hotelcatalan@navegalia.com<br>CATALAN</div>

<p></p>
<a href="http://www.center-ramblas.com" target="_new">www.center-ramblas.com</a><br>
<div class="info">CARRER</div>

<p></p>
<a href="http://www.hotelsansebastian.com" target="_new">www.hotelsansebastian.com</a><br>
<div class="info">SAN SEBASTIAN PLAYA</div>

<p></p>
<div class="info">nhnumancia@nh-hotels.com<br>NH NUMANCIA</div>

<p></p>
<a href="http://www.hotelguillermotell.com" target="_new">www.hotelguillermotell.com</a><br>
<div class="info">HOTEL GUILLERMO TELL</div>

<p></p>
<div class="info">hmediterraneo@cambraben.es<br>MEDITERRANEO</div>

<p></p>
<div class="info">nhlamaquinista@nh-hotels.com<br>NH EXPRESS LA MAQUINISTA</div>

<p></p>
<a href="http://www.hotelamister.com" target="_new">www.hotelamister.com</a><br>
<div class="info">ÁMISTER HOTEL</div>

<p></p>
<a href="http://www.sitges.dolce.com" target="_new">www.sitges.dolce.com</a><br>
<div class="info">DOLCE SITGES</div>

<p></p>
<a href="http://www.hotelartsbarcelona.com" target="_new">www.hotelartsbarcelona.com</a><br>
<div class="info">HOTEL ARTS BARCELONA</div>

<p></p>
<a href="http://www.hotelargentona.com" target="_new">www.hotelargentona.com</a><br>
<div class="info">HOTEL VILA D'ARGENTONA</div>

<p></p>
<a href="http://www.hotelcelimar.com" target="_new">www.hotelcelimar.com</a><br>
<div class="info">HOTEL CELIMAR</div>

<p></p>
<div class="info">nhcalderon@nh-hotels.com<br>NH CALDERON</div>

<p></p>
<a href="http://www.hotelcalasanz.com" target="_new">www.hotelcalasanz.com</a><br>
<div class="info">HOTEL RESTAURANTE CALASANZ</div>

<p></p>
<div class="info">nhcornella@nh-hotels.com<br>NH CORNELLA</div>

<p></p>
<a href="http://www.ibishotel.com" target="_new">www.ibishotel.com</a><br>
<div class="info">HOTEL IBIS BARCELONA MERIDIANA</div>

<p></p>
<a href="http://www.marfina.com" target="_new">www.marfina.com</a><br>
<div class="info">MARFINA</div>

<p></p>
<div class="info">hotelcoronado.bcn@wanadoo.es<br>CORONADO</div>

<p></p>
<a href="http://www.campingplayasol.com" target="_new">www.campingplayasol.com</a><br>
<div class="info">CAMPING PLAYASOL</div>

<p></p>
<a href="http://www.canpamplona.com" target="_new">www.canpamplona.com</a><br>
<div class="info">CAN PAMPLONA</div>

<p></p>
<div class="info">nhrallye@nh-hotels.com<br>NH RALLYE</div>

<p></p>
<div class="info">nhc-mataro@nh-hoteles.es<br>NH CIUTAT DE MATARO</div>

<p></p>
<div class="info">taurus@goldenhotels.com<br>HOTEL GOLDEN TAURUS PARK</div>

<p></p>
<a href="http://www.hotelturin.com" target="_new">www.hotelturin.com</a><br>
<div class="info">TURIN</div>

<p></p>
<a href="http://www.hoteliris.com" target="_new">www.hoteliris.com</a><br>
<div class="info">IRIS</div>

<p></p>
<div class="info">hostalmiramar@ya.com<br>HOSTAL MIRAMAR</div>

<p></p>
<a href="http://www.geminisitges.com" target="_new">www.geminisitges.com</a><br>
<div class="info">HOSTAL RESIDENCIA GÉMINI SITGES</div>

<p></p>
<a href="http://www.parksedo.com" target="_new">www.parksedo.com</a><br>
<div class="info">APARTAHOTEL PARK SEDO</div>

<p></p>
<a href="http://www.gataccommodation.com" target="_new">www.gataccommodation.com</a><br>
<div class="info">HOSTAL GAT RAVAL</div>

<p></p>
<a href="http://www.miramarhotel.net" target="_new">www.miramarhotel.net</a><br>
<div class="info">HOTEL MIRAMAR</div>

<p></p>
<a href="http://www.paretselspins.com" target="_new">www.paretselspins.com</a><br>
<div class="info">HOTEL PARETS ELS PINS S.A.</div>

<p></p>
<a href="http://www.hotelatlantis-bcn.com" target="_new">www.hotelatlantis-bcn.com</a><br>
<div class="info">ATLANTIS</div>

<p></p>
<a href="http://www.hotel-lleo.es" target="_new">www.hotel-lleo.es</a><br>
<div class="info">HOTEL LLEO</div>

<p></p>
<a href="http://www.hotelcondestable.com" target="_new">www.hotelcondestable.com</a><br>
<div class="info">HOTEL CONDESTABLE</div>

<p></p>
<a href="http://www.hotelgaudi.es" target="_new">www.hotelgaudi.es</a><br>
<div class="info">HOTEL GAUDI</div>

<p></p>
<div class="info">nhbelagua@nh-hotels.com<br>NH BELAGUA</div>

<p></p>
<a href="http://www.apartamentosmurmar.com" target="_new">www.apartamentosmurmar.com</a><br>
<div class="info">APARTAMENTOS MUR - MAR</div>

<p></p>
<div class="info">info@barcelonamar.com<br>INTEGRAL RENT S.L.</div>

<p></p>
<a href="http://www.foraparc.com" target="_new">www.foraparc.com</a><br>
<div class="info">HOTEL FLORA PARC</div>

<p></p>
<div class="info">nhcorts@nh-hotels.com<br>NH LES CORTS</div>

<p></p>
<a href="http://www.hotelflorparks@ctv.es" target="_new">www.hotelflorparks@ctv.es</a><br>
<div class="info">FLOR PARKS</div>

<p></p>
<div class="info">nhpodium@nh-hotels.com<br>NH PODIUM</div>

<p></p>
<div class="info">nhsantangelo@nh-hotels.com<br>NH SANT ANGELO</div>

<p></p>
<a href="http://www.albergdeberga.com" target="_new">www.albergdeberga.com</a><br>
<div class="info">ALBERG DE BERGA S.L.</div>

<p></p>
<a href="http://www.elcastell.com" target="_new">www.elcastell.com</a><br>
<div class="info">HOTEL EL CASTELL DE SANT BOI</div>

<p></p>
<a href="http://www.hotelalfavalles.com" target="_new">www.hotelalfavalles.com</a><br>
<div class="info">AUGUSTA VALLES</div>

<p></p>
<div class="info">hoteles@bcnclassic.com<br>HOTEL BARCELONA CLASSIC</div>

<p></p>
<div class="info">nhcondor@nh-hotels.com<br>NH CONDOR</div>

<p></p>
<div class="info">exportabarcelona@nh-hotels.com<br>NH EXPRESS PORTA BARCELONA</div>

<p></p>
<a href="http://www.apartamentostavir.com" target="_new">www.apartamentostavir.com</a><br>
<div class="info">APARTAMENTS TAVIR TURISTIC</div>

<p></p>
<div class="info">nhducdelavictoria@nh-hotels.com<br>NH DUC DE LA VICTORIA</div>

<p></p>
<div class="info">info@hduquesadecardona.com<br>DUQUESA DE CARDONA</div>

<p></p>
<a href="http://www.solifemar.com" target="_new">www.solifemar.com</a><br>
<div class="info">APARTAMENTOS SOLIFEMAR</div>

<p></p>
<div class="info">reservas@hotelcristalpalace.com<br>HOTEL CRISTAL PALACE</div>

<p></p>
<a href="http://www.hotelcelimarcentre.com" target="_new">www.hotelcelimarcentre.com</a><br>
<div class="info">HOTEL CELIMAR CENTRE</div>

<p></p>
<a href="http://www.ciutatdesantadria.com" target="_new">www.ciutatdesantadria.com</a><br>
<div class="info">CIUTAT DE SANT ADRIA</div>

<p></p>
<a href="http://www.tavernaelglop.com" target="_new">www.tavernaelglop.com</a><br>
<div class="info">HOSTAL LAYETANA</div>

<p></p>
<div class="info">cancampanya@terra.es<br>CAN CAMPANYÀ</div>

<p></p>
<div class="info">CASAONS@HOTMAIL.COM<br>CASA OMS</div>

<p></p>
<a href="http://www.restaurantegolfsantfeliu.com" target="_new">www.restaurantegolfsantfeliu.com</a><br>
<div class="info">GOLF SANT FELIU</div>

<p></p>
<a href="http://www.cancanyameres.com" target="_new">www.cancanyameres.com</a><br>
<div class="info">CAN CANYAMERES</div>

<p></p>
<a href="http://www.gruplocat.com/cellerdesabadell" target="_new">www.gruplocat.com/cellerdesabadell</a><br>
<div class="info">RESTAURANTE CELLER DE SABADELL</div>

<p></p>
<a href="http://www.latrocha-casajuliana.com" target="_new">www.latrocha-casajuliana.com</a><br>
<div class="info">LA TROCHA</div>

<p></p>
<div class="info">masia-bartres@mixmail.com<br>RESTAURANT - BRASERÍA LA MASÍA BARTRÈS CATERING S.L.</div>

<p></p>
<a href="http://www.casalrestaurant.com" target="_new">www.casalrestaurant.com</a><br>
<div class="info">RESTAURANTE EL CASAL</div>

<p></p>
<a href="http://www.anxaneta.net" target="_new">www.anxaneta.net</a><br>
<div class="info">RESTAURANT L'ANXANETA</div>

<p></p>
<a href="http://www.members.xoom.com/caterristol/web%20r" target="_new">www.members.xoom.com/caterristol/web%20r</a><br>
<div class="info">RISTOL SANT LLUIS</div>

<p></p>
<a href="http://www.calmarisatany.com" target="_new">www.calmarisatany.com</a><br>
<div class="info">CAL MARISTANY</div>

<p></p>
<a href="http://www.cancabassa.com" target="_new">www.cancabassa.com</a><br>
<div class="info">CAN CABASSA CASTAÑO</div>

<p></p>
<a href="http://www.cuineta.com" target="_new">www.cuineta.com</a><br>
<div class="info">LA BONA CUINA</div>

<p></p>
<div class="info">canbonet@infonegocio.com<br>MASIA CAN BONET</div>

<p></p>
<a href="http://www.grup-soteras.com" target="_new">www.grup-soteras.com</a><br>
<div class="info">DIAGONAL - CAN SOTERAS</div>

<p></p>
<div class="info">orotava@333grup3.es<br>OROTAVA</div>

<p></p>
<a href="http://www.cacheirogrup.com" target="_new">www.cacheirogrup.com</a><br>
<div class="info">EL GRAN CAFE</div>

<p></p>
<a href="http://www.restaurantelasbotas.com" target="_new">www.restaurantelasbotas.com</a><br>
<div class="info">LAS BOTAS</div>

<p></p>
<div class="info">rest.sala@minoriza.es<br>SALA</div>

<p></p>
<div class="info">aliga@teleline.es<br>CAN PATOLLA</div>

<p></p>
<a href="http://www.calisidre.com" target="_new">www.calisidre.com</a><br>
<div class="info">CA L'ISIDRE</div>

<p></p>
<div class="info">lencisms@cdlat.ictnet.es<br>L'ENCIS</div>

<p></p>
<a href="http://www.cancortes.com" target="_new">www.cancortes.com</a><br>
<div class="info">CAN CORTES</div>

<p></p>
<div class="info">ir@internet-restaurantes.com.<br>L'AVI MINGO</div>

<p></p>
<a href="http://www.sietepuertas.es" target="_new">www.sietepuertas.es</a><br>
<div class="info">7 PORTES</div>

<p></p>
<a href="http://www.laie.es" target="_new">www.laie.es</a><br>
<div class="info">LAIE</div>

<p></p>
<a href="http://www.angrup.com" target="_new">www.angrup.com</a><br>
<div class="info">LA BOTIGA 155 RESTAURANT</div>

<p></p>
<div class="info">pmonje@adam.es<br>VIA VENETO</div>

<p></p>
<a href="http://www.elpatorrat.com" target="_new">www.elpatorrat.com</a><br>
<div class="info">EL PATORRAT</div>

<p></p>
<a href="http://www.vinyarosamagi.com" target="_new">www.vinyarosamagi.com</a><br>
<div class="info">VIÑA ROSA-MAGI</div>

<p></p>
<div class="info">reservasambassador@rivolihotels.com<br>RESTAURANTE AMBASSADOR</div>

<p></p>
<a href="http://www.elcorteingles.es" target="_new">www.elcorteingles.es</a><br>
<div class="info">RESTAURANTE EL CORTE INGLES</div>

<p></p>
<div class="info">semon@logicontrol.es<br>L'INDRET DE SEMON</div>

<p></p>
<a href="http://www.hotelmajestic.es" target="_new">www.hotelmajestic.es</a><br>
<div class="info">DROLMA HOTEL MAJESTIC</div>

<p></p>
<a href="http://www.restaurantaligue.es" target="_new">www.restaurantaligue.es</a><br>
<div class="info">ALIGUE</div>

<p></p>
<a href="http://www.garbi.com/egipto" target="_new">www.garbi.com/egipto</a><br>
<div class="info">EGIPTO</div>

<p></p>
<a href="http://www.apart-hotelmediterraneo.com" target="_new">www.apart-hotelmediterraneo.com</a><br>
<div class="info">1001 TAPAS</div>

<p></p>
<a href="http://www.lizarran.com" target="_new">www.lizarran.com</a><br>
<div class="info">LIZARRAN</div>

<p></p>
<a href="http://www.lizarran.com" target="_new">www.lizarran.com</a><br>
<div class="info">EGUZKI-LIZARRAN</div>

<p></p>
<a href="http://www.agudina.com" target="_new">www.agudina.com</a><br>
<div class="info">PULPERIA A'GUDIÑA</div>

<p></p>
<a href="http://www.cayolargocafe.com" target="_new">www.cayolargocafe.com</a><br>
<div class="info">CAYO LARGO CAFE</div>

<p></p>
<a href="http://www.lavinateria.com" target="_new">www.lavinateria.com</a><br>
<div class="info">LA VINATERIA DEL CALL</div>

<p></p>
<div class="info">marina@paradis.es<br>TAPASBAR</div>

<p></p>
<a href="http://www.lizarran.com" target="_new">www.lizarran.com</a><br>
<div class="info">LIZARRAN</div>

<p></p>
<a href="http://www.voxpopuli.com" target="_new">www.voxpopuli.com</a><br>
<div class="info">VOX POPULI</div>

<p></p>
<a href="http://www.lizarran.com" target="_new">www.lizarran.com</a><br>
<div class="info">LIZARRAN</div>

<p></p>
<a href="http://www.cacheirogrup.com" target="_new">www.cacheirogrup.com</a><br>
<div class="info">TENORIO</div>

<p></p>
<div class="info">99origens@terra.es<br>ORIGENS 99,9 %</div>

<p></p>
<div class="info">SERGIOMA@JET.ES<br>TAPES</div>

<p></p>
<a href="http://www.entretapasyvinos.com" target="_new">www.entretapasyvinos.com</a><br>
<div class="info">ENTRETAPASYVINOS</div>

<p></p>
<a href="http://www.tallerdetapas.com" target="_new">www.tallerdetapas.com</a><br>
<div class="info">TALLER DE TAPAS</div>

<p></p>
<div class="info">jcala-51@mixmail.com<br>MESON DEHESA SANTA MARIA</div>

<p></p>
<div class="info">acbarcelona@ac-hotels.com<br>EL CAFE</div>

<p></p>
<a href="http://www.entretapasyvinos.com" target="_new">www.entretapasyvinos.com</a><br>
<div class="info">ENTRETAPAS Y VINOS</div>

<p></p>

<p></p>
<a href="http://www.eljardidelapat.com" target="_new">www.eljardidelapat.com</a><br>
<div class="info">EL JARDI DE L'APAT</div>

<p></p>
<a href="http://www.tavernaelglop.com" target="_new">www.tavernaelglop.com</a><br>
<div class="info">RESTAURANT EL GLOP</div>

<p></p>
<a href="http://www.harrisonrestaurant.com" target="_new">www.harrisonrestaurant.com</a><br>
<div class="info">HARRISON FOC</div>

<p></p>
<a href="http://www.lasguias.com/elbotell" target="_new">www.lasguias.com/elbotell</a><br>
<div class="info">EL BOTELL</div>

<p></p>
<a href="http://www.guliver.es/tabernadesantamaria.htm" target="_new">www.guliver.es/tabernadesantamaria.htm</a><br>
<div class="info">SANTA MARIA</div>

<p></p>
<a href="http://www. taiet.com" target="_new">www. taiet.com</a><br>
<div class="info">TAIET</div>

<p></p>
<a href="http://www.asadoraranda.com" target="_new">www.asadoraranda.com</a><br>
<div class="info">EL ASADOR DE ARANDA</div>

<p></p>
<div class="info">rjcoll_13@hotmail.com<br>CA LA NURI</div>

<p></p>
<div class="info">cal_pages@hotmail.com<br>CAL PAGES</div>

<p></p>
<a href="http://WWW.RACODECASA.ES" target="_new">WWW.RACODECASA.ES</a><br>
<div class="info">EL RACO DE CASA</div>

<p></p>
<div class="info">reservas@rspain.com<br>VEGETARIANO ORIENTAL</div>

<p></p>
<div class="info">barcelona@hilton.com<br>Hilton Barcelona</div>

<p></p>
<div class="info">plaza@hoteles-catalonia.es<br>Catalonia Barcelona Plaza</div>

<p></p>
<div class="info">comercialban@expogrupo.com<br>Expo Hotel Barcelona TOP</div>

<p></p>
<div class="info">melia.barcelona@solmelia.es<br>Meliá Barcelona</div>

<p></p>
<div class="info">customer@meridienbarcelona.com<br>Le Meridien BarcelonaTOP</div>

<p></p>
<div class="info">reservas@condesdebarcelona.com<br>Condes de BarcelonaTOP</div>

<p></p>
<div class="info">zenitbarna@zenithoteles.com<br>Zenit Barcelona</div>

<p></p>
<div class="info">reservas@hotelbarcelonahouse.com<br>Barcelona House</div>

<p></p>
<div class="info">hotel@hesperia-sarria.com<br>Hesperia Barcelona</div>

<p></p>
<div class="info">info@hotelhusabarcelonamar.com<br>Husa Barcelona Mar</div>

<p></p>
<div class="info">bcnuniversal@nnhotels.es<br>Barcelona UniversalTOP</div>

<p></p>
<div class="info">h10.marina.barcelona@h10.es<br>H10 Marina Barcelona</div>

<p></p>
<div class="info">info@aquariumbcn.com<br>L'Aquàrium de BarcelonaTOP</div>

<p></p>
<div class="info">infozoo@zoobarcelona.com<br>Parque Zoológico de BarcelonaTOP</div>

<p></p>
<div class="info">custo-olles@custo-barcelona.com<br>Custo Barcelona (Pl. les Olles) TOP</div>

<p></p>
<div class="info">fmacba@macba.es<br>MACBA. Museu d'Art Contemporani de Barcelona</div>

<p></p>
<div class="info">infoclos@fundclos.com<br>Museu Egipci de Barcelona - Fundació Arqueológica Clos</div>

<p></p>
<div class="info">minibuses@arrakis.es<br>Mini Vip's Guías de Barcelona</div>

<p></p>
<div class="info">vespa.barcelona@maptel.es<br>Vespa Barcelona</div>

<p></p>
<div class="info">agencia@intercom.es<br>Mesa de Asociaciones de Cultura de Barcelona</div>

<p></p>
<div class="info">apdeb@d5.ub.es<br>Aula de Poesía de Barcelona</div>

<p></p>
<div class="info">asso_palasatenea@hotmail.com<br>Asociación de Mujeres Palas Atenea de Barcelona</div>

<p></p>
<a href="http://www.restaurantelasbotas.com" target="_new">www.restaurantelasbotas.com</a><br>
<div class="info">LAS BOTAS</div>

<p></p>
<div class="info">aliga@teleline.es<br>CAN PATOLLA</div>

<p></p>
<div class="info">espagueti@teleline.es</div>

<p></p>
<a href="http://www.calisidre.com" target="_new">www.calisidre.com</a><br>
<div class="info">CA L'ISIDRE</div>

<p></p>
<div class="info">lencisms@cdlat.ictnet.es<br>L'ENCIS</div>

<p></p>
<a href="http://www.cancortes.com" target="_new">www.cancortes.com</a><br>
<div class="info">CAN CORTES</div>

<p></p>
<div class="info">nasi@lix.intercom.es<br>CA L'IGNASI</div>

<p></p>
<a href="http://www.internet-restaurantes.com" target="_new">www.internet-restaurantes.com</a><br>
<div class="info">L'AVI MINGO</div>

<p></p>
<div class="info">restaurante@hotelespanya.com<br>FONDA DE ESPAÑA</div>

<p></p>
<div class="info">barcelona@hilton.com<br>MOSAIC</div>

<p></p>
<div class="info">barcelona@hilton.com<br>LA HIEDRA</div>

<p></p>
<a href="http://www.playasenator.com" target="_new">www.playasenator.com</a><br>
<div class="info">RESTAURANTE PLAYA SENATOR</div>

<p></p>
<div class="info">restamar@yahoo.es<br>FRAGATA</div>

<p></p>
<div class="info">scenic@scenic.es<br>OLIMPIA</div>

<p></p>
<div class="info">astoria@derbyhotels.es<br>RESTAURANTE ASTORIA</div>

<p></p>
<div class="info">derby@derbyhotels.es<br>THE TIMES</div>

<p></p>
<div class="info">derby@derbyhotels.es<br>EPSOM</div>

<p></p>
<div class="info">cdc-hotel@ggrup-soteras.com<br>EL REBOST</div>

<p></p>
<a href="http://www.maspi.com" target="_new">www.maspi.com</a><br>
<div class="info">MAS PI</div>

<p></p>
<div class="info">POLINYA@RESTAURANTSPARADIS.COM<br>PARADIS</div>

<p></p>
<a href="http://www.hotelcristalpalace.com" target="_new">www.hotelcristalpalace.com</a><br>
<div class="info">PICTORY</div>

<p></p>
<div class="info">hotel@hesperia-delmar.com<br>AL PUNTO</div>

<p></p>
<div class="info">restaurante@caelis.com<br>CAELIS</div>

<p></p>
<div class="info">ritz@ritzbcn.com<br>EL JARDIN DE DIANA</div>

<p></p>
<div class="info">receptionexpobcn@expogrupo.com<br>RESTAURANTE EXPO HOTEL</div>

<p></p>
<a href="http://www.hotel-capital.com" target="_new">www.hotel-capital.com</a><br>
<div class="info">RESTAURANTE CAPITAL</div>

<p></p>
<div class="info">mikado@hoteles-catalonia.es<br>RESTAURANTE MIKADO</div>

<p></p>
<a href="http://www.ibishotel.com" target="_new">www.ibishotel.com</a><br>
<div class="info">RESTAURANTE EL CAFE</div>

<p></p>
<a href="http://www.ibishotel.com" target="_new">www.ibishotel.com</a><br>
<div class="info">EL RACO</div>

<p></p>
<div class="info">h3445@accord.com<br>PLANCHA Y PARRILLA</div>

<p></p>
<div class="info">h1167-fb@hotels.com<br>CLARAVIA</div>

<p></p>
<a href="http://www.business-cafe-restaurants.com" target="_new">www.business-cafe-restaurants.com</a><br>
<div class="info">SAMOA</div>

<p></p>
<a href="http://www.sietepuertas.es" target="_new">www.sietepuertas.es</a><br>
<div class="info">7 PORTES</div>

<p></p>
<div class="info">info@hotel-santcugat.com<br>STC RESTAURANTE</div>

<p></p>
<a href="http://www.casino-barcelona.com" target="_new">www.casino-barcelona.com</a><br>
<div class="info">LE GOURMAND</div>

<p></p>
<a href="http://www.laie.es" target="_new">www.laie.es</a><br>
<div class="info">LAIE</div>

<p></p>
<div class="info">info@restaurantlacucanya.com<br>LA CUCANYA</div>

<p></p>
<a href="http://www.botafumeiro.es" target="_new">www.botafumeiro.es</a><br>
<div class="info">BOTAFUMEIRO</div>

<p></p>
<a href="http://www.relaischateaux.com/neichel" target="_new">www.relaischateaux.com/neichel</a><br>
<div class="info">RESTAURANTE NEICHEL</div>

<p></p>
<a href="http://www.angrup.com" target="_new">www.angrup.com</a><br>
<div class="info">LA BOTIGA 155 RESTAURANT</div>

<p></p>
<div class="info">pmonje@adam.es<br>VIA VENETO</div>

<p></p>
<div class="info">barcelonamar@husa.es<br>LA TORRE DE L'AIGUA</div>

<p></p>
<div class="info">hotelilla@husa.es<br>AMESIS</div>

<p></p>
<div class="info">grancatalonia@hoteles-catalonia.es<br>RESTAURANTE GRAN CATALONIA</div>

<p></p>
<a href="http://www.elpatorrat.com" target="_new">www.elpatorrat.com</a><br>
<div class="info">EL PATORRAT</div>

<p></p>
<a href="http://www.vinyarosamagi.com" target="_new">www.vinyarosamagi.com</a><br>
<div class="info">VIÑA ROSA-MAGI</div>

<p></p>
<a href="http://www.casajordi.es" target="_new">www.casajordi.es</a><br>
<div class="info">CASA JORDI</div>

<p></p>
<div class="info">reservasambassador@rivolihotels.com<br>RESTAURANTE AMBASSADOR</div>

<p></p>
<div class="info">comercial@rivolihotels.com<br>LE BRUT</div>

<p></p>
<a href="http://www.canametller.com" target="_new">www.canametller.com</a><br>
<div class="info">MASIA CAN AMETLLER</div>

<p></p>
<a href="http://www.elcorteingles.es" target="_new">www.elcorteingles.es</a><br>
<div class="info">RESTAURANTE EL CORTE INGLES</div>

<p></p>
<a href="http://www.hoteles-hesperia.es" target="_new">www.hoteles-hesperia.es</a><br>
<div class="info">PETIT PRINCEP</div>

<p></p>
<div class="info">semon@logicontrol.es<br>L'INDRET DE SEMON</div>

<p></p>
<a href="http://www.hipercor.es" target="_new">www.hipercor.es</a><br>
<div class="info">RESTAURANTE HIPERCOR</div>

<p></p>
<a href="http://www.hotelmajestic.es" target="_new">www.hotelmajestic.es</a><br>
<div class="info">EL BUFFET DEL MAJESTIC</div>

<p></p>
<a href="http://www.nh-hotels.com" target="_new">www.nh-hotels.com</a><br>
<div class="info">PINEA</div>

<p></p>
<div class="info">nhcalderon@nh-hotels.com<br>EL CALDERON</div>

<p></p>
<div class="info">nhducdelavictoria@nh-hotels.com<br>RESTAURANTE DUC DE LA VICTORIA</div>

<p></p>
<div class="info">nhlescorts@nh-hotels.com<br>RESTAURANTE LES CORTS</div>

<p></p>
<div class="info">avpalace@husa.es<br>RESTAURANTE INSOLIT</div>

<p></p>
<a href="http://www.restaurantaligue.es" target="_new">www.restaurantaligue.es</a><br>
<div class="info">ALIGUE</div>

<p></p>
<a href="http://www.garbi.com/egipto" target="_new">www.garbi.com/egipto</a><br>
<div class="info">EGIPTO</div>

<p></p>
<a href="http://www.calpinxo.com" target="_new">www.calpinxo.com</a><br>
<div class="info">CAL PINXO</div>

<p></p>
<div class="info">claris@derbyhotels.es<br>EAST 47</div>

<p></p>
<a href="http://www.galleryhotel.com" target="_new">www.galleryhotel.com</a><br>
<div class="info">CAFE DEL GALLERY</div>

<p></p>
<a href="http://www.hotelitaca.com" target="_new">www.hotelitaca.com</a><br>
<div class="info">RESTAURANTE ITACA</div>

<p></p>
<a href="http://www.lluernarestaurant.com" target="_new">www.lluernarestaurant.com</a><br>
<div class="info">LLUERNA</div>

<p></p>
<a href="http://www.rocxi.com" target="_new">www.rocxi.com</a><br>
<div class="info">ROCXY CASTELLDEFELS</div>

<p></p>
<a href="http://www.hisop.com" target="_new">www.hisop.com</a><br>
<div class="info">HISOP</div>

<p></p>
<a href="http://www.triberica.com" target="_new">www.triberica.com</a><br>
<div class="info">EL TRILLO</div>

<p></p>
<a href="http://WWW.lambigu.com" target="_new">WWW.lambigu.com</a><br>
<div class="info">L'AMBIGU</div>

<p></p>
<a href="http://www.notifixis.net" target="_new">www.notifixis.net</a><br>
<div class="info">NOTIFIXIS</div>

<p></p>
<a href="http://www.rescco.com" target="_new">www.rescco.com</a><br>
<div class="info">FRESC CO</div>

<p></p>
<a href="http://www.grandmarinahotel.com" target="_new">www.grandmarinahotel.com</a><br>
<div class="info">AIRE DE MAR</div>

<p></p>
<div class="info">polentaes@yahoo.es<br>POLENTA</div>

<p></p>
<a href="http://www.hotel-gravina.com" target="_new">www.hotel-gravina.com</a><br>
<div class="info">RESTAURANTE GRAVINA</div>

<p></p>
<div class="info">cal morilla.@.wanadoo.es<br>CAL MORILLA</div>

<p></p>
<a href="http://www.feliz2.com" target="_new">www.feliz2.com</a><br>
<div class="info">FELI? 2</div>

<p></p>
<div class="info">acvilamari@achotels.com<br>ACTUAL</div>

<p></p>
<a href="http://www.granparis.com" target="_new">www.granparis.com</a><br>
<div class="info">GRAN PARIS</div>

<p></p>
<div class="info">reservas.bestial@grupotragaluz<br>BESTIAL</div>

<p></p>
<div class="info">atriumpalace@apsishotels.com<br>APSIS RESTAURANTE</div>

<p></p>
<div class="info">ellulure@tiscali.es<br>EL LLIURE</div>

<p></p>
<a href="http://www.freudbart.com" target="_new">www.freudbart.com</a><br>
<div class="info">FREUD B?ART</div>

<p></p>
<div class="info">mmandrion@pedralvesbistrot.com<br>BISTROT DE PEDRALBES</div>

<p></p>
<a href="http://www.hotellaflorida.com" target="_new">www.hotellaflorida.com</a><br>
<div class="info">L'ORANGERIE</div>

<p></p>
<div class="info">mk1@angrup.com<br>ATTIC RESTAURANT</div>

<p></p>
<div class="info">albertoflores@telefonica.net<br>EL RACO DE LA NOLY</div>

<p></p>
<a href="http://www.hotelcalasanz.com" target="_new">www.hotelcalasanz.com</a><br>
<div class="info">CALASANZ</div>

<p></p>
<a href="http://www.pantaiberic.com" target="_new">www.pantaiberic.com</a><br>
<div class="info">LALLAR DEL JABUGO</div>

<p></p>
<div class="info">jcala-51@mixmail.com<br>MESON DEHESA SANTA MARIA</div>

<p></p>
<div class="info">garden@abbahoteles.com<br>AMALUR</div>

<p></p>
<div class="info">info@hotelpulitzer.es<br>RESTAURANTE VISIT</div>

<p></p>
<div class="info">acbarcelona@ac-hotels.com<br>DIA & NIT</div>

<p></p>
<a href="http://www.elnou-cents.com" target="_new">www.elnou-cents.com</a><br>
<div class="info">EL NOU-CENTS</div>

<p></p>
<a href="http://www.calpinxositges.com" target="_new">www.calpinxositges.com</a><br>
<div class="info">CAL PINXO</div>

<p></p>
<a href="http://www.entretapasyvinos.com" target="_new">www.entretapasyvinos.com</a><br>
<div class="info">ENTRETAPAS Y VINOS</div>

<p></p>
<a href="http://www.cotursahotels.com" target="_new">www.cotursahotels.com</a><br>
<div class="info">RESTAURANTE COTURSA ROSELLO</div>

<p></p>
<a href="http://www.candelaraval.com" target="_new">www.candelaraval.com</a><br>
<div class="info">CANDELA</div>

<p></p>
<div class="info">montblanc@hcchotels.es<br>RACO GAUDI</div>

<p></p>
<a href="http://www.mitosbarcelona.com" target="_new">www.mitosbarcelona.com</a><br>
<div class="info">MITOS</div>

<p></p>
<a href="http://www.xaletdemontjuic.com" target="_new">www.xaletdemontjuic.com</a><br>
<div class="info">MONTJUIC EL XALET</div>

<p></p>
<a href="http://www.lafondadelabruixa.com" target="_new">www.lafondadelabruixa.com</a><br>
<div class="info">LA FONDA DE LA BRUIXA</div>

<p></p>
<div class="info">txikiteotabernavasca@hotmail.com<br>TXIKITEO</div>

<p></p>
<div class="info">btaillard@telefonica.net<br>CALCIUMMM</div>

<p></p>
<div class="info">arbeca@yahoo.es<br>L'ARBECA RESTAURANT</div>

<p></p>
<a href="http://www.espaisucre.com" target="_new">www.espaisucre.com</a><br>
<div class="info">ESPAI SUCRE</div>

<p></p>
<a href="http://www.elpedregar.com" target="_new">www.elpedregar.com</a><br>
<div class="info">EL PEDREGAR DE BELLATERRA</div>

<p></p>
<a href="http://www.asadoraranda.com" target="_new">www.asadoraranda.com</a><br>
<div class="info">EL ASADOR DE ARANDA</div>

<p></p>
<a href="http://www.pantaiberic.com" target="_new">www.pantaiberic.com</a><br>
<div class="info">LALLAR DEL JABUGO</div>

<p></p>
<a href="http://www.merenderodelamari.com" target="_new">www.merenderodelamari.com</a><br>
<div class="info">MERENDERO DE LA MARI</div>

<p></p>
<a href="http://www.eljardidelapat.com" target="_new">www.eljardidelapat.com</a><br>
<div class="info">EL JARDI DE L'APAT</div>

<p></p>
<a href="http://www.lamasiacanportell.com" target="_new">www.lamasiacanportell.com</a><br>
<div class="info">MASIA CAN PORTELL</div>

<p></p>
<a href="http://www.restaurantwindsor.com" target="_new">www.restaurantwindsor.com</a><br>
<div class="info">WINDSOR</div>

<p></p>
<a href="http://www.culleradeboix.com" target="_new">www.culleradeboix.com</a><br>
<div class="info">CULLERA DE BOIX</div>

<p></p>
<a href="http://www.castelldefels.com/canferal" target="_new">www.castelldefels.com/canferal</a><br>
<div class="info">RESTAURANTE CAN FERAL</div>

<p></p>
<a href="http://www.monchos.com" target="_new">www.monchos.com</a><br>
<div class="info">ASADOR DEL MAR</div>

<p></p>
<a href="http://www.jaumeprovenza.com" target="_new">www.jaumeprovenza.com</a><br>
<div class="info">JAUME DE PROVENCA</div>

<p></p>
<a href="http://www.cansarda.com" target="_new">www.cansarda.com</a><br>
<div class="info">restaurant Cansarda</div>

<p></p>
<a href="http://www.moka-elsfanals.com" target="_new">www.moka-elsfanals.com</a><br>
<div class="info">MOKA</div>

<p></p>
<a href="http://www.restaurantcanoliver.com" target="_new">www.restaurantcanoliver.com</a><br>
<div class="info">CAN OLIVER</div>

<p></p>
<a href="http://www.canpique.com" target="_new">www.canpique.com</a><br>
<div class="info">CAN PIQU?</div>

<p></p>
<a href="http://www.masgranell.com" target="_new">www.masgranell.com</a><br>
<div class="info">MASGRANELL</div>

<p></p>
<a href="http://www.masiareixac.com" target="_new">www.masiareixac.com</a><br>
<div class="info">MAS?A DE REIXAC</div>

<p></p>
<a href="http://www.lafontdelbosc.com" target="_new">www.lafontdelbosc.com</a><br>
<div class="info">LA FONT DEL BOSC</div>

<p></p>
<a href="http://www.mont-bell.es" target="_new">www.mont-bell.es</a><br>
<div class="info">RESTAURANT MONT - BELL</div>

<p></p>
<a href="http://www.esl4vents.com" target="_new">www.esl4vents.com</a><br>
<div class="info">4 VENTS</div>

<p></p>
<a href="http://www.cantraver.es" target="_new">www.cantraver.es</a><br>
<div class="info">RESTAURANTE CAN TRAVER</div>

<p></p>
<a href="http://www.lamasiadelametlla.com" target="_new">www.lamasiadelametlla.com</a><br>
<div class="info">LA MASIA</div>

<p></p>
<div class="info">canxixol@teleline.es<br>RESTAURANT CAN XIXOL</div>

<p></p>
<a href="http://www.castellarnau.com" target="_new">www.castellarnau.com</a><br>
<div class="info">CASTELL ARNAU</div>

<p></p>
<a href="http://www.canfeliu.com" target="_new">www.canfeliu.com</a><br>
<div class="info">MASIA CAN FELIU</div>

<p></p>
<a href="http://www.gargantuaipantagruel.com" target="_new">www.gargantuaipantagruel.com</a><br>
<div class="info">GARGANTUA Y PANTAGRUEL</div>

<p></p>
<a href="http://www.elviverositges.com" target="_new">www.elviverositges.com</a><br>
<div class="info">RESTAURANTE EL VIVERO</div>

<p></p>
<div class="info">info@elmexicanodebarcelona.com<br>El Mexicano de BarcelonaTOP</div>

<p></p>
<div class="info">cafe@cafeinternet.es<br>Café Internet</div>

<p></p>
<div class="info">barcelona7dreams@hotmail.com<br>Barcelona 7 DreamsTOP</div>

<p></p>
<div class="info">reservas@boitaullresort.es<br>Boí-Taüll en Barcelona</div>

<p></p>
<div class="info">reservas@rspain.com<br>Arts BarcelonaTOP</div>

<p></p>
<div class="info">moncho@ctv.es<br>Moncho's Barcelona</div>

<p></p>
<div class="info">restaurant@elmiradorbcn.com<br>El Mirador de Barcelona-Restaurante El Cordero</div>

<p></p>
<a href="http://www.milisa.com" target="_new">www.milisa.com</a><br>
<div class="info">AL PASSATORE</div>

<p></p>
<a href="http://www.cms.es/venezia" target="_new">www.cms.es/venezia</a><br>
<div class="info">PIZZERÍA RESTAURANTE VENEZIA</div>

<p></p>
<div class="info">norca@intercom.es<br>MENORCA</div>

<p></p>
<a href="http://www.restaurantlacucanya.com" target="_new">www.restaurantlacucanya.com</a><br>
<div class="info">LA CUCANYA</div>

<p></p>
<div class="info">targa@tecsic.com<br>LA TARGA FLORIO</div>

<p></p>
<a href="http://www.clubvips.com" target="_new">www.clubvips.com</a><br>
<div class="info">GINOS</div>

<p></p>
<a href="http://www.losinmortales.es" target="_new">www.losinmortales.es</a><br>
<div class="info">INMORTALES</div>

<p></p>
<a href="http://www.tramonti1980.com" target="_new">www.tramonti1980.com</a><br>
<div class="info">TRAMONTI 1980</div>

<p></p>
<div class="info">hostel@cecosnet.es<br>SAPRI PIZZA</div>

<p></p>
<a href="http://www.doncarpi.com" target="_new">www.doncarpi.com</a><br>
<div class="info">DON PIZZA</div>

<p></p>
<a href="http://www.milisa.com" target="_new">www.milisa.com</a><br>
<div class="info">AL PASSATORE</div>

<p></p>
<a href="http://www.pizzeria-vivaldi.com" target="_new">www.pizzeria-vivaldi.com</a><br>
<div class="info">VIVALDI</div>

<p></p>
<a href="http://www.gulliver.es/eljardi.htm" target="_new">www.gulliver.es/eljardi.htm</a><br>
<div class="info">SABOR D'ITALIA</div>

<p></p>
<a href="http://www.buenasmigas.com" target="_new">www.buenasmigas.com</a><br>
<div class="info">LAS BUENAS MIGAS</div>

<p></p>
<a href="http://www.doncarpi.com" target="_new">www.doncarpi.com</a><br>
<div class="info">CVADENA DON PIZZA</div>

<p></p>
<a href="http://www.biceristorante.com" target="_new">www.biceristorante.com</a><br>
<div class="info">BICE</div>

<p></p>
<a href="http://www.san-marzano.com" target="_new">www.san-marzano.com</a><br>
<div class="info">SAN MARZANO</div>

<p></p>
<a href="http://www.sapripizza.com" target="_new">www.sapripizza.com</a><br>
<div class="info">GALILEO</div>

<p></p>
<div class="info">barcelona2@frankie&benny101.com<br>FRANKIE & BENNY'S</div>

<p></p>
<a href="http://www.pastarito-pizzarito.com" target="_new">www.pastarito-pizzarito.com</a><br>
<div class="info">PASTARITO PIZZARITO</div>

<p></p>
<a href="http://www.gentedepasta.com" target="_new">www.gentedepasta.com</a><br>
<div class="info">GENTE DE PASTA</div>

<p></p>
<div class="info">reservas.bestial@grupotragaluz<br>BESTIAL</div>

<p></p>
<a href="http://www.latagliatella.es" target="_new">www.latagliatella.es</a><br>
<div class="info">LA TAGLIATELLA</div>

<p></p>
<div class="info">restaurante_raffaello@yahoo.<br>RESTAURANTE RAFFAELLO</div>

<p></p>
<a href="http://www.galeriagastronomica.com" target="_new">www.galeriagastronomica.com</a><br>
<div class="info">GALERIA GASTRONOMICA</div>

<p></p>
<a href="http://www.grupotragaluz.com" target="_new">www.grupotragaluz.com</a><br>
<div class="info">TRAGALUZ</div>

<p></p>
<a href="http://www.sobaculture.com" target="_new">www.sobaculture.com</a><br>
<div class="info">SOBA SUSHI & LOUNGE</div>

<p></p>
<a href="http://www.casino-barcelona.com" target="_new">www.casino-barcelona.com</a><br>
<div class="info">TEPPAN YAKI</div>

<p></p>
<a href="http://www.kinsushibar.com" target="_new">www.kinsushibar.com</a><br>
<div class="info">KIN SUSHIBAR</div>

<p></p>
<a href="http://www.hello-sushi.com" target="_new">www.hello-sushi.com</a><br>
<div class="info">HELLO SUSHI</div>

<p></p>
<div class="info">polentaes@yahoo.es<br>POLENTA</div>

<p></p>
<a href="http://www.sushiexpress.net" target="_new">www.sushiexpress.net</a><br>
<div class="info">SUSHIEXPRESS</div>

<p></p>
<a href="http://www.restauranteasia.com" target="_new">www.restauranteasia.com</a><br>
<div class="info">ASIA</div>

<p></p>
<div class="info">jmonegal@thesushiplanet.com<br>KENTO</div>

<p></p>
<a href="http://www.memoriasdechina.com" target="_new">www.memoriasdechina.com</a><br>
<div class="info">MEMORIAS DE CHINA</div>

<p></p>
<div class="info">shangai@patopekin.com<br>SHANGHAI</div>

<p></p>
<a href="http://www.come.tu/orientalformosa" target="_new">www.come.tu/orientalformosa</a><br>
<div class="info">TONG LIN</div>

<p></p>
<div class="info">jiang@abaforum.com<br>DA JIANG JIN</div>

<p></p>
<div class="info">dongjie@teleline.es<br>GRAN BARCELONA</div>

<p></p>
<a href="http://www.feliz2.com" target="_new">www.feliz2.com</a><br>
<div class="info">FELIÇ 2</div>

<p></p>
<div class="info">masia@grn.es<br>MASIA CAN PORTELL</div>

<p></p>
<a href="http://www.elspescadors.com" target="_new">www.elspescadors.com</a><br>
<div class="info">ELS PESCADORS</div>

<p></p>
<a href="http://www.elcapitangarfio.net" target="_new">www.elcapitangarfio.net</a><br>
<div class="info">EL CAPITÁN GARFIO</div>

<p></p>
<a href="http://www.restaurantwindsor.com" target="_new">www.restaurantwindsor.com</a><br>
<div class="info">WINDSOR</div>

<p></p>
<a href="http://www.tapelia.com" target="_new">www.tapelia.com</a><br>
<div class="info">TAPELIA</div>

<p></p>
<a href="http://www.culleradeboix.com" target="_new">www.culleradeboix.com</a><br>
<div class="info">CULLERA DE BOIX</div>

<p></p>
<a href="http://www.elpedregar.com" target="_new">www.elpedregar.com</a><br>
<div class="info">EL PEDREGAR DE BELLATERRA</div>

<p></p>
<a href="http://www.castelldefels.com/canferal" target="_new">www.castelldefels.com/canferal</a><br>
<div class="info">RESTAURANTE CAN FERAL</div>

<p></p>
<a href="http://www.lafitora.com" target="_new">www.lafitora.com</a><br>
<div class="info">LA FITORA</div>

<p></p>
<a href="http://www.canpique.com" target="_new">www.canpique.com</a><br>
<div class="info">CAN PIQUÉ</div>

<p></p>
<div class="info">hcberga@hostalets.com<br>CAN SARDÀ</div>

<p></p>
<a href="http://www.hotelestel.com" target="_new">www.hotelestel.com</a><br>
<div class="info">Hotel Estel</div>

<p></p>
<div class="info">info@vilaformiu.com<br>El Cobert de Vilaformiu</div>

<p></p>
<a href="http://www.parador.es" target="_new">www.parador.es</a><br>
<div class="info">PARADOR DE VIC-SAU</div>

<p></p>
<div class="info">nhciutatdevic@nh-hotels.com<br>NH Ciutat de Vic</div>

<p></p>
<div class="info">cardona@parador.es<br>PARADOR DE CARDONA</div>

<p></p>
<a href="http://www.hoteldoncandido.com" target="_new">www.hoteldoncandido.com</a><br>
<div class="info">Don Cándido</div>

<p></p>
<div class="info">Terrasa Park</div>
<a href="http://www.hotelterrassapark.com" target="_new">www.hotelterrassapark.com</a><br>

<p></p>
<div class="info">info@aparthotel-ateneavalles.com<br>ATENEA VALLÈS Aparthotel</div>

<p></p>
<a href="http://www.ciutathotels.com" target="_new">www.ciutathotels.com</a><br>
<div class="info">Ciutat de Granollers</div>

<p></p>
<div class="info">express.montmelo@ichotelsgroup.com<br>Express By Holiday Inn</div>

<p></p>
<a href="http://www.hotelaugustavalles.com" target="_new">www.hotelaugustavalles.com</a><br>
<div class="info">Cadenas: Diagonal Hotels</div>

<p></p>
<a href="http://www.aquahotel.com" target="_new">www.aquahotel.com</a><br>
<div class="info">Aqua Hotel</div>

<p></p>
<div class="info">info@hotelaugustavalles.com<br>Hotel August Avalles</div>

<p></p>
<a href="http://www.hotelstellapineda.com" target="_new">www.hotelstellapineda.com</a><br>
<div class="info">El Hotel Stella</div>

<p></p>
<a href="http://www.hotelbrisamar.com" target="_new">www.hotelbrisamar.com</a><br>
<div class="info">Brisamar</div>

<p></p>
<a href="http://www.hotelsabiote.com" target="_new">www.hotelsabiote.com</a><br>
<div class="info">Sabiote Hotel</div>

<p></p>
<a href="http://www.hotelcatalan.com" target="_new">www.hotelcatalan.com</a><br>
<div class="info">Catalán Hotel</div>

<p></p>
<a href="http://www.ciutathotels.com/ES/ch_mollet.htm" target="_new">www.ciutathotels.com/ES/ch_mollet.htm</a><br>
<div class="info">Ciutat de Mollet</div>

<p></p>
<a href="http://www.hotelformule1.com" target="_new">www.hotelformule1.com</a><br>
<div class="info">Hotel Torre Vermella</div>

<p></p>
<a href="http://www.hotelbarberaparc.com" target="_new">www.hotelbarberaparc.com</a><br>
<div class="info">Barberà Parc Hotel</div>

<p></p>
<a href="http://www.hotelcastelldemata.com/esp/empresa.htm" target="_new">www.hotelcastelldemata.com/esp/empresa.htm</a><br>
<div class="info">Castell de Mata Hotel</div>

<p></p>
<a href="http://www.novotel.com/novotel/fichehotel/gb/nov/3289/fiche_hotel.shtml" target="_new">www.novotel.com/novotel/fichehotel/gb/nov/3289/fiche_hotel.shtml</a><br>
<div class="info">Novotel Sant Joan Despí Hotel</div>

<p></p>
<a href="http://www.hotelsuburmaritim.com/cgi-bin/smaritim/index.asp" target="_new">www.hotelsuburmaritim.com/cgi-bin/smaritim/index.asp</a><br>
<div class="info">Subur Maritim Hotel</div>

<p></p>
<a href="http://www.hotelsubur.com" target="_new">www.hotelsubur.com</a><br>
<div class="info">Subur Hotel</div>

<p></p>
<a href="http://www.hotelmontserrat-sitges.com/spanish/main.html" target="_new">www.hotelmontserrat-sitges.com/spanish/main.html</a><br>
<div class="info">Montserrat</div>

<p></p>
<a href="http://www.hotelmontserrat-sitges.com/apartments/index.spanish.html" target="_new">www.hotelmontserrat-sitges.com/apartments/index.spanish.html</a><br>
<div class="info">Apartamentos Montserrat</div>

<p></p>

<p></p>
<a href="http://www.hotelmontserrat-sitges.com/espalter/index.spanish.html" target="_new">www.hotelmontserrat-sitges.com/espalter/index.spanish.html</a><br>
<div class="info">Espalter, 11</div>

<p></p>
<a href="http://www.antemare.com/castellano/contacto.html" target="_new">www.antemare.com/castellano/contacto.html</a><br>
<div class="info">Hotel Antemare "Nova Dimensió" ****</div>

<p></p>
<a href="http://www.ahmediterraneo.com/index.html" target="_new">www.ahmediterraneo.com/index.html</a><br>
<div class="info">Mediterráneo ApartHotel</div>

<p></p>
<div class="info">melia.sitges@solmelia.com<br>Meliá Sitges  Hotel</div>

<p></p>
<a href="http://www.portsitges.com" target="_new">www.portsitges.com</a><br>
<div class="info">Port Sitges Resort Hotel</div>

<p></p>
<div class="info">hotelsansebastian@hotelsansebastian.com<br>San Sebastian Playa Hotel</div>

<p></p>
<a href="http://www.hotelterramar.com/index.asp?idioma=CAS" target="_new">www.hotelterramar.com/index.asp?idioma=CAS</a><br>
<div class="info">Terramar Hotel</div>

<p></p>
<a href="http://www.hotelcelimar.com" target="_new">www.hotelcelimar.com</a><br>
<div class="info">Hotel Celimar</div>

<p></p>
<a href="http://www.lapinta.net" target="_new">www.lapinta.net</a><br>
<div class="info">Hotel La Pinta</div>

<p></p>
<a href="http://www.lasantamaria.com" target="_new">www.lasantamaria.com</a><br>
<div class="info">Hotel La Santa Maria</div>

<p></p>
<a href="http://www.elxalet.com" target="_new">www.elxalet.com</a><br>
<div class="info">Hotel  Xalet</div>

<p></p>
<a href="http://www.elxalet.com" target="_new">www.elxalet.com</a><br>
<div class="info">Hotel Garraf</div>

<p></p>
<a href="http://www.libertyhotelsitges.com" target="_new">www.libertyhotelsitges.com</a><br>
<div class="info">Hotel Liberty</div>

<p></p>
<a href="http://www.milisa.com/P.Maricel/maricel.htm" target="_new">www.milisa.com/P.Maricel/maricel.htm</a><br>
<div class="info">PENCION MARICEL</div>

<p></p>
<a href="http://www.hotelromantic.com" target="_new">www.hotelromantic.com</a><br>
<div class="info">Hotel Romantic</div>

<p></p>
<a href="http://www.hostaltermes.com" target="_new">www.hostaltermes.com</a><br>
<div class="info">Hostal Termes - C/ Termes 9 - Sitges (Barcelona)</div>

<p></p>
<a href="http://www.los-globos.com" target="_new">www.los-globos.com</a><br>
<div class="info">HOTEL LOS GLOBOS</div>

<p></p>
<a href="http://www.hai-partner.com" target="_new">www.hai-partner.com</a><br>
<div class="info">Hotel HAI - Don Jaime ****</div>

<p></p>
<a href="http://www.apartamentoscactus.com" target="_new">www.apartamentoscactus.com</a><br>
<div class="info">CACTUS APARTAMENT</div>

<p></p>
<div class="info">Ibis Castelldefels</div>
<a href="http://www.hesperia-castelldefe ls.com" target="_new">www.hesperia-castelldefe ls.com</a><br>

<p></p>
<a href="http://www.ibishotel.com/ibis/fichehotel/gb/ibi/3208/fiche_hotel.shtml#info" target="_new">www.ibishotel.com/ibis/fichehotel/gb/ibi/3208/fiche_hotel.shtml#info</a><br>
<div class="info">Hotel Ibis</div>

<p></p>
<a href="http://www.marfina.com" target="_new">www.marfina.com</a><br>
<div class="info">Apartemento Marfina</div>

<p></p>
<a href="http://www.hotelcesar.net" target="_new">www.hotelcesar.net</a><br>
<div class="info">Hotel Cesar</div>

<p></p>
<div class="info">tryp.barcelona.aeropuerto@solmelia.com<br>Tryp Barcelona Aeropuerto   ****</div>

<p></p>
<a href="http://www.miramarhotel.net" target="_new">www.miramarhotel.net</a><br>
<div class="info">Miramar Hotel</div>

<p></p>
<a href="http://www.bajabeach.es" target="_new">www.bajabeach.es</a><br>
<div class="info">BAJA BEAH CLUB</div>

<p></p>
<a href="http://www.blue-iceclub.com" target="_new">www.blue-iceclub.com</a><br>
<div class="info">BLUE ICE CLUB</div>

<p></p>
<a href="http://www.grupocostaeste.com" target="_new">www.grupocostaeste.com</a><br>
<div class="info">BUCARO</div>

<p></p>
<a href="http://www.mojitobcn.com" target="_new">www.mojitobcn.com</a><br>
<div class="info">MOJITO CLUB</div>

<p></p>
<a href="http://www.pubyfiesta.com/base.php?name=pubportal&pub_id=000283" target="_new">www.pubyfiesta.com/base.php?name=pubportal&pub_id=000283</a><br>
<div class="info">NICK HAVANNA</div>

<p></p>
<a href="http://www.tunnelbalmes.com" target="_new">www.tunnelbalmes.com</a><br>
<div class="info">TUNNEL CASANOVA</div>

<p></p>
<a href="http://www.antillasalsa.com/ppal.html" target="_new">www.antillasalsa.com/ppal.html</a><br>
<div class="info">ANTILLA BCN LATIN CLUB</div>

<p></p>
<a href="http://www.arenadisco.com" target="_new">www.arenadisco.com</a><br>
<div class="info">ARENA CLASSIC</div>

<p></p>
<a href="http://www.bovedagroup.com" target="_new">www.bovedagroup.com</a><br>
<div class="info">BOVEDA</div>

<p></p>
<a href="http://www.cibelessala.com" target="_new">www.cibelessala.com</a><br>
<div class="info">CIBELES</div>

<p></p>
<a href="http://www.confeeling.com" target="_new">www.confeeling.com</a><br>
<div class="info">FEELING</div>

<p></p>
<div class="info">laboite@masimas.com<br>LA BOITE</div>

<p></p>
<a href="http://www.pubyfiesta.com/base.php?name=pubportal&pub_id=000304" target="_new">www.pubyfiesta.com/base.php?name=pubportal&pub_id=000304</a><br>
<div class="info">LA SAL</div>

<p></p>
<a href="http://www.mondclub.com" target="_new">www.mondclub.com</a><br>
<div class="info">MOND CLUB</div>
<a href="http://www.piratasbcn.com/htdocs/index.html" target="_new">www.piratasbcn.com/htdocs/index.html</a><br>
<div class="info">PIRATA</div>

<p></p>
<a href="http://www.discotecatrauma.com" target="_new">www.discotecatrauma.com</a><br>
<div class="info">TRUAMA</div>

<p></p>
<a href="http://www.edreams.es" target="_new">www.edreams.es</a><br>
<div class="info">Grupo europeo, ofertas increibles en vuelos, viajes por todo el mundo, reservas on-line.</div>

<p></p>
<a href="http://www.viatgespanorama.com" target="_new">www.viatgespanorama.com</a><br>
<div class="info">Panorama ITC Viajes</div>

<p></p>
<a href="http://www.blaumon.es" target="_new">www.blaumon.es</a><br>
<div class="info">Blau Món Viajes</div>

<p></p>
<a href="http://www.mandala-tc.com" target="_new">www.mandala-tc.com</a><br>
<div class="info">Mandala-tc</div>

<p></p>
<a href="http://www.onix-tours.es" target="_new">www.onix-tours.es</a><br>
<div class="info">Onix Tours Agencia especialista en viajes por Europa.</div>

<p></p>
<a href="http://www.soldor.com" target="_new">www.soldor.com</a><br>
<div class="info">Viajes Sol D Especialista en viajes de incentivo y empresas.</div>

<p></p>
<a href="http://www.taranna.com" target="_new">www.taranna.com</a><br>
<div class="info">Taranna Dedicados a viajes alternativos, aventuras, expediciones.</div>

<p></p>
<a href="http://www.todocruceros.com" target="_new">www.todocruceros.com</a><br>
<div class="info">Todocruceros.com Esta agencia es especialista en viajes en cruceros.</div>

<p></p>
<a href="http://www.viatgesatlas.com" target="_new">www.viatgesatlas.com</a><br>
<div class="info">Viatges Atlas Agencia de viajes dedicada a todo tipo de trayectos.</div>

<p></p>
<a href="http://www.viajesbaixas.com" target="_new">www.viajesbaixas.com</a><br>
<div class="info">Viajes Baixas Unas de las mejores agencias especializada en viajes para la practica de Golf.</div>

<p></p>

<p></p>

<p></p>

