

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<div class="info Style10">SWITZERLAND</div>

<p></p>
<a href="http://www.salsa.ch" target="_new">www.salsa.ch</a><br>
<div class="info">El portal de la salsa en suiza.</div>

<p></p>
<a href="http://www.dansepassion.ch" target="_new">www.dansepassion.ch</a><br>
<div class="info">la primera Academia de baile Salsa en suiza</div>

<p></p>
<a href="http://www.congas.ch" target="_new">www.congas.ch</a><br>
<div class="info">Percussion afro-cubaine, ses instruments,<br>histoire de la musique et la culture cubaine.</div>

<p></p>
<a href="http://www.latino.ch" target="_new">www.latino.ch</a><br>
<div class="info">el portal latino en suiza</div>

<p></p>
<a href="http://www.salsa-switzerland.ch" target="_new">www.salsa-switzerland.ch</a><br>
<div class="info">Salsa Festival Switzerland</div>

<p></p>
<a href="http://www.solo-alexa.com" target="_new"> www.solo-alexa.com</a><br>
<div class="info">Artista dominicana de gran talento</div>

<p></p>
<a href="http://www.salsastudio.ch" target="_new">www.salsastudio.ch</a><br>
<div class="info">1er studio de salsa en switzerland</div>

<p></p>
<a href="http://www.dancing-diamonds.ch" target="_new">www.dancing-diamonds.ch</a><br>
<div class="info">Las diamantes del baile latino</div>

<p></p>
<a href="http://www.salsapictures.ch" target="_new">www.salsapictures.ch</a><br>
<div class="info">El album de todas las fiestas salsa</div>

<p></p>
<a href="http://www.tanzschuhe.ch" target="_new">www.tanzschuhe.ch</a><br>
<div class="info">Venta de zapatos de baile</div>

<p></p>
<a href="http://www.salsapeople.net" target="_new">www.tanzschuhe.ch</a><br>
<div class="info">Salsa Tanzschule in Zürich</div>

<p></p>
<a href="http://www.djelmalo.com" target="_new">www.djelmalo.com</a><br>
<div class="info">Salsa Dj</div>

<p></p>
<a href="http://www.djcochano.ch" target="_new">www.djcochano.ch</a><br>
<div class="info">Latino Dj</div>

<p></p>
<a href="http://www.djlivia.ch" target="_new">www.djlivia.ch</a><br>
<div class="info">Salsa Dj</div>

<p></p>
<a href="http://www.bauchtanz-total.ch" target="_new">www.bauchtanz-total.ch</a><br>
<div class="info">Le spectacle avec la Danseuse Du Ventre Asmhan</div>

<p></p>
<a href="http://www.cubanisima.ch" target="_new">www.cubanisima.ch</a><br>
<div class="info">La Cubanisima Records</div>

<p></p>
<a href="http://www.basel-baila.ch" target="_new">www.basel-baila.ch</a><br>
<div class="info">Basel Baila, El 1r. Festival Latino Internacional<br>es ya una historia!</div>

<p></p>
<a href="http://www.reiki-libre.ch/musique/congas/magazine.htm" target="_new">www.reiki-libre.ch/musique/congas/magazine.htm</a><br>
<div class="info">MAGAZINE . . . Salsa et  Musiques Afro Cubaine</div>

<p></p>
<a href="http://byc.ch/tangolatino" target="_new">byc.ch/tangolatino</a><br>
<div class="info">festival Tango y Latino<br>de Saint-Geniez-d'Olt en Aveyron</div>

<p></p>
<a href="http://www.salsamaniacs.org/index.htm" target="_new">www.salsamaniacs.org/index.htm</a><br>
<div class="info">le site de l'association  Salsa Maniacs de Gen?ve</div>

<p></p>
<a href="http://www.salsavirus.com" target="_new">www.salsavirus.com</a><br>
<div class="info">SalsaVirus Dance Studio Gen?ve</div>

<p></p>
<a href="http://www.salsa-pictures-suisse.ch" target="_new">www.salsa-pictures-suisse.ch</a><br>
<div class="info">Le Portail suisse de la Salsa<br>The swiss salsa portal</div>

<p></p>
<a href="http://www.lionsalsacongress.com" target="_new">www.lionsalsacongress.com</a><br>
<div class="info">Lion Salsa Congress</div>

<p></p>
<a href="http://www.salsavalais.info" target="_new">www.salsavalais.info</a><br>
<div class="info">Le portail des Danses Latines du Valais</div>

<p></p>
<a href="http://www.canadulce.ch" target="_new">www.canadulce.ch</a><br>
<div class="info">... Ambiance chaude ou les bouffées de cigares<br>
se mêlent aux rythmes endiablées de la musique latine.<br>
Caña Dulce Band</div>
