			
			
	<p>&nbsp;</p>	
	<p>&nbsp;</p>	
	<p>&nbsp;</p>	
	<p>&nbsp;</p>	
<div class="info">	COLOMBIA	</div>
	<p></p>	
	<p></p>	
<div class="info">	LINKS: PORTALES DE LA RUMBA	</div>
	<br><br>	
	<br><br>	

<br><br> <a href="http://www.mivillavo.com" target="_new">www.mivillavo.com</a><br/>		
	La web de Villavicencio y Dto del Meta	

<br><br> <a href="http://www.llanera.com" target="_new">www.llanera.com</a><br/>	
	Información cultural del llano de Colombia

<br><br> <a href="http://www.cartagenarumbera.com" target="_new">www.cartagenarumbera.com</a><br/>	
	La página de la Rumba en Cartagena

<br><br> <a href="http://www.sincelejorumbero.com" target="_new">www.sincelejorumbero.com</a><br/>	
	La red social de los costeños en Colombia

<br><br> <a href="http://www.costarumba.com" target="_new">www.costarumba.com</a><br/>	
	Para la Costa Caribe Colombiana

<br><br> <a href="http://www.farranquilla.com" target="_new">www.farranquilla.com</a><br/>	
	Toda Barranquilla de Farra..!! 

<br><br> <a href="http://www.lafarrany.com" target="_new">www.lafarrany.com</a><br/>	
	Membresía farra NY, Agenda Latina de NY

<br><br> <a href="http://www.okrumba.com" target="_new">www.okrumba.com</a><br/>	
	Guía virtual de la Rumba en Bogotá

<br><br> <a href="http://www.caliderumba.com" target="_new">www.caliderumba.com</a><br/>	
	Caliderumba, Emisora de Salsa de Cali

<br><br> <a href="http://www.calibuenanota.com" target="_new">www.calibuenanota.com</a><br/>	
	Info de Rumba-Moda-Música-Cine en Cali 

<br><br> <a href="http://www.pegateya.com" target="_new">www.pegateya.com</a><br/>	
	Tu Rumba en la web y mucho mas!

<br><br> <a href="http://www.piedecuestanos.com" target="_new">www.piedecuestanos.com</a><br/>	
	Comunidad Piedecuestana en la Internet

<br><br> <a href="http://www.samarios.com" target="_new">www.samarios.com</a><br/>	
	El Portal de Santa Marta

<br><br> <a href="http://www.radiofarra.com" target="_new">www.radiofarra.com</a><br/>	
	El Portal de Montería

<br><br> <a href="http://www.monteriadenoche.com" target="_new">www.monteriadenoche.com</a><br/>	
	Portal de Rumba de Montería y Córdoba

<br><br> <a href="http://www.rumbiaderosmedellin.com" target="_new">www.rumbiaderosmedellin.com</a><br/>	
	La rumba de la ciudad de Medellín

<br><br> <a href="http://www.rumbasdelaciudad.com" target="_new">www.rumbasdelaciudad.com</a><br/>	
	La Rumba en varias ciudades de Colombia

<br><br> <a href="http://www.entretenete.com" target="_new">www.entretenete.com</a><br/>	
	Eventos, Música, Farándula y mucho mas!

<br><br> <a href="http://www.areacucuta.com" target="_new">www.areacucuta.com</a><br/>	
	Todos los eventos del área del Cúcuta

<br><br> <a href="http://www.alairecucuta.com" target="_new">www.alairecucuta.com</a><br/>	
	Lo Mejor de la rumba en Cúcuta

<br><br> <a href="http://www.pastorumba.com" target="_new">www.pastorumba.com</a><br/>	
	Guía comercial y turística de Pasto

<br><br> <a href="http://www.enpasto.com" target="_new">www.enpasto.com</a><br/>	
	Comunidad virtual desde Pasto

<br><br> <a href="http://www.viveibague.com" target="_new">www.viveibague.com</a><br/>	
	Ibagué, La ciudad, rumba, bares y mas		

<br><br> <a href="http://www.paparazzitolima.com" target="_new">www.paparazzitolima.com</a><br/>			
	Desde El Tolima, su Rumba y mucho mas		

<br><br> <a href="http://www.madrerumba.com" target="_new">www.madrerumba.com</a><br/>			
	Portal Salsero Eje cafetero y Manizales		

<br><br> <a href="http://www.nuestrotalento.com" target="_new">www.nuestrotalento.com</a><br/>			
	Hip Hop &amp; Reggaeton 100% Colombiano		


	<br><br>		
	<br><br>		

<div class="info">	LINKS: DISCOTECAS / CLUBS	</div>	<div class="info">


<br><br> <a href="http://www.discotecaparadise.com" target="_new">www.discotecaparadise.com</a><br/>	
	Galería fotográfica de la Discoteca Paradise

<br><br> <a href="http://www.kukaramakara.com" target="_new">www.kukaramakara.com</a><br/>	
	Kukaramakara, Top Club en Medellín 

<br><br> <a href="http://www.tropicalcocktails.com.co" target="_new">www.tropicalcocktails.com.co</a><br/>	
	Líder del mercado en cocktails tipo frozen

<br><br> <a href="http://www.starsboxkaraoke.com" target="_new">www.starsboxkaraoke.com</a><br/>	
	Bar Star's Karaoke Show

<br><br> <a href="http://www.discotecacharlesdegaulle.com" target="_new">www.discotecacharlesdegaulle.com</a><br/>	
	Música en vivo, Francia en Medellín

<br><br> <a href="http://www.discotecasalsalenaverde.com" target="_new">www.discotecasalsalenaverde.com</a><br/>			
	La mejor rumba de Perira		

<br><br> <a href="http://www.discotecamangos.com" target="_new">www.discotecamangos.com</a><br/>			
	Mangos: colorido, bailarinas y shows		

	<br><br>		
	<br><br>		


<div class="info">	LINKS: RESTAURANTES	</div>	<div class="info">

<br><br> <a href="http://www.cabanadelsheriff.com" target="_new">www.cabanadelsheriff.com</a><br/>			
	Cabaña del Shriff, a la llanera con Música		

<br><br> <a href="http://www.elmarquezdecasablanca.com" target="_new">www.elmarquezdecasablanca.com</a><br/>	
	Finísimo restaurante con concepto español

<br><br> <a href="http://www.morrilloparrillabar.com" target="_new">www.morrilloparrillabar.com</a><br/>	
	Morrillo: parrillada y Música en vivo

<br><br> <a href="http://www.labarracarestaurante.com" target="_new">www.labarracarestaurante.com</a><br/>	
	La Barraca: Show en vivo y floclor

<br><br> <a href="http://www.yaztabar.com" target="_new">www.yaztabar.com</a><br/>	
	Yazta: Música en vivo y comida, Bogotá

<br><br> <a href="http://www.laleyendabar.net" target="_new">www.laleyendabar.net</a><br/>	
	La Leyenda: Rumba, comida y tradición

<br><br> <a href="http://www.tekilabar.com" target="_new">www.tekilabar.com</a><br/>	
	Tekila Bar: El ambiente mexicano, Bogotá		

	<br><br>		
	<br><br>		


<div class="info">	LINKS: FERIAS Y FESTIVIDADES	</div>	<div class="info">


<br><br> <a href="http://www.carnavaldepasto.org" target="_new">www.carnavaldepasto.org</a><br/>			
	Carnaval de Negros y Blancos de Pasto		

<br><br> <a href="http://www.feriademanizales.com.co" target="_new">www.feriademanizales.com.co</a><br/>			
	Turismo de Manizales y Pereira entre otros		

<br><br> <a href="http://www.hayfestival.com" target="_new">www.hayfestival.com</a><br/>			
	Hay Festival en Cartagena de Indias

<br><br> <a href="http://www.carnavaldebarranquilla.com" target="_new">www.carnavaldebarranquilla.com</a><br/>	
	Web del Carnaval anual de Barranquilla

<br><br> <a href="http://www.festicinecartagena.org" target="_new">www.festicinecartagena.org</a><br/>	
	Festival de cine y TV, Cartagena

<br><br> <a href="http://www.festivaldeteatro.com.co" target="_new">www.festivaldeteatro.com.co</a><br/>	
	Festival Iberoamericano de Teatro, Bogotá

<br><br> <a href="http://www.juntasemanasantapopayan.org" target="_new">www.juntasemanasantapopayan.org</a><br/>	
	La Semana Santa en Popayán

<br><br> <a href="http://santacruzdemompox.spaces.live.com" target="_new">santacruzdemompox.spaces.live.com</a><br/>	
	La Unica Semana Santa Marchada !!

<br><br> <a href="http://www.festivalvallenato.com" target="_new">www.festivalvallenato.com</a><br/>	
	Web del Festival de La Leyenda Vallenata

<br><br> <a href="http://www.feriadellibro.com" target="_new">www.feriadellibro.com</a><br/>	
	La Feria Internacional del Libro, Bogotá

<br><br> <a href="http://www.festivalfolclorico.com" target="_new">www.festivalfolclorico.com</a><br/>	
	Festival folclórico, Tolima e Ibagué

<br><br> <a href="http://www.neivamigos.com" target="_new">www.neivamigos.com</a><br/>	
	Neivamigos, somos tu punto de encuentro

<br><br> <a href="http://www.calarca.net" target="_new">www.calarca.net</a><br/>	
	Completa información sobre Calarcá, Quindío

<br><br> <a href="http://www.ginebra-valle.gov.co" target="_new">www.ginebra-valle.gov.co</a><br/>	
	Contratación, noticias y eventos del Valle

<br><br> <a href="http://www.inexmoda.org.co" target="_new">www.inexmoda.org.co</a><br/>	
	La web de Colombiamoda

<br><br> <a href="http://www.feriadelasfloresmedellin.gov.co" target="_new">www.feriadelasfloresmedellin.gov.co</a><br/>	
	La Feria de las Flores, Medellín

<br><br> <a href="http://www.villadeleyva.net" target="_new">www.villadeleyva.net</a><br/>	
	Hoteles Casas Campestres Finca Raiz, Guía

<br><br> <a href="http://www.sanpacho.com" target="_new">www.sanpacho.com</a><br/>	
	Fiestas de San Francisco de Asís en Quibdó

<br><br> <a href="http://www.mundialcoleo.com.co" target="_new">www.mundialcoleo.com.co</a><br/>	
	Tradición de llaneros de Colombia y Venezuela

<br><br> <a href="http://www.srtacolombia.org" target="_new">www.srtacolombia.org</a><br/>	
	Concurso Nacional de belleza de Colombia

<br><br> <a href="http://www.feriadecali.com" target="_new">www.feriadecali.com</a><br/>	
	Subite a la Chiva!! Feria de Cali 2008

<br><br> <a href="http://www.underground.com.co" target="_new">www.underground.com.co</a><br/>	
	Undergroung Megaeventos en Colombia


	<br><br>
	<br><br>


<div class="info">	LINKS: PROMO DE ESPECTACULOS	</div>	<div class="info">


<br><br> <a href="http://www.bravoshow.com" target="_new">www.bravoshow.com</a><br/>			
	BravoShow La Experiencia en Vivo		

<br><br> <a href="http://www.rodeblamproducciones.com" target="_new">www.rodeblamproducciones.com</a><br/>			
	Rodeblam: Top promotores de evntos		

<br><br> <a href="http://www.alseventos.com" target="_new">www.alseventos.com</a><br/>			
	Conciertos, nacional e internacionales		

<br><br> <a href="http://www.konklase.com" target="_new">www.konklase.com</a><br/>			
	Desde El Reggaeton hasta El Merengue		

	<br><br>		
	<br><br>		

<div class="info">	LINKS: LOS TOP DJS 	</div>	<div class="info">

<br><br> <a href="http://www.deejaypopemix.tk" target="_new">www.deejaypopemix.tk</a><br/>			
	DJ Pope 12 largos años de profesionalimo		

<br><br> <a href="http://djpopemix.blogspot.com" target="_new">djpopemix.blogspot.com</a><br/>			
	DJ POPE.... MIXES &amp; REMIXES 2008		

<br><br> <a href="http://jcvargas.es.tl" target="_new">jcvargas.es.tl</a>			
	J C Vargas, top DJ del Crossover		

<br><br> <a href="http://jhonvasquezdj.blogspot.com" target="_new">jhonvasquezdj.blogspot.com</a><br/>			
	Jhon Vasquez: top DJ del Crossover		

<br><br> <a href="http://miguelvargasdj.es.tl" target="_new">miguelvargasdj.es.tl</a>	
	Miguel Vargas: Top DJ Internacional

<br><br> <a href="http://musicaremix.com/index.php" target="_new">musicaremix.com</a><br/>	
	Listado de Top Djs,remixes y mucho mas!

<br><br> <a href="http://www.deejayjohnbarrera.es.tl" target="_new">www.deejayjohnbarrera.es.tl</a><br/>	
	De Neiva y para el mundo DJ John Barrera

<br><br> <a href="http://www.djfabianremix2008.es.tl" target="_new">www.djfabianremix2008.es.tl</a><br/>	
	Los Remix del talentoso DJ Fabián

<br><br> <a href="http://www.djmarioandretti.com" target="_new">www.djmarioandretti.com</a><br/>	
	DJ Mario Andretti: El Original.......

<br><br> <a href="http://www.edwin-dj.es.tl" target="_new">www.edwin-dj.es.tl</a><br/>	
	DJ Edwin: Top fusión Vallenato-reggaeton

<br><br> <a href="http://www.henryaya.tk" target="_new">www.henryaya.tk</a><br/>	
	Henry: DJ-VDJ el mejor del sur del país

<br><br> <a href="http://leocasas666.es.tl" target="_new">leocasas666.es.tl</a>	
	DJ Leo: Haciendo mover tu cuerpo

<br><br> <a href="http://www.migueldj.es.tl" target="_new">www.migueldj.es.tl</a><br/>	
	DJ Miguel, el mejor DJ Crossover!!!

<br><br> <a href="http://www.myspace.com/masterdjmchavess" target="_new">www.myspace.com/masterdjmchavess</a><br/>	
	Link a Master DJ Mauricio Chavess

<br><br> <a href="http://www.supermezclas.com" target="_new">www.supermezclas.com</a><br/>	
	La página oficial de los mejores DJs!

<br><br> <a href="http://www.djtedu.com" target="_new">www.djtedu.com</a><br/>	
	Dj Tedu: Supercampeón internacional

<br><br> <a href="http://www.djvampireg.com" target="_new">www.djvampireg.com</a><br/>	
	Vampire G: Top DJ de Bogotá

<br><br> <a href="http://www.josediazdj.com" target="_new">www.josediazdj.com</a><br/>	
	José Días: Top House Music DJ

<br><br> <a href="http://www.proyectodedjs.com" target="_new">www.proyectodedjs.com</a><br/>	
	Web de los productores y DJ Latinos

<br><br> <a href="http://www.rolydj.com" target="_new">www.rolydj.com</a><br/>	
	Roly: Radio&amp;Music DJ de Barranquilla

<br><br> <a href="http://www.willyflechas.net" target="_new">www.willyflechas.net</a><br/>	
	DJ Willy: Top DJ internacional

<br><br> <a href="http://www.djfranzmoreno.es.tl" target="_new">www.djfranzmoreno.es.tl</a><br/>	
	Franz: Top Latin DJ de Bogotá
<br><br>			
<br><br>			
			
