
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<div class="info">ITALIA</div>

<p></p>
<p></p>
<p></p>
<a href="http://www.salsa.it" target="_new">www.salsa.it</a><br>
<div class="info">Locali e serate su salsa in Italia</div>

<p></p>
<a href="http://salsa.gensoft.it" target="_new">salsa.gensoft.it</a><br>
<div class="info">Riferimento delle danze Latino Americane.</div>

<p></p>
<a href="http://www.salsaschool.it" target="_new">www.salsaschool.it</a><br>
<div class="info">Corsi di salsa</div>

<p></p>
<a href="http://www.romasalsaschool.it" target="_new">www.romasalsaschool.it</a><br>
<div class="info">Scuola di ballo</div>

<p></p>
<a href="http://www.salsanapoli.it" target="_new">www.salsanapoli.it</a><br>
<div class="info">Salsa y cultura latina</div>

<p></p>
<a href="http://www.ballilatini.it" target="_new">www.ballilatini.it</a><br>
<div class="info">Locali, serate ed eventi latini</div>

<p></p>
<a href="http://www.salsavacanze.it" target="_new">www.salsavacanze.it</a><br>
<div class="info">Eventi della musica latinoamericana</div>

<p></p>
<a href="http://www.salsasocialclub.com" target="_new">www.salsasocialclub.com</a><br>
<div class="info">Webzine sulla salsa e ritmi latini</div>

<p></p>
<a href="http://www.salsamania.it" target="_new">www.salsamania.it</a><br>
<div class="info">Portale multimediale della salsa</div>

<p></p>
<a href="http://www.pinolagioia.it" target="_new">www.pinolagioia.it</a><br>
<div class="info">Salsa, bachata, merengue, rueda e balli di grupo</div>

<p></p>
<a href="http://www.salsabrava.it" target="_new">www.salsabrava.it</a><br>
<div class="info">Accademia di ballo</div>

<p></p>
<a href="http://www.loszaquanos.it" target="_new">www.loszaquanos.it</a><br>
<div class="info">Salsa e musica latina</div>

<p></p>
<a href="http://www.meetinglatino.it" target="_new">www.meetinglatino.it</a><br>
<div class="info">Salsa e mondo latino</div>

<p></p>
<a href="http://www.ventanaalcaribe.it" target="_new">www.ventanaalcaribe.it</a><br>
<div class="info">Balli tropicali: corsi</div>

<p></p>
<a href="http://www.perugiasalsa.it" target="_new">www.perugiasalsa.it</a><br>
<div class="info">Musica salsa</div>

<p></p>
<a href="http://www.aboutsalsa.it" target="_new">www.aboutsalsa.it</a><br>
<div class="info">Portale di salsa e musica caraibica</div>

<p></p>
<a href="http://www.salsamambo.it" target="_new">www.salsamambo.it</a><br>
<div class="info">Scuola di salsa</div>

<p></p>
<a href="http://www.tropicalsalsa.it" target="_new">www.tropicalsalsa.it</a><br>
<div class="info">Serate di salsa</div>

<p></p>
<a href="http://digilander.libero.it/salsape/salsa_peHome.htm" target="_new">digilander.libero.it/salsape/salsa_peHome.htm</a><br>
<div class="info">Locali di salsa</div>

<p></p>
<a href="http://www.astempolibero.135.it" target="_new">www.astempolibero.135.it</a><br>
<div class="info">Corsi di salsa</div>

<p></p>
<a href="http://www.almasalsera.it" target="_new">www.almasalsera.it</a><br>
<div class="info">Corsi di balli</div>

<p></p>
<a href="http://www.ritmotropicale.it" target="_new">www.ritmotropicale.it</a><br>
<div class="info">Corsi di balli latini</div>

<p></p>
<a href="http://www.ilcafelatino.it" target="_new">www.ilcafelatino.it</a><br>
<div class="info">Corsi di balli latini</div>

<p></p>
<a href="http://scuoladisalsa.it" target="_new">scuoladisalsa.it</a><br>
<div class="info">Scuola di Anna &amp; Carlo</div>

<p></p>
<a href="http://djsilviosisto.it" target="_new">djsilviosisto.it</a><br>
<div class="info">Eventi latini</div>

<p></p>
<a href="http://www.salsaconclase.it" target="_new">www.salsaconclase.it</a><br>
<div class="info">Corsi di salsa</div>

<p></p>
<a href="http://www.salsasulserio.it" target="_new">www.salsasulserio.it</a><br>
<div class="info">Scuola di balli latini</div>

<p></p>
<a href="http://www.ivanamaldonado.it" target="_new">www.ivanamaldonado.it</a><br>
<div class="info">Scuola di salsa</div>

<p></p>
<a href="http://www.mamadance.it" target="_new">www.mamadance.it</a><br>
<div class="info">Scuola di ballo</div>

<p></p>
<a href="http://www.sangrelatina.it" target="_new">www.sangrelatina.it</a><br>
<div class="info">Scuola di ballo</div>

<p></p>
<a href="http://www.salsatiberina.it" target="_new">www.salsatiberina.it</a><br>
<div class="info">Eventi e serate latine</div>

<p></p>
<a href="http://www.latinplanet.it" target="_new">www.latinplanet.it</a><br>
<div class="info">Corsi di salsa cubana e portoricana</div>

<p></p>
<a href="http://www.salsalocateam.it" target="_new">www.salsalocateam.it</a><br>
<div class="info">Corsi di ballo e serate latinoamericane</div>

<p></p>

<p></p>
<a href="http://www.ballaconnoi.it" target="_new">www.ballaconnoi.it</a><br>
<div class="info">Musica latina</div>

<p></p>
<a href="http://www.salsaamimanera.it" target="_new">www.salsaamimanera.it</a><br>
<div class="info">Scuola di salsa</div>

<p></p>
<a href="http://www.danzesportsardegna.it" target="_new">www.danzesportsardegna.it</a><br>
<div class="info">Essibizioni e gare di balli dei Caraibi</div>

<p></p>
<a href="http://www.michelasalsalight.it" target="_new">www.michelasalsalight.it</a><br>
<div class="info">Corsi di balli latini</div>

<p></p>
<a href="http://www.danza.it" target="_new">www.danza.it</a><br>
<div class="info">Magazine delle scuole di ballo</div>

<p></p>
<a href="http://www.academycdance.it" target="_new">www.academycdance.it</a><br>
<div class="info">Corsi di salsa</div>

<p></p>
<a href="http://www.salsaverde.it" target="_new">www.salsaverde.it</a><br>
<div class="info">Info salsa y latinoamericana</div>

<p></p>
<a href="http://www.tuttoilweb.it" target="_new">www.tuttoilweb.it</a><br>
<div class="info">Scuola di salsa</div>

<p></p>
<a href="http://www.lluvia.it" target="_new">www.lluvia.it</a><br>
<div class="info">Scuola di ballo cubano e latini</div>

<p></p>
<a href="http://www.cagliarinochelatina.it" target="_new">www.cagliarinochelatina.it</a><br>
<div class="info">Musica e cultura latina</div>

<p></p>
<a href="http://www.havanadisco.it" target="_new">www.havanadisco.it</a><br>
<div class="info">Musica caraibica e balli di grupo</div>

<p></p>
<a href="http://web.tiscali.it/homepassionelatina" target="_new">web.tiscali.it/homepassionelatina</a><br>
<div class="info">Lezioni di salsa</div>

<p></p>
<a href="http://www.7caliente.com" target="_new">www.7caliente.com</a><br>
<div class="info">Attività latina</div>

<p></p>
<a href="http://www.7scuolediballo.com" target="_new">www.7scuolediballo.com</a><br>
<div class="info">Scuole di ballo</div>

<p></p>
<a href="http://www.bluecaribe.it" target="_new">www.bluecaribe.it</a><br>
<div class="info">Associazione di balli caraibici</div>

<p></p>
<a href="http://www.escuelaloca.it" target="_new">www.escuelaloca.it</a><br>
<div class="info">Corsi di salsa</div>

<p></p>
<a href="http://www.salsaromaclub.it" target="_new">www.salsaromaclub.it</a><br>
<div class="info">Organizzazione web della salsa</div>

<p></p>
<a href="http://www.salsasicilia.com" target="_new">www.salsasicilia.com</a><br>
<div class="info">Portale latino</div>

<p></p>
<a href="http://www.sampaoli.com" target="_new">www.sampaoli.com</a><br>
<div class="info">Corsi di salsa</div>

<p></p>
<a href="http://www.fuegolatino.it" target="_new">www.fuegolatino.it</a><br>
<div class="info">Serate latine</div>

<p></p>
<a href="http://www.suenolatino.it" target="_new">www.suenolatino.it</a><br>
<div class="info">Eventi di salsa</div>

<p></p>
<a href="http://www.ravennainsalsa.it" target="_new">www.ravennainsalsa.it</a><br>
<div class="info">Scuola e locali di salsa</div>

<p></p>
<a href="http://www.ondatropical.it" target="_new">www.ondatropical.it</a><br>
<div class="info">Oferta di musica latina</div>

<p></p>
<a href="http://www.filolatino.it" target="_new">www.filolatino.it</a><br>
<div class="info">Cultura latina</div>

<p></p>
<a href="http://www.mambolatino.it" target="_new">www.mambolatino.it</a><br>
<div class="info">Scuola di balli latini</div>

<p></p>
<a href="http://marlongiuri.it/caraibiche.html" target="_new">marlongiuri.it/caraibiche.html</a><br>
<div class="info">Corsi di danze caraibiche</div>

<p></p>
<a href="http://www.estudiosalsa.it" target="_new">www.estudiosalsa.it</a><br>
<div class="info">Corsi di salsa</div>

<p></p>
<a href="http://www.kidojo.it/salsa_merengue" target="_new">www.kidojo.it/salsa_merengue</a><br>
<div class="info">Corso di salsa per principianti</div>

<p></p>
<a href="http://www.savanas.it" target="_new">www.savanas.it</a><br>
<div class="info">Serate latine</div>

<p></p>
<a href="http://www.salsamundo.it" target="_new">www.salsamundo.it</a><br>
<div class="info">Lezioni di ballo</div>

<p></p>
<a href="http://www.crazygroup.it" target="_new">www.crazygroup.it</a><br>
<div class="info">Salsa, locali, eventi</div>

<p></p>
<a href="http://www.fueradeliga.it" target="_new">www.fueradeliga.it</a><br>
<div class="info">Locali di musica latina</div>
<a href="http://www.palacavicchi.it" target="_new">www.palacavicchi.it</a><br>
<div class="info">Discoteca di musica latina</div>

<p></p>
<a href="http://www.romasalsaworldfestival.com" target="_new">www.romasalsaworldfestival.com</a><br>
<div class="info">Festival di salsa</div>

<p></p>
<a href="http://www.salsaonline.it" target="_new">www.salsaonline.it</a><br>
<div class="info">Serate  e corsi di ballo</div>

<p></p>
<a href="http://www.festivaleolatino.it" target="_new">www.festivaleolatino.it</a><br>
<div class="info">Programme di musica latina</div>

<p></p>
<a href="http://www.salsadimension.it" target="_new">www.salsadimension.it</a><br>
<div class="info">Corsi di salsa</div>

<p></p>
<a href="http://www-utenti.dsc.unibo.it/~cesari/ig/index.html" target="_new">www-utenti.dsc.unibo.it/~cesari/ig/index.html</a><br>
<div class="info">Origini della salsa</div>

<p></p>
<a href="http://www.elpuma.it" target="_new">www.elpuma.it</a><br>
<div class="info">Cantante di musica latina</div>

<p></p>
<a href="http://www.tropicalgem.it" target="_new">www.tropicalgem.it</a><br>
<div class="info">Scuola di danza</div>

<p></p>
<a href="http://www.congaplace.com" target="_new">www.congaplace.com</a><br>
<div class="info">La conga</div>

<p></p>
<a href="http://www.corazonbarese.it" target="_new">www.corazonbarese.it</a><br>
<div class="info">Portale salsero in Puglia</div>

<p></p>
<a href="http://www.discolatino.com" target="_new">www.discolatino.com</a><br>
<div class="info">Musica latina</div>

<p></p>
<a href="http://www.cubabaila.net" target="_new">www.cubabaila.net</a><br>
<div class="info">Scuola di Alberto Valdés</div>

<p></p>
<a href="http://www.salsasocialclub.com" target="_new">www.salsasocialclub.com</a><br>
<div class="info">Locali di ballo</div>

<p></p>
<a href="http://www.bianconerolatino.it" target="_new">www.bianconerolatino.it</a><br>
<div class="info">Serate latine e scuola di ballo</div>

<p></p>
<a href="http://www.queritmo.it" target="_new">www.queritmo.it</a><br>
<div class="info">Latin webradio</div>

<p></p>
<a href="http://www.todavidagroup.it" target="_new">www.todavidagroup.it</a><br>
<div class="info">Serate latine</div>

<p></p>
<a href="http://www.boogaloo.it/default15.asp" target="_new">www.boogaloo.it/default15.asp</a><br>
<div class="info">Gruppo di musica latina</div>

<p></p>

<p></p>
<a href="http://www.levantelatino.it" target="_new">www.levantelatino.it</a><br>
<div class="info">Corsi e serate latine</div>

<p></p>
<a href="http://www.grupocaribe.it" target="_new">www.grupocaribe.it</a><br>
<div class="info">Programma di serate latine</div>

<p></p>
<a href="http://www.crazysalsa.it" target="_new">www.crazysalsa.it</a><br>
<div class="info">Serate e corsi di salsa</div>

<p></p>
<a href="http://www.salsastyle.it/index1.htm" target="_new">www.salsastyle.it/index1.htm</a><br>
<div class="info">Corsi di salsa</div>

<p></p>
<a href="http://www.portbahia.it" target="_new">www.portbahia.it</a><br>
<div class="info">Scuola di danza</div>

<p></p>
<a href="http://www.danielson.it" target="_new">www.danielson.it</a><br>
<div class="info">Corsi di salsa</div>

<p></p>
<a href="http://www.salsajazz.it" target="_new">www.salsajazz.it</a><br>
<div class="info">Corsi di salsa</div>

<p></p>
<a href="http://www.salsayritmocaliente.com" target="_new">www.salsayritmocaliente.com</a><br>
<div class="info">Corsi di salsa</div>

<p></p>
<a href="http://www.bintmusic.it" target="_new">www.bintmusic.it</a><br>
<div class="info">Risorse su artisti e musica latina</div>

<p></p>
<a href="http://www.rizzidj.it" target="_new">www.rizzidj.it</a><br>
<div class="info">Serate latine</div>

<p></p>
<a href="http://www.danceforfun.it" target="_new">www.danceforfun.it</a><br>
<div class="info">Scuola di ballo</div>

<p></p>
<a href="http://www.danzaymovimiento.it" target="_new">www.danzaymovimiento.it</a><br>
<div class="info">Il medico della salsa</div>

<p></p>
<a href="http://www.maxballetacademy.it" target="_new">www.maxballetacademy.it</a><br>
<div class="info">Scuola di arte e spettacolo</div>

<p></p>
<a href="http://www.distritolatino.it" target="_new">www.distritolatino.it</a><br>
<div class="info">Portale salsero distrito latino</div>

<p></p>
<a href="http://www.darklatindance.it" target="_new">www.darklatindance.it</a><br>
<div class="info">Scuola di danza</div>

<p></p>
<a href="http://nuke.salsaysabor.it/Eventidanonperdere/SalsaconGusto200612aprile2006/tabid/85/Default.aspx" target="_new">nuke.salsaysabor.it/Eventidanonperdere/SalsaconGusto200612aprile2006/tabid/85/Default.aspx</a><br>
<div class="info">Animazioni e spectacoli</div>

<p></p>
<a href="http://www.mamanu.it" target="_new">www.mamanu.it</a><br>
<div class="info">Mamanu</div>

<p></p>
