			
			
	<p>&nbsp;</p>		
	<p>&nbsp;</p>		
	<p>&nbsp;</p>		
	<p>&nbsp;</p>		
			
<div class="info">	FRANCIA LATINA	</div>	<div class="info">
	<br><br>		
	<br><br>		
	<br><br>		
			
			
			
<div class="info">	PORTAL LATINO DE FRANCIA	</div>	<div class="info">
	<br><br>		
	<br><br>		
	<br><br>		
			
			
			
<br><br> <a href="http://www.fra.cityvox.fr/restaurants_avignon/bodeguita-cubana_200060126/ProfilLieu	 " target="_new">liens:	
	La Bodeguita Cubana Bienvenidos a La Habana<br>		
	Restaurante cubano con fiestas de Salsa		
	<br><br>		
<br><br> <a href="http://www.fra.cityvox.fr/restaurants_avignon/bodeguita-cubana_200060126/ProfilLieu	 " target="_new">liens:	
	Bodeguita Cubana Bienvenue à la Havane Ce<br>		
	restaurant cubain est un lieu accueillant 		
	<br><br>		
<br><br> <a href="http://www.el-arbol.com" target="_new">liens:	
	Découvrez l'Amérique!		
	<br><br>		
<br><br> <a href="http://www.la-calaca.com" target="_new">liens:	
	La musique précolombienne mexicaine 		
	<br><br>		
<br><br> <a href="http://www.putumayo.com" target="_new">liens:	
	PUTUMAYO Label dédié à la world musique		
	<br><br>		
<br><br> <a href="http://www.comnact.com" target="_new">liens:	
	Vous recherchez un artiste ? <br>
Vous êtes artiste ?		
	<br><br>		
<br><br> <a href="http://www.bigbone.fr" target="_new">liens:	
	BIGBONE Etude Gestion réalisation <br>
de Projets sonores		
	<br><br>		
<br><br> <a href="http://www.mexique-voyage.com" target="_new">liens:	
	MEXIQUE VOYAGE Carnet de voyage 		
	<br><br>		
<br><br> <a href="http://www.salsasud.com" target="_new">liens:	
	le site et forum de la salsa <br>
dans le sud de la France		
	<br><br>		
<br><br> <a href="http://www.salsa-sud.fr" target="_new">liens:	
	salsa-sud toute la danse salsa à montpellier 		
	<br><br>		
<br><br> <a href="http://www.salsamontpellier.com" target="_new">liens:	
	Salsa à Montpellier 		
	<br><br>		
<br><br> <a href="http://www.habamas.net" target="_new">liens:	
	c'est le site du Trio Habamas !!		
	<br><br>		
<br><br> <a href="http://www.diabloson.com" target="_new">liens:	
	une formation latino américaine de salsa		
	<br><br>		
<br><br> <a href="http://www.buscasalsa.com" target="_new">liens:	
	Site consacré à la Salsa 		
	<br><br>		
<br><br> <a href="http://www.huronazul.com" target="_new">liens:	
	El Restaurante Paladar Huron Azul, en La Habana		
	<br><br>		
<br><br> <a href="http://www.afrolatino.net" target="_new">liens:	
	Propose des informations sur <br>
les événements en France de Salsa		
	<br><br>		
<br><br> <a href="http://salsamigos.free.fr/" target="_new">liens:	
	c'est le site du l'équipe Salsamigos		
	<br><br>		
<br><br> <a href="http://www.salsafada.com" target="_new">liens:	
	Salsafada Organisation d'activités diverses 		
	<br><br>		
<br><br> <a href="http://www.salsaconga.com" target="_new">liens:	
	Ecole de Salsa, Cours de salsa, Spectacles		
	<br><br>		
<br><br> <a href="http://www.danse-a-2.com/" target="_new">liens:	
	toutes les Danses de Couple		
	<br><br>		
<br><br> <a href="http://www.freddanses.com" target="_new">liens:	
	ecole de danse stage et cours à Montpellier 		
	<br><br>		
<br><br> <a href="http://www.swingcatcie.com" target="_new">liens:	
	cours de danse swing salsa à montpellier 		
	<br><br>		
<br><br> <a href="http://www.noomba-sport.com" target="_new">liens:	
	Ecole de Salsa à MONTPELLIER		
	<br><br>		
<br><br> <a href="http://www.karibe1.com" target="_new">liens:	
	karibe1 Dance Studio à montpellier		
	<br><br>		
<br><br> <a href="http://www.apollojazzcafe.com" target="_new">liens:	
	L’incontourable Bar Dansant <br>
et Restaurant de Montpellier		
	<br><br>		
<br><br> <a href="http://www.cotton-club-montpellier.com" target="_new">liens:	
	COTTON CLUB, Le Club musical et le plus raffiné de Montpellier 		
	<br><br>		
<br><br> <a href="http://www.havananight.fr" target="_new">liens:	
	Le bar salsa de Montpellier 		
	<br><br>		
<br><br> <a href="http://culturesalsa.free.fr" target="_new">liens:	
	cours et stages de salsa à Montpellier		
	<br><br>		
<br><br> <a href="http://www.studio-latino.com" target="_new">liens:	
	Studio Latino, école de danses latinos		
	<br><br>		
<br><br> <a href="http://www.latinoaldia.com" target="_new">liens:	
	le site internet de la revue latino america		
	<br><br>		
<br><br> <a href="http://www.assocol.com" target="_new">liens:	
	La Asociación de la Colonia Colombiana en Francia		
	<br><br>		
<br><br> <a href="http://www.humanas.unal.edu.co/acolprof/" target="_new">liens:	
	Association Colombienne des Professeurs de Français		
	<br><br>		
<br><br> <a href="http://uniframex.com" target="_new">liens:	
	UNIFRAMEX Union Franco Mexicaine		
	<br><br>		
<br><br> <a href="http://www.mexique-voyage.com" target="_new">liens:	
	Association TEQUILA-MARTEL		
	<br><br>		
<br><br> <a href="http://www.acfm.net" target="_new">liens:	
	Association des cultures Franco - Mexicaines		
	<br><br>		
<br><br> <a href="http://www.uniframex.com" target="_new">liens:	
	Promotion de l’image et l’authenticité mexicaine		
	<br><br>		
<br><br> <a href="http://www.geocities.com/mextlse/index3.html" target="_new">liens:	
	Asociacion de Estudiantes Mexicanos en Toulouse		
	<br><br>		
<br><br> <a href="http://www.colcrea.org" target="_new">liens:	
	estudiantes, creadores y latinoamericanos en Francia		
	<br><br>		
<br><br> <a href="http://www.brasil.fr" target="_new">liens:	
	Le Portail du Brasil en France		
	<br><br>		
<br><br> <a href="http://www.bonjourbrasil.com" target="_new">liens:	
	Bonjour Brasil ! portail culturel du Brésil en France		
	<br><br>		
<br><br> <a href="http://www.france-cuba.fr" target="_new">liens:	
	une association solidaire du peuple cubain 		
	<br><br>		
<br><br> <a href="http://francecubanormandie.free.fr" target="_new">liens:	
	comité France Cuba Normandie		
	<br><br>		
<br><br> <a href="http://www.elachedecuba.com" target="_new">liens:	
	Café Concert du Plateau, salsa, jazz...		
	<br><br>		
<br><br> <a href="http://www.cubailacafe.fr" target="_new">liens:	
	Le Cubaïla Café - Restaurant Cubain Marseille		
	<br><br>		
<br><br> <a href="http://marquiseclub.free.fr" target="_new">liens:	
	Discothèque La Marquise a Lyon		
	<br><br>		
<br><br> <a href="http://www.salsaclub.tv" target="_new">liens:	
	Musiamerica* Salsa Club (Lyon) 		
	<br><br>		
<br><br> <a href="http://www.salsaconga.com" target="_new">liens:	
	SALSA CONGA, Ecole de Salsa, <br>
Cours de salsa, Spectacles		
	<br><br>		
<br><br> <a href="http://www.buscasalsa.com" target="_new">liens:	
	Cours de Salsa et Bachata à Toulon 		
	<br><br>		
<br><br> <a href="http://www.newstylesalsa.com" target="_new">liens:	
	Ecole de danse, Draguignan		
	<br><br>		
<br><br> <a href="http://www.salsacaliente.fr" target="_new">liens:	
	la salsa sur région cote d'azur.		
	<br><br>		
<br><br> <a href="http://www.thieritomambo.com" target="_new">liens:	
	Salsa sur la Cote D'Azur France avec Thierito 		
	<br><br>		
<br><br> <a href="http://casadelasalsa.free.fr" target="_new">liens:	
	La casa de la Salsa		
	<br><br>		
<br><br> <a href="http://salsatools.com" target="_new">liens:	
	Salsa Tools, pour vocation de <br>
vous faire découvrir la Salsa		
	<br><br>		
<br><br> <a href="http://carlos.m.hernandez.free.fr" target="_new">liens:	
	Carlos Hernández, chanteur de Bolero		
	<br><br>		
<br><br> <a href="http://commeilvousplaira.free.fr" target="_new">liens:	
	Culture, musique et valeurs solidaires		
	<br><br>		
<br><br> <a href="http://salsanuestra.free.fr" target="_new">liens:	
	Salsa nuestra, Cours de Salsa cubaine		
	<br><br>		
<br><br> <a href="http://www.ritmoscubanos.fr" target="_new">liens:	
	Ritmos cubanos,Solidarité en faveur d'enfants cubains		
	<br><br>		
<br><br> <a href="http://www.lapachanga.fr" target="_new">liens:	
	La Pachangs, Vous y passerez une soirée inoubliable !!!		
	<br><br>		
<br><br> <a href="http://www.latina.fr" target="_new">liens:	
	Radio Latina hot 99FM		
	<br><br>		
<br><br> <a href="http://salsaddict.free.fr" target="_new">liens:	
	Salsaddict, Les accros de la salsa nantaise		
	<br><br>		
<br><br> <a href="http://aquicuba.free.fr" target="_new">liens:	
	Aqui Cuba Festival de Salsa Cubaine		
	<br><br>		
<br><br> <a href="http://www.salsamegusta.fr" target="_new">liens:	
	site de l’association Salsa Me Gusta 		
	<br><br>		
<br><br> <a href="http://essaswing.com" target="_new">liens:	
	Site de danse en couple, Salsa!		
	<br><br>		
<br><br> <a href="http://www.candelamison.com" target="_new">liens:	
	Candela mi Son,une envie irresistible de danser.		
	<br><br>		
<br><br> <a href="http://salsaloca.free.fr" target="_new">liens:	
	Salsaloca, L'essentiel de la salsa, actualité latino		
	<br><br>		
<br><br> <a href="http://www.pmfsalsa.com" target="_new">liens:	
	Escuela de Salsa Cubana		
	<br><br>		
<br><br> <a href="http://fiestacubana.net" target="_new">liens:	
	Fiesta cubana,le portail <br>
de la Salsa cubaine en France 		
	<br><br>		
<br><br> <a href="http://www.soy-salsero.com" target="_new">liens:	
	Soy salsero,Accueil Blog Espace Musiciens		
	<br><br>		
<br><br> <a href="http://juanito.dansescubaines.over-blog.com" target="_new">liens:	
	Juanito,Professeur de danse Yoruba et Rumba		
	<br><br>		
<br><br> <a href="http://okilakua.free.fr" target="_new">liens:	
	Okilakua, Manos poderosas, Folklore cubain		
	<br><br>		
<br><br> <a href="http://afincao.free.fr" target="_new">liens:	
	Afincao, toute la saveur des Rythmes Afro-Cubains		
	<br><br>		
<br><br> <a href="http://www.tempo-latino.com" target="_new">liens:	
	Festival Tempo Latino		
	<br><br>		
<br><br> <a href="http://www.palaciodelasalsa.fr" target="_new">liens:	
	El Palacio de la Salsa, restaurant-bar musical cubain		
			
	<br><br>		
	<br><br>		
	<br><br>		
