
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<div class="info">RUSSIA</div>

<p></p>

<p></p>

<p></p>

<p></p>
<a href="http://www.karma-bar.ru/club.htm" target="_new">www.karma-bar.ru/club.htm</a><br>
<div class="info">Currently this is the most popular salsa <br>
  discotheque in Moscow.</div>

<p></p>
<a href="http://www.panchovilla.ru/site/index.html" target="_new">www.panchovilla.ru/site/index.html</a><br>
<div class="info">This is just a Mexican restaurant, but <br>
  salseros are welcome. Live Latin <br>
  (not Mexican) music. Small dance floor, </div>

<p></p>
<a href="http://www.bailando.ru" target="_new">www.bailando.ru</a><br>
<div class="info">&#1090;&#1072;&#1085;&#1094;&#1077;&#1074;&#1072;&#1083;&#1100;&#1085;&#1072;&#1103; &#1096;&#1082;&#1086;&#1083;&#1072; &laquo;Studio Caribe</div>

<p></p>
<a href="http://www.salsastudio.ru" target="_new">www.salsastudio.ru</a><br>
<div class="info">merengue, Los Angeles Style. &#1086;&#1073;&#1091;&#1095;&#1077;&#1085;&#1080;&#1077; <br>
  &#1089;&#1072;&#1083;&#1100;&#1089;&#1077; 
&#1080; &#1076;&#1088;&#1091;&#1075;&#1080;&#1084; &#1082;&#1083;&#1091;&#1073;&#1085;&#1099;&#1084; <br>
&#1083;&#1072;&#1090;&#1080;&#1085;&#1086;&#1072;&#1084;&#1077;&#1088;&#1080;&#1082;&#1072;&#1085;&#1089;&#1082;&#1080;&#1084; &#1090;&#1072;&#1085;&#1094;&#1072;&#1084;.</div>

<p></p>
<a href="http://www.academydance.ru" target="_new">www.academydance.ru</a><br>
<div class="info">Los Angeles style as well as any other dances.</div>

<p></p>
<a href="http://www.coconuts.ru/ru/parties/afisha" target="_new">www.coconuts.ru/ru/parties/afisha</a><br>
<div class="info">&#1042; &#1089;&#1072;&#1084;&#1086;&#1084; &#1094;&#1077;&#1085;&#1090;&#1088;&#1077; &#1052;&#1086;&#1089;&#1082;&#1074;&#1099; &#1091; <br>
  &#1080;&#1089;&#1090;&#1086;&#1089;&#1082;&#1086;&#1074;&#1072;&#1074;&#1096;&#1080;&#1093;&#1089;&#1103; &#1087;&#1086; &#1101;&#1082;&#1079;&#1086;&#1090;&#1080;&#1082;&#1077; &#1075;&#1086;&#1088;&#1086;&#1078;&#1072;&#1085; <br>
  &#1087;&#1086;&#1103;&#1074;&#1080;&#1083;&#1072;&#1089;&#1100; &#1091;&#1076;&#1080;&#1074;&#1080;&#1090;&#1077;&#1083;&#1100;&#1085;&#1072;&#1103; &#1074;&#1086;&#1079;&#1084;&#1086;&#1078;&#1085;&#1086;&#1089;&#1090;&#1100; <br>
  &#1087;&#1077;&#1088;&#1077;&#1087;&#1088;&#1099;&#1075;&#1085;&#1091;&#1090;&#1100; &#1085;&#1072; &#1050;&#1091;&#1073;&#1091;, &#1044;&#1086;&#1084;&#1080;&#1085;&#1080;&#1082;&#1072;&#1085;&#1091;, <br>
  &#1043;&#1072;&#1080;&#1090;&#1080; &#1080; &#1080; &#1085;&#1072; &#1074;&#1089;&#1077; &#1050;&#1072;&#1088;&#1080;&#1073;&#1099; &#1074; &#1094;&#1077;&#1083;&#1086;&#1084;. &#1050;&#1083;&#1091;&#1073; &#1050;&#1054;&#1050;&#1054;&#1053;&#1040;&#1058;&#1057; !!!</div>

<p></p>
<a href="http://wsdance.com/new/article.html?id=382&incat=&sitelang=" target="_new">wsdance.com/new/article.html?id=382&incat=&sitelang=</a><br>
<div class="info">best adreses for Salsa, Merengue, Cumbia, <br>
  Baladas  clubs in Moskow</div>

<p></p>
<a href="http://salsaviva.narod.ru" target="_new">salsaviva.narod.ru</a><br>
<div class="info">best salsa shool in St. Petersburg, congresses.</div>

<p></p>
<a href="http://salsaviva.narod.ru/ru/Clubs.html" target="_new">salsaviva.narod.ru/ru/Clubs.html</a><br>
<div class="info">programma of latino clubs in St.Peterrsburg</div>

<p></p>
<a href="http://www.salsa.spb.ru" target="_new">www.salsa.spb.ru</a><br>
<div class="info">"Havana Club" in St. Petersburg</div>

<p></p>
<a href="http://buenavista.salsa.spb.ru" target="_new">buenavista.salsa.spb.ru</a><br>
<div class="info">restaurant Buena Vista in St. Petersburg</div>

<p></p>
<a href="http://www.photosalsa.com/indexru.htm" target="_new">www.photosalsa.com/indexru.htm</a><br>
<div class="info">Salsa in Rostov-on-Don</div>

<p></p>
<a href="http://www.photosalsa.com/boogalen.htm" target="_new">www.photosalsa.com/boogalen.htm</a><br>
<div class="info">The school of the year &acirc;&euro;&ldquo; the "Boogaloo" <br>
  club in Rostov  (&#1096;&#1082;&#1086;&#1083;a &#1089;&#1072;&#1083;&#1100;&#1089;&#1099; &#1074; &#1056;&#1086;&#1089;&#1090;&#1086;&#1074;&#1077;)</div>

<p></p>
<a href="http://salsaviva.narod.ru/en/Clubs.html" target="_new">salsaviva.narod.ru/en/Clubs.html</a><br>
<div class="info">Salsa Clubs in Russia</div>

<p></p>
<a href="http://travel.yahoo.com/p-travelguide-2789089-armadillo_moscow-i?action=describe" target="_new">travel.yahoo.com/p-travelguide-2789089-armadillo_moscow-i?action=describe</a><br>
<div class="info">*Armadillo* in Moskow- American-style billiard <br>
  tables and a dance floor. Thursday is <br>
  Latin American night, while Fridays offer a <br>
  Caribbean party with salsa, <br>
  merengue and cha-cha lessons.</div>

<p></p>
<a href="http://cityguides.salsaweb.com/russia/moscow/spanish.htm" target="_new">cityguides.salsaweb.com/russia/moscow/spanish.htm</a><br>
<div class="info">Moskow Spanish page. Bienvenidos a la p&Atilde;&iexcl;gina <br>
  "Salsa en Moskow!</div>

<p></p>
<a href="http://www.latinhits.narod.ru" target="_new">www.latinhits.narod.ru</a><br>
<div class="info">party pichters from Latino partys online</div>

<p></p>
<a href="http://www.photosalsa.com/frontru.htm" target="_new">www.photosalsa.com/frontru.htm</a><br>
<div class="info">&laquo;&#1058;&#1088;&#1077;&#1090;&#1080;&#1081; &#1092;&#1088;&#1086;&#1085;&#1090;&raquo; &mdash; &#1101;&#1090;&#1086; &#1077;&#1078;&#1077;&#1075;&#1086;&#1076;&#1085;&#1099;&#1081; &#1089;&#1072;&#1083;&#1100;&#1089;&#1072;-&#1092;&#1077;&#1089;&#1090;&#1080;&#1074;&#1072;&#1083;&#1100; <br>
  &#1074; &#1056;&#1086;&#1089;&#1090;&#1086;&#1074;&#1077;-&#1085;&#1072;-&#1044;&#1086;&#1085;&#1091;, &#1086;&#1088;&#1075;&#1072;&#1085;&#1080;&#1079;&#1091;&#1077;&#1084;&#1099;&#1081; &#1082;&#1083;&#1091;&#1073;&#1086;&#1084; &laquo;Boogaloo.</div>

<p></p>
<a href="http://www.salsaminsk.com/?PHPSESSID=6bd8259da3a4cdf11945b35f95e2b7dd" target="_new">www.salsaminsk.com/?PHPSESSID=6bd8259da3a4cdf11945b35f95e2b7dd</a><br>
<div class="info">Salsa agenda in Belorussia Minsk</div>

<p></p>
<a href="http://clavellina.narod.ru" target="_new">clavellina.narod.ru</a><br>
<div class="info">salsa in Yekaterinburg
&#1055;&#1077;&#1088;&#1074;&#1072;&#1103; &#1089;&#1090;&#1091;&#1076;&#1080;&#1103; &#1092;&#1083;&#1072;&#1084;&#1077;&#1085;&#1082;&#1086;, <br>
&#1089;&#1072;&#1083;&#1100;&#1089;&#1099; &#1080; &#1072;&#1088;&#1075;&#1077;&#1085;&#1090;&#1080;&#1085;&#1089;&#1082;&#1086;&#1075;&#1086; &#1090;&#1072;&#1085;&#1075;&#1086; &#1074; &#1045;&#1082;&#1072;&#1090;&#1077;&#1088;&#1080;&#1085;&#1073;&#1091;&#1088;&#1075;&#1077;</div>

<p></p>
<a href="http://www.salsa.com.ua" target="_new">www.salsa.com.ua</a><br>
<div class="info">salsa in Ukraine in Kiev</div>

<p></p>
<a href="http://www.salsapasion.net" target="_new">www.salsapasion.net</a><br>
<div class="info">salsa life in Finland Helsinki</div>

<p></p>
<a href="http://www.salsapasion.net/festival" target="_new">www.salsapasion.net/festival</a><br>
<div class="info">Salsa festival in Finland 29-31.7.2005</div>

<p></p>
<a href="http://www.salsastudio.ru" target="_new">www.salsastudio.ru</a><br>
<div class="info">&#1086;&#1073;&#1091;&#1095;&#1077;&#1085;&#1080;&#1077; &#1090;&#1072;&#1085;&#1094;&#1072;&#1084; &#1084;&#1077;&#1088;&#1077;&#1085;&#1075;&#1077;, &#1073;&#1072;&#1095;&#1072;&#1090;&#1072;, &#1089;&#1072;&#1083;&#1100;&#1089;&#1072; <br>
  &#1089;&#1090;&#1080;&#1083;&#1077;&#1081; &#1082;&#1072;&#1089;&#1080;&#1085;&#1086; &#1080; NY</div>

<p></p>
<a href="http://www.panchovilla.ru/site/address.html" target="_new">www.panchovilla.ru/site/address.html</a><br>
<div class="info">&ldquo;Pancho Villa&rdquo; Moskow&rsquo;s best Mexican restaraunt</div>

<p></p>
<a href="http://www.amazonia.ru" target="_new">www.amazonia.ru</a><br>
<div class="info">&#1050;&#1072;&#1078;&#1076;&#1099;&#1081; &#1087;&#1086;&#1085;&#1077;&#1076;&#1077;&#1083;&#1100;&#1085;&#1080;&#1082; - Cool Jazz &#1074;&#1077;&#1095;&#1077;&#1088;&#1080;&#1085;&#1082;&#1080; <br>
  &#1089; 20:00 v Moskve</div>

<p></p>
<a href="http://salsaviva.narod.ru/ru/Congress5pre.html" target="_new">salsaviva.narod.ru/ru/Congress5pre.html</a><br>
<div class="info">&#1052;&#1077;&#1078;&#1076;&#1091;&#1085;&#1072;&#1088;&#1086;&#1076;&#1085;&#1099;&#1081; &#1089;&#1072;&#1083;&#1100;&#1089;&#1072;-&#1082;&#1086;&#1085;&#1075;&#1088;&#1077;&#1089;&#1089; &#1074;<br> 
  &#1057;&#1072;&#1085;&#1082;&#1090;-&#1055;&#1077;&#1090;&#1077;&#1088;&#1073;&#1091;&#1088;&#1075;&#1077;</div>

<p></p>
<a href="http://sharpcat.chat.ru/salsa.html" target="_new">sharpcat.chat.ru/salsa.html</a><br>
<div class="info">&#1044;&#1086;&#1073;&#1088;&#1086; &#1087;&#1086;&#1078;&#1072;&#1083;&#1086;&#1074;&#1072;&#1090;&#1100; &#1085;&#1072; &#1089;&#1090;&#1088;&#1072;&#1085;&#1080;&#1095;&#1082;&#1091; &#1086; &#1089;&#1072;&#1083;&#1089;&#1077;.</div>

<p></p>
<a href="http://www.dancelife.ru" target="_new">www.dancelife.ru</a><br>
<div class="info">tanci v Rossii i v Mire</div>

<p></p>
<a href="http://www.salsaminsk.com" target="_new">www.salsaminsk.com</a><br>
<div class="info">Salsa agenda in Minsk</div>

<p></p>
<a href="http://clavellina.narod.ru" target="_new">clavellina.narod.ru</a><br>
<div class="info">salsa in Yekaterinburg </div>

<p></p>
<a href="http://www.salsa.com.ua" target="_new">www.salsa.com.ua</a><br>
<div class="info">salsa in Ukraine in Kiev</div>

<p></p>
<a href="http://www.salsapower.com/cities/ukraine_kiev.htm" target="_new">www.salsapower.com/cities/ukraine_kiev.htm</a><br>
<div class="info">salsa cites en life in Ukraine  Kiev</div>

<p></p>
<a href="http://www.salsapasion.net" target="_new">www.salsapasion.net</a><br>
<div class="info">salsa life in Finland</div>

<p></p>
<a href="http://www.salsapasion.net/festival" target="_new">www.salsapasion.net/festival</a><br>
<div class="info">Salsa festival in Finland 29-31.7.2005</div>

<p></p>
<a href="http://www.salsastudio.ru" target="_new">www.salsastudio.ru</a><br>
<div class="info">&#1086;&#1073;&#1091;&#1095;&#1077;&#1085;&#1080;&#1077; &#1090;&#1072;&#1085;&#1094;&#1072;&#1084; &#1084;&#1077;&#1088;&#1077;&#1085;&#1075;&#1077;, &#1073;&#1072;&#1095;&#1072;&#1090;&#1072;, <br>
  &#1089;&#1072;&#1083;&#1100;&#1089;&#1072; &#1089;&#1090;&#1080;&#1083;&#1077;&#1081; &#1082;&#1072;&#1089;&#1080;&#1085;&#1086; &#1080; NY</div>

<p></p>
<a href="http://www.amazonia.ru" target="_new">www.amazonia.ru</a><br>
<div class="info">&#1050;&#1072;&#1078;&#1076;&#1099;&#1081; &#1087;&#1086;&#1085;&#1077;&#1076;&#1077;&#1083;&#1100;&#1085;&#1080;&#1082; - Cool Jazz <br>
  &#1074;&#1077;&#1095;&#1077;&#1088;&#1080;&#1085;&#1082;&#1080; &#1089; 20:00</div>

<p></p>
<a href="http://sharpcat.chat.ru/salsa.html" target="_new">sharpcat.chat.ru/salsa.html</a><br>
<div class="info">&#1089;&#1090;&#1088;&#1072;&#1085;&#1080;&#1095;&#1082;a &#1086; &#1089;&#1072;&#1083;&#1089;&#1077;</div>

<p></p>
<a href="http://www.mp3search.ru/album.html?id=25490" target="_new">www.mp3search.ru/album.html?id=25490</a><br>
<div class="info">salsa albums</div>

<p></p>
<a href="http://www.go-magazine.ru/venues/show/1972" target="_new">www.go-magazine.ru/venues/show/1972</a><br>
<div class="info">Drinking & dancing<br>DJs, Europop music and Latin rhythms, <br>
  free salsa lessons</div>

<p></p>
<a href="http://www.go-magazine.ru/venues/show/1582" target="_new">www.go-magazine.ru/venues/show/1582</a><br>
<div class="info">&ldquo;Cabana&rdquo; Entertainment includes blues <br>
  and Latin music -- and a male strip ballet.</div>

<p></p>
<a href="http://eng.moscowout.ru/events/osch" target="_new">eng.moscowout.ru/events/osch</a><br>
<div class="info">Clubs Open Salsa Championship</div>

<p></p>
<a href="http://sashka.spb.ru/gallery/salsa?&page=1" target="_new">sashka.spb.ru/gallery/salsa?&page=1</a><br>
<div class="info">pichters of salsa  in Moskou</div>

<p></p>
<a href="http://www.dirtydancing.ru/e_afisha.html" target="_new">www.dirtydancing.ru/e_afisha.html</a><br>
<div class="info">agenda of "Dirty Dancing" moskou</div>

<p></p>
<a href="http://fridays.rosinter.com/menu/main?photos=yes" target="_new">fridays.rosinter.com/menu/main?photos=yes</a><br>
<div class="info">nice place 2 eat</div>

<p></p>
<a href="http://www.waytorussia.net/SaintPetersburg/WhatsOn/Archive/05April2005WhatsOn.html" target="_new">www.waytorussia.net/SaintPetersburg/WhatsOn/Archive/05April2005WhatsOn.html</a><br>
<div class="info">the most important agenda of night life <br>
  in Sint-Pitersburg</div>

<p></p>
<a href="http://www.salsa.ee/detail" target="_new">www.salsa.ee/detail</a><br>
<div class="info">Salsa life in Tallin (republika of  Estonia)</div>

<p></p>
<a href="http://www.salsa.ee/story/index.php?id=288" target="_new">www.salsa.ee/story/index.php?id=288</a><br>
<div class="info">Salsa Festival in TALLIN 13-16 april 2006</div>

<p></p>
<a href="http://www.jansuki.ee" target="_new">www.jansuki.ee</a><br>
<div class="info">dance studio in Tallin</div>

<p></p>
<a href="http://www.danceact.ee" target="_new">www.danceact.ee</a><br>
<div class="info">dance shool in  (rep. Estonia)</div>

<p></p>
<a href="http://www.mambo.ee" target="_new">www.mambo.ee</a><br>
<div class="info">salsa shool in Tallin</div>

<p></p>
<a href="http://www.hot.ee/tkstep" target="_new">www.hot.ee/tkstep</a><br>
<div class="info">salsa shool Tallin republica of Estonia</div>

<p></p>
<a href="http://www.dubjazzsalsa.com" target="_new">www.dubjazzsalsa.com</a><br>
<div class="info">Aladin's cave of Salsa Music in Helsinki <br>
  (North Tallinn). Well worth a visit for <br>
  all Estonian Latin music lovers</div>

<p></p>
<a href="http://www.hot.ee/tkstep" target="_new">www.hot.ee/tkstep</a><br>
<div class="info">shool of tango y Flamengo in Estonia Tallin</div>

<p></p>
<a href="http://uus.tantsutarbed.ee" target="_new">uus.tantsutarbed.ee</a><br>
<div class="info">Shop for Dance wear & shoes, Tallinn</div>

<p></p>
<a href="http://www.salsaweb.cz/index.php?la=en" target="_new">www.salsaweb.cz/index.php?la=en</a><br>
<div class="info">Czech Republic<br>Marika, Dushan and S.E.C.S, busy Salsa <br>
  troup in Prague</div>

<p></p>
<a href="http://www.salsaweb.cz/kluby.php?la=en&co=1" target="_new">www.salsaweb.cz/kluby.php?la=en&co=1</a><br>
<div class="info">Salsa club in Czech rep in Praga</div>

<p></p>
<a href="http://www.salsaweb.cz/kluby.php?la=en&co=2" target="_new">www.salsaweb.cz/kluby.php?la=en&co=2</a><br>
<div class="info">Tropison, salsa diskotek in    (Praga Chez. Rep.)</div>

<p></p>
<a href="http://www.salsaweb.cz/kluby.php?la=en&co=3" target="_new">www.salsaweb.cz/kluby.php?la=en&co=3</a><br>
<div class="info">salsa  party in &quot;Aperretivo&quot;   (Praga Chez. Rep.)</div>

<p></p>
<a href="http://www.salsaweb.cz/kluby.php?la=en&co=6" target="_new">www.salsaweb.cz/kluby.php?la=en&co=6</a><br>
<div class="info">Tropicana night in &quot;Manes&quot;  (Praga Chez. Rep.)</div>

<p></p>
<a href="http://www.salsaweb.cz/kurzy.php?la=en" target="_new">www.salsaweb.cz/kurzy.php?la=en</a><br>
<div class="info">salsa courses in  Praga Chez. Rep.</div>

<p></p>
<a href="http://www.salsariga.lv" target="_new">www.salsariga.lv</a><br>
<div class="info">salsa life in Republica of LATVIA in Riga</div>

<p></p>
<a href="http://www.salsariga.lv/index.php?id=en-links&m=l" target="_new">www.salsariga.lv/index.php?id=en-links&m=l</a><br>
<div class="info">Salsa also in Riga</div>

<p></p>
<a href="http://www.salsapower.com/cities/index.htm" target="_new">www.salsapower.com/cities/index.htm</a><br>
<div class="info">Salsa site&rsquo;s International</div>

<p></p>
<a href="http://www.salsapower.com/cities/russia_novosibirsk.htm" target="_new">www.salsapower.com/cities/russia_novosibirsk.htm</a><br>
<div class="info">New new! Salsa in Novosibirsk!!! Russia</div>

<p></p>
<a href="http://www.absolutesalsa.com" target="_new">www.absolutesalsa.com</a><br>
<div class="info">ABSOLUTE SALSA - TROPICAL <br>
  ELEMENTARY RUEDA GROUP</div>

<p></p>
<a href="http://www.sierramaestra.ru" target="_new">www.sierramaestra.ru</a><br>
<div class="info">salsa en swing dance studio in Moskou</div>

<p></p>
<a href="http://www.sierramaestra.ru/shops_msc.html" target="_new">www.sierramaestra.ru/shops_msc.html</a><br>
<div class="info">salsa close, shoes accessories for <br>
  dancing, addresses of the most shops</div>

<p></p>
<a href="http://www.estadance.su" target="_new">www.estadance.su</a><br>
<div class="info">dance shop in Moskou, &#1069;&#1057;&#1058;&#1040; <br>
  &#1072;&#1088;&#1090;-&#1089;&#1072;&#1083;&#1086;&#1085; - &#1090;&#1086;&#1074;&#1072;&#1088;&#1099; &#1076;&#1083;&#1103; &#1090;&#1072;&#1085;&#1094;&#1072; &#1080; &#1090;&#1077;&#1072;&#1090;&#1088;&#1072;</div>

<p></p>
<a href="http://www.soloplus.ru" target="_new">www.soloplus.ru</a><br>
<div class="info">&#1054;&#1089;&#1085;&#1086;&#1074;&#1085;&#1086;&#1077; &#1085;&#1072;&#1087;&#1088;&#1072;&#1074;&#1083;&#1077;&#1085;&#1080;&#1077; &#1074; &#1088;&#1072;&#1073;&#1086;&#1090;&#1077; - <br>
  &#1087;&#1086;&#1096;&#1080;&#1074; &#1086;&#1073;&#1091;&#1074;&#1080; &#1080; &#1082;&#1086;&#1089;&#1090;&#1102;&#1084;&#1086;&#1074;&#1076;&#1083;&#1103; &#1089;&#1087;&#1086;&#1088;&#1090;&#1080;&#1074;&#1085;&#1099;&#1093; <br>
  &#1073;&#1072;&#1083;&#1100;&#1085;&#1099;&#1093; &#1090;&#1072;&#1085;&#1094;&#1077;&#1074;</div>

<p></p>
<a href="http://www.masca.ru" target="_new">www.masca.ru</a><br>
<div class="info">rent and sell clothes for dancing, &#1074;&#1089;&#1077;&#1075;&#1076;&#1072; <br>
  &#1073;&#1086;&#1083;&#1100;&#1096;&#1086;&#1081; &#1074;&#1099;&#1073;&#1086;&#1088; &#1092;&#1086;&#1088;&#1084;&#1099; &#1076;&#1083;&#1103; &#1093;&#1086;&#1088;&#1077;&#1086;&#1075;&#1088;&#1072;&#1092;&#1080;&#1080;!</div>

<p></p>
<a href="http://www.kostumer.ru" target="_new">www.kostumer.ru</a><br>
<div class="info">&laquo;&#1055;&#1086;&#1089;&#1083;&#1077;&#1076;&#1085;&#1080;&#1077; &#1090;&#1077;&#1085;&#1076;&#1077;&#1085;&#1094;&#1080;&#1080; &#1084;&#1086;&#1076;&#1099; &#1074; <br>
  &#1090;&#1072;&#1085;&#1094;&#1077;&#1074;&#1072;&#1083;&#1100;&#1085;&#1086;&#1084; &#1082;&#1086;&#1089;&#1090;&#1102;&#1084;&#1077;. &#1057;&#1077;&#1079;&#1086;&#1085; 2005- 2006&#1075;&raquo;</div>

<p></p>
<a href="http://www.grishko.ru/start" target="_new">www.grishko.ru/start</a><br>
<div class="info">dance wear addresses in Moskou en regions</div>

<p></p>
<a href="http://www.thetunnel.ru/main.html" target="_new">www.thetunnel.ru/main.html</a><br>
<div class="info">&#1050;&#1083;&#1091;&#1073;-&#1088;&#1077;&#1089;&#1090;&#1086;&#1088;&#1072;&#1085; (exclusief) in Moskou</div>

<p></p>
<a href="http://old-havana.ru/main.php?&w=1024" target="_new">old-havana.ru/main.php?&w=1024</a><br>
<div class="info">Restaurant OLD HAVANA in Moskou Russia</div>

<p></p>
<a href="http://www.s-tres.kiev.ua" target="_new">www.s-tres.kiev.ua</a><br>
<div class="info">salsa dance Sudio &ldquo;S- Tress&rdquo; in Kiev <br>
  (Ukraine) + programma</div>

<p></p>
<a href="http://www.academydance.ru" target="_new">www.academydance.ru</a><br>
<div class="info">Salsa , Merengue, cha-cha-cha, rumba, <br>
  academy of dance in Moskou, addresses</div>

<p></p>
<a href="http://www.salsa-union.ru" target="_new">www.salsa-union.ru</a><br>
<div class="info">Hottest  latino Party&rsquo;s News eterythink <br>
  about enjoying it! Stay in Touch</div>

<p></p>
<a href="http://www.salsa-union.ru/clubs/njoy.htm" target="_new">www.salsa-union.ru/clubs/njoy.htm</a><br>
<div class="info">cafe N-Joy hot salsa party&rsquo;s on vryday & satarday</div>

<p></p>
<a href="http://www.salsa-kubana.ru" target="_new">www.salsa-kubana.ru</a><br>
<div class="info">Cuban salsa shool (Krasnodar)</div>

<p></p>
<a href="http://www.salsacongress.ru" target="_new">www.salsacongress.ru</a><br>
<div class="info">all about Salsa festival in Russia (congress)<br> 
  in Rostov na Donu</div>

<p></p>
<a href="http://www.salsacongress.ru/index.php?categoryid=14" target="_new">www.salsacongress.ru/index.php?categoryid=14</a><br>
<div class="info">hotel addressees during the festival</div>

<p></p>
<a href="http://www.casa-latina.ru" target="_new">www.casa-latina.ru</a><br>
<div class="info">Shool of Dance _ Club in St-Pitersburg <br>
  `Casa-Latina`
&#1064;&#1082;&#1086;&#1083;&#1072; &#1090;&#1072;&#1085;&#1094;&#1077;&#1074; &#1080; &#1085;&#1086;&#1095;&#1085;&#1086;&#1081; <br>
&#1090;&#1072;&#1085;&#1094;&#1077;&#1074;&#1072;&#1083;&#1100;&#1085;&#1099;&#1081; &#1082;&#1083;&#1091;&#1073; Casa latina &#1087;&#1088;&#1080;&#1074;&#1077;&#1090;&#1089;&#1090;&#1074;&#1091;&#1077;&#1090; &#1042;&#1072;&#1089;</div>

<p></p>
<a href="http://www.agnostus.ru" target="_new">www.agnostus.ru</a><br>
<div class="info">dancing and lifesyl</div>

<p></p>
<a href="http://www.sibsalsa.ru/index.htm" target="_new">www.sibsalsa.ru/index.htm</a><br>
<div class="info">About salsa in Novosibirsk</div>

<p></p>
<a href="http://www.sierramaestra.ru/shops_spb.html" target="_new">www.sierramaestra.ru/shops_spb.html</a><br>
<div class="info">adress for dance shops in St.Pitersburg</div>

<p></p>
<a href="http://www.musicasalsa.de" target="_new">www.musicasalsa.de</a><br>
<div class="info">salsa Musika</div>

<p></p>
<a href="http://www.salsavideo.ru" target="_new">www.salsavideo.ru</a><br>
<div class="info">Salsa video</div>

<p></p>
<a href="http://www.millionmovesman.com/main.htm" target="_new">www.millionmovesman.com/main.htm</a><br>
<div class="info">Salsa move&acute;s</div>

<p></p>
<a href="http://www.latin.ru:8101/festiest/festi3.shtml" target="_new">www.latin.ru:8101/festiest/festi3.shtml</a><br>
<div class="info">festival latino amerikan Student&acute;s</div>

<p></p>
<a href="http://www.latin.ru:8101/index.html" target="_new">www.latin.ru:8101/index.html</a><br>
<div class="info">Most IMPORTANT site for Latino in Russia!!</div>

<p></p>
<a href="http://www.latin.ru:8101/celer" target="_new">www.latin.ru:8101/celer</a><br>
<div class="info">CLUB DE ESTUDIANTES LATINOS EN RUSIA</div>

<p></p>
<a href="http://www.latin.ru:8101/embajadasRu.shtml" target="_new">www.latin.ru:8101/embajadasRu.shtml</a><br>
<div class="info">&#1055;&#1054;&#1057;&#1054;&#1051;&#1068;&#1057;&#1058;&#1042;&#1040; &#1057;&#1058;&#1056;&#1040;&#1053; &#1051;&#1040;&#1058;&#1048;&#1053;&#1057;&#1050;&#1054;&#1049; &#1040;&#1052;&#1045;&#1056;&#1048;&#1050;&#1048; <br>
  &#1042; &#1052;&#1054;&#1057;&#1050;&#1042;&#1045;
Ambasades of <br>
Latino Amerikan 
Countrys in Moskou</div>

<p></p>
<a href="http://www.latin.ru/dominica/merengue.shtml" target="_new">www.latin.ru/dominica/merengue.shtml</a><br>
<div class="info">all about Merengue</div>

<p></p>
<a href="http://www.latin.ru/esp" target="_new">www.latin.ru/esp</a><br>
<div class="info">information about Russia in Spanol</div>

<p></p>
<a href="http://www.prolatino.ru/eng_index.htm" target="_new">www.prolatino.ru/eng_index.htm</a><br>
<div class="info">projecto Latino, Show group Proyecto Latino</div>

<p></p>
<a href="http://www.opencity.ru/Rest/nc-group.asp?group=salsaboys" target="_new">www.opencity.ru/Rest/nc-group.asp?group=salsaboys</a><br>
<div class="info">salsa group in Russia</div>

<p></p>
<a href="http://www.2ostrov.ru/photoes_031220_luzhniki_04.htm" target="_new">www.2ostrov.ru/photoes_031220_luzhniki_04.htm</a><br>
<div class="info">dance shool in Russia</div>

